-- تحديث جدول المبيعات ليشمل user_id
CREATE TABLE IF NOT EXISTS public.sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    price DECIMAL(10,2) NOT NULL DEFAULT 0,
    total DECIMAL(10,2) NOT NULL DEFAULT 0,
    payment_method TEXT,
    customer_name TEXT,
    sale_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    warehouse_id UUID REFERENCES public.warehouses(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- إعداد Row Level Security (RLS)
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;

-- سياسة القراءة
CREATE POLICY "Enable read access for user's warehouse sales" ON public.sales
    FOR SELECT USING (
        auth.uid() = user_id OR 
        warehouse_id IN (SELECT id FROM public.warehouses WHERE user_id = auth.uid())
    );

-- سياسة الإضافة
CREATE POLICY "Enable insert access for user's warehouse sales" ON public.sales
    FOR INSERT WITH CHECK (
        auth.uid() = user_id OR 
        warehouse_id IN (SELECT id FROM public.warehouses WHERE user_id = auth.uid())
    );

-- سياسة الحذف
CREATE POLICY "Enable delete access for user's warehouse sales" ON public.sales
    FOR DELETE USING (
        auth.uid() = user_id OR 
        warehouse_id IN (SELECT id FROM public.warehouses WHERE user_id = auth.uid())
    );
