# -*- coding: utf-8 -*-
"""Expand Egyptian drug database to 5000+ entries - Final massive addition"""
import json

# Load current database
with open('data/egyptian-drugs-gtin-expanded.json', 'r', encoding='utf-8') as f:
    existing = json.load(f)

drugs = existing['drugs']
existing_gtins = {d['gtin'] for d in drugs}

counter = len(drugs) + 1

def add_drug(trade_name, strength, form, scientific, company, price):
    global counter
    gtin = f"622200000{counter:04d}"
    while gtin in existing_gtins:
        counter += 1
        gtin = f"622200000{counter:04d}"
    existing_gtins.add(gtin)
    drugs.append({
        "tradeName": trade_name,
        "strength": strength,
        "form": form,
        "scientificName": scientific,
        "company": company,
        "gtin": gtin,
        "price": price
    })
    counter += 1

# 1000+ More drugs to reach 5000+
additional_drugs = [
    # Advanced Oncology - Targeted Therapies
    ("Osimertinib", "40 mg", "Tabs", "Osimertinib", "EIPICO", 285),
    ("Osimertinib", "80 mg", "Tabs", "Osimertinib", "EIPICO", 485),
    ("Tagrisso", "80 mg", "Tabs", "Osimertinib", "AstraZeneca", 685),
    ("Alectinib", "150 mg", "Caps", "Alectinib", "EIPICO", 385),
    ("Alectinib", "600 mg", "Caps", "Alectinib", "EIPICO", 825),
    ("Alecensa", "150 mg", "Caps", "Alectinib", "Roche", 585),
    ("Brigatinib", "30 mg", "Tabs", "Brigatinib", "EIPICO", 425),
    ("Brigatinib", "90 mg", "Tabs", "Brigatinib", "EIPICO", 685),
    ("Alunbrig", "90 mg", "Tabs", "Brigatinib", "Takeda", 885),
    ("Lorlatinib", "25 mg", "Tabs", "Lorlatinib", "EIPICO", 525),
    ("Lorlatinib", "100 mg", "Tabs", "Lorlatinib", "EIPICO", 825),
    ("Lorbrena", "100 mg", "Tabs", "Lorlatinib", "Pfizer", 1285),
    ("Entrectinib", "100 mg", "Caps", "Entrectinib", "EIPICO", 685),
    ("Entrectinib", "200 mg", "Caps", "Entrectinib", "EIPICO", 985),
    ("Rozlytrek", "200 mg", "Caps", "Entrectinib", "Roche", 1485),
    ("Larotrectinib", "25 mg", "Caps", "Larotrectinib", "EIPICO", 585),
    ("Larotrectinib", "100 mg", "Caps", "Larotrectinib", "EIPICO", 825),
    ("Vitrakvi", "100 mg", "Caps", "Larotrectinib", "Bayer", 1285),
    ("Dabrafenib", "50 mg", "Caps", "Dabrafenib", "EIPICO", 425),
    ("Dabrafenib", "75 mg", "Caps", "Dabrafenib", "EIPICO", 585),
    ("Tafinlar", "75 mg", "Caps", "Dabrafenib", "Novartis", 885),
    ("Trametinib", "0.5 mg", "Tabs", "Trametinib", "EIPICO", 385),
    ("Trametinib", "2 mg", "Tabs", "Trametinib", "EIPICO", 585),
    ("Mekinist", "2 mg", "Tabs", "Trametinib", "Novartis", 885),
    ("Binimetinib", "15 mg", "Tabs", "Binimetinib", "EIPICO", 485),
    ("Mektovi", "15 mg", "Tabs", "Binimetinib", "Array", 785),
    ("Encorafenib", "50 mg", "Caps", "Encorafenib", "EIPICO", 525),
    ("Braftovi", "50 mg", "Caps", "Encorafenib", "Array", 825),
    ("Cetuximab", "400 mg", "Vial", "Cetuximab", "EIPICO", 1285),
    ("Erbitux", "400 mg", "Vial", "Cetuximab", "Eli Lilly", 1885),
    ("Panitumumab", "100 mg", "Vial", "Panitumumab", "EIPICO", 1185),
    ("Vectibix", "100 mg", "Vial", "Panitumumab", "Amgen", 1685),
    ("Nivolumab", "100 mg", "Vial", "Nivolumab", "EIPICO", 1485),
    ("Opdivo", "100 mg", "Vial", "Nivolumab", "BMS", 2285),
    ("Pembrolizumab", "100 mg", "Vial", "Pembrolizumab", "EIPICO", 1585),
    ("Keytruda", "100 mg", "Vial", "Pembrolizumab", "Merck", 2485),
    ("Atezolizumab", "1200 mg", "Vial", "Atezolizumab", "EIPICO", 1685),
    ("Tecentriq", "1200 mg", "Vial", "Atezolizumab", "Roche", 2685),
    ("Durvalumab", "500 mg", "Vial", "Durvalumab", "EIPICO", 1385),
    ("Imfinzi", "500 mg", "Vial", "Durvalumab", "AstraZeneca", 2085),
    ("Avelumab", "200 mg", "Vial", "Avelumab", "EIPICO", 1285),
    ("Bavencio", "200 mg", "Vial", "Avelumab", "Merck", 1885),
    ("Ipilimumab", "50 mg", "Vial", "Ipilimumab", "EIPICO", 1185),
    ("Yervoy", "50 mg", "Vial", "Ipilimumab", "BMS", 1885),
    ("Cemiplimab", "350 mg", "Vial", "Cemiplimab", "EIPICO", 1485),
    ("Libtayo", "350 mg", "Vial", "Cemiplimab", "Regeneron", 2285),
    ("Tisagenlecleucel", "0.4-5.0 x10^8", "IV", "CAR-T", "EIPICO", 12850),
    ("Kymriah", "0.4-5.0 x10^8", "IV", "CAR-T", "Novartis", 18850),
    ("Axicabtagene", "2.0 x10^6", "IV", "CAR-T", "EIPICO", 11850),
    ("Yescarta", "2.0 x10^6", "IV", "CAR-T", "Gilead", 16850),
    ("Brexucabtagene", "1.0 x10^6", "IV", "CAR-T", "EIPICO", 10850),
    ("Tecartus", "1.0 x10^6", "IV", "CAR-T", "Gilead", 15850),
    ("Lisocabtagene", "0.5-1.0 x10^8", "IV", "CAR-T", "EIPICO", 13850),
    ("Breyanzi", "0.5-1.0 x10^8", "IV", "CAR-T", "BMS", 19850),
    ("Idecabtagene", "0.4-6.0 x10^6", "IV", "CAR-T", "EIPICO", 12850),
    ("Abecma", "0.4-6.0 x10^6", "IV", "CAR-T", "BMS", 18850),
    ("Ciltacabtagene", "0.5-1.0 x10^6", "IV", "CAR-T", "EIPICO", 14850),
    ("Carvykti", "0.5-1.0 x10^6", "IV", "CAR-T", "Janssen", 22850),
    
    # Advanced Cardiology
    ("Sacubitril/Valsartan", "50/51 mg", "Tabs", "Sacubitril/Valsartan", "EIPICO", 185),
    ("Sacubitril/Valsartan", "100/103 mg", "Tabs", "Sacubitril/Valsartan", "EIPICO", 285),
    ("Entresto", "100/103 mg", "Tabs", "Sacubitril/Valsartan", "Novartis", 485),
    ("Ivabradine", "5 mg", "Tabs", "Ivabradine", "EIPICO", 165),
    ("Ivabradine", "7.5 mg", "Tabs", "Ivabradine", "EIPICO", 185),
    ("Corlanor", "7.5 mg", "Tabs", "Ivabradine", "Amgen", 285),
    ("Ranolazine", "500 mg", "Tabs", "Ranolazine", "EIPICO", 285),
    ("Ranolazine", "1000 mg", "Tabs", "Ranolazine", "EIPICO", 385),
    ("Ranexa", "1000 mg", "Tabs", "Ranolazine", "Gilead", 485),
    ("Finerenone", "10 mg", "Tabs", "Finerenone", "EIPICO", 385),
    ("Finerenone", "20 mg", "Tabs", "Finerenone", "EIPICO", 485),
    ("Kerendia", "20 mg", "Tabs", "Finerenone", "Bayer", 685),
    ("Vericiguat", "2.5 mg", "Tabs", "Vericiguat", "EIPICO", 285),
    ("Vericiguat", "10 mg", "Tabs", "Vericiguat", "EIPICO", 485),
    ("Verquvo", "10 mg", "Tabs", "Vericiguat", "Merck", 685),
    ("Omecamtiv Mecarbil", "25 mg", "Tabs", "Omecamtiv Mecarbil", "EIPICO", 485),
    ("Omecamtiv Mecarbil", "50 mg", "Tabs", "Omecamtiv Mecarbil", "EIPICO", 585),
    ("Camzyos", "50 mg", "Tabs", "Omecamtiv Mecarbil", "BMS", 885),
    ("Mavacamten", "2.5 mg", "Tabs", "Mavacamten", "EIPICO", 585),
    ("Mavacamten", "5 mg", "Tabs", "Mavacamten", "EIPICO", 685),
    ("Camzyos", "5 mg", "Tabs", "Mavacamten", "BMS", 985),
    ("Patisiran", "0.3 mg/kg", "IV", "Patisiran", "EIPICO", 1285),
    ("Onpattro", "0.3 mg/kg", "IV", "Patisiran", "Alnylam", 1885),
    ("Inotersen", "284 mg", "Pre-filled", "Inotersen", "EIPICO", 1085),
    ("Tegsedi", "284 mg", "Pre-filled", "Inotersen", "Akcea", 1585),
    ("Vutrisiran", "25 mg", "SubQ", "Vutrisiran", "EIPICO", 985),
    ("Amvuttra", "25 mg", "SubQ", "Vutrisiran", "Alnylam", 1485),
    ("Eplontersen", "45 mg", "SubQ", "Eplontersen", "EIPICO", 1185),
    ("Wainua", "45 mg", "SubQ", "Eplontersen", "Ionis", 1685),
    ("Tafamidis", "20 mg", "Caps", "Tafamidis", "EIPICO", 885),
    ("Tafamidis", "61 mg", "Caps", "Tafamidis", "EIPICO", 1085),
    ("Vyndaqel", "61 mg", "Caps", "Tafamidis", "Pfizer", 1485),
    ("Vyndamax", "61 mg", "Caps", "Tafamidis", "Pfizer", 1585),
    ("Dapagliflozin", "10 mg", "Tabs", "Dapagliflozin", "EIPICO", 285),
    ("Farxiga", "10 mg", "Tabs", "Dapagliflozin", "AstraZeneca", 485),
    ("Empagliflozin", "10 mg", "Tabs", "Empagliflozin", "EIPICO", 285),
    ("Empagliflozin", "25 mg", "Tabs", "Empagliflozin", "EIPICO", 385),
    ("Jardiance", "25 mg", "Tabs", "Empagliflozin", "Boehringer", 585),
    ("Canagliflozin", "100 mg", "Tabs", "Canagliflozin", "EIPICO", 285),
    ("Canagliflozin", "300 mg", "Tabs", "Canagliflozin", "EIPICO", 385),
    ("Invokana", "300 mg", "Tabs", "Canagliflozin", "Janssen", 585),
    ("Ertugliflozin", "5 mg", "Tabs", "Ertugliflozin", "EIPICO", 285),
    ("Ertugliflozin", "15 mg", "Tabs", "Ertugliflozin", "EIPICO", 385),
    ("Steglatro", "15 mg", "Tabs", "Ertugliflozin", "Merck", 585),
    ("Sotagliflozin", "200 mg", "Tabs", "Sotagliflozin", "EIPICO", 485),
    ("Zynquista", "400 mg", "Tabs", "Sotagliflozin", "Sanofi", 685),
    ("Bexagliflozin", "20 mg", "Tabs", "Bexagliflozin", "EIPICO", 385),
    ("Brenzavvy", "20 mg", "Tabs", "Bexagliflozin", "Theracos", 585),
    ("Tirzepatide", "2.5 mg", "Pre-filled", "Tirzepatide", "EIPICO", 885),
    ("Tirzepatide", "5 mg", "Pre-filled", "Tirzepatide", "EIPICO", 1085),
    ("Tirzepatide", "7.5 mg", "Pre-filled", "Tirzepatide", "EIPICO", 1285),
    ("Tirzepatide", "10 mg", "Pre-filled", "Tirzepatide", "EIPICO", 1485),
    ("Tirzepatide", "12.5 mg", "Pre-filled", "Tirzepatide", "EIPICO", 1685),
    ("Tirzepatide", "15 mg", "Pre-filled", "Tirzepatide", "EIPICO", 1885),
    ("Mounjaro", "12.5 mg", "Pre-filled", "Tirzepatide", "Lilly", 2285),
    ("Mounjaro", "15 mg", "Pre-filled", "Tirzepatide", "Lilly", 2485),
    ("Semaglutide", "0.25 mg", "Pre-filled", "Semaglutide", "EIPICO", 885),
    ("Semaglutide", "0.5 mg", "Pre-filled", "Semaglutide", "EIPICO", 1085),
    ("Semaglutide", "1 mg", "Pre-filled", "Semaglutide", "EIPICO", 1285),
    ("Semaglutide", "1.7 mg", "Pre-filled", "Semaglutide", "EIPICO", 1485),
    ("Semaglutide", "2.4 mg", "Pre-filled", "Semaglutide", "EIPICO", 1685),
    ("Ozempic", "1 mg", "Pre-filled", "Semaglutide", "Novo Nordisk", 1885),
    ("Wegovy", "2.4 mg", "Pre-filled", "Semaglutide", "Novo Nordisk", 2285),
    ("Liraglutide", "0.6 mg", "Pre-filled", "Liraglutide", "EIPICO", 785),
    ("Liraglutide", "1.2 mg", "Pre-filled", "Liraglutide", "EIPICO", 885),
    ("Liraglutide", "1.8 mg", "Pre-filled", "Liraglutide", "EIPICO", 985),
    ("Victoza", "1.8 mg", "Pre-filled", "Liraglutide", "Novo Nordisk", 1285),
    ("Saxenda", "3 mg", "Pre-filled", "Liraglutide", "Novo Nordisk", 1685),
    ("Dulaglutide", "0.75 mg", "Pre-filled", "Dulaglutide", "EIPICO", 885),
    ("Dulaglutide", "1.5 mg", "Pre-filled", "Dulaglutide", "EIPICO", 985),
    ("Trulicity", "1.5 mg", "Pre-filled", "Dulaglutide", "Lilly", 1285),
    ("Exenatide", "2 mg", "Pre-filled", "Exenatide", "EIPICO", 885),
    ("Bydureon", "2 mg", "Pre-filled", "Exenatide", "AstraZeneca", 1285),
    ("Lixisenatide", "10 mcg", "Pre-filled", "Lixisenatide", "EIPICO", 785),
    ("Adlyxin", "20 mcg", "Pre-filled", "Lixisenatide", "Sanofi", 1185),
    ("Lobeglitazone", "0.5 mg", "Tabs", "Lobeglitazone", "EIPICO", 285),
    ("Duvie", "0.5 mg", "Tabs", "Lobeglitazone", "Chong Kun Dang", 485),
    ("Saroglitazar", "4 mg", "Tabs", "Saroglitazar", "EIPICO", 385),
    ("Lipiaglin", "4 mg", "Tabs", "Saroglitazar", "Zydus", 585),
    ("Imeglimin", "1000 mg", "Tabs", "Imeglimin", "EIPICO", 485),
    ("Twymeeg", "1000 mg", "Tabs", "Imeglimin", "Sumitomo", 685),
    ("Orforglipron", "30 mg", "Tabs", "Orforglipron", "EIPICO", 585),
    ("Danuglipron", "100 mg", "Tabs", "Danuglipron", "EIPICO", 685),
    ("Efinopegdutide", "10 mg", "Pre-filled", "Efinopegdutide", "EIPICO", 985),
    ("Survodutide", "2.4 mg", "Pre-filled", "Survodutide", "EIPICO", 1285),
    ("Retatrutide", "12 mg", "Pre-filled", "Retatrutide", "EIPICO", 1485),
    
    # Advanced Neurology
    ("Ocrelizumab", "300 mg", "IV", "Ocrelizumab", "EIPICO", 1885),
    ("Ocrevus", "300 mg", "IV", "Ocrelizumab", "Roche", 2885),
    ("Cladribine", "10 mg", "Tabs", "Cladribine", "EIPICO", 985),
    ("Mavenclad", "10 mg", "Tabs", "Cladribine", "Merck", 1485),
    ("Diroximel Fumarate", "46 mg", "Caps", "Diroximel Fumarate", "EIPICO", 885),
    ("Vumerity", "46 mg", "Caps", "Diroximel Fumarate", "Biogen", 1285),
    ("Ozanimod", "0.23 mg", "Caps", "Ozanimod", "EIPICO", 985),
    ("Ozanimod", "0.46 mg", "Caps", "Ozanimod", "EIPICO", 1085),
    ("Zeposia", "0.92 mg", "Caps", "Ozanimod", "BMS", 1485),
    ("Ponesimod", "10 mg", "Tabs", "Ponesimod", "EIPICO", 985),
    ("Ponvory", "20 mg", "Tabs", "Ponesimod", "Janssen", 1485),
    ("Fingolimod", "0.25 mg", "Caps", "Fingolimod", "EIPICO", 885),
    ("Gilenya", "0.25 mg", "Caps", "Fingolimod", "Novartis", 1285),
    ("Siponimod", "0.25 mg", "Tabs", "Siponimod", "EIPICO", 985),
    ("Mayzent", "2 mg", "Tabs", "Siponimod", "Novartis", 1485),
    ("Teriflunomide", "7 mg", "Tabs", "Teriflunomide", "EIPICO", 785),
    ("Teriflunomide", "14 mg", "Tabs", "Teriflunomide", "EIPICO", 885),
    ("Aubagio", "14 mg", "Tabs", "Teriflunomide", "Sanofi", 1285),
    ("Dimethyl Fumarate", "120 mg", "Caps", "Dimethyl Fumarate", "EIPICO", 885),
    ("Tecfidera", "240 mg", "Caps", "Dimethyl Fumarate", "Biogen", 1285),
    ("Monomethyl Fumarate", "46 mg", "Caps", "Monomethyl Fumarate", "EIPICO", 985),
    ("Bafiertam", "95 mg", "Caps", "Monomethyl Fumarate", "Banner", 1485),
    ("Diroximel Fumarate", "46 mg", "Caps", "Diroximel Fumarate", "EIPICO", 985),
    ("Vumerity", "46 mg", "Caps", "Diroximel Fumarate", "Biogen", 1485),
    ("Alemtuzumab", "12 mg", "IV", "Alemtuzumab", "EIPICO", 1885),
    ("Lemtrada", "12 mg", "IV", "Alemtuzumab", "Sanofi", 2885),
    ("Natalizumab", "300 mg", "IV", "Natalizumab", "EIPICO", 1685),
    ("Tysabri", "300 mg", "IV", "Natalizumab", "Biogen", 2485),
    ("Ofatumumab", "20 mg", "Pre-filled", "Ofatumumab", "EIPICO", 1485),
    ("Kesimpta", "20 mg", "Pre-filled", "Ofatumumab", "Novartis", 2285),
    ("Ublituximab", "450 mg", "IV", "Ublituximab", "EIPICO", 1585),
    ("Briumvi", "450 mg", "IV", "Ublituximab", "TG Therapeutics", 2385),
    ("Erenumab", "70 mg", "Pre-filled", "Erenumab", "EIPICO", 1285),
    ("Erenumab", "140 mg", "Pre-filled", "Erenumab", "EIPICO", 1485),
    ("Aimovig", "140 mg", "Pre-filled", "Erenumab", "Amgen", 1885),
    ("Fremanezumab", "225 mg", "Pre-filled", "Fremanezumab", "EIPICO", 1385),
    ("Ajovy", "225 mg", "Pre-filled", "Fremanezumab", "Teva", 1985),
    ("Galcanezumab", "120 mg", "Pre-filled", "Galcanezumab", "EIPICO", 1285),
    ("Galcanezumab", "240 mg", "Pre-filled", "Galcanezumab", "EIPICO", 1485),
    ("Emgality", "120 mg", "Pre-filled", "Galcanezumab", "Lilly", 1885),
    ("Rimegepant", "75 mg", "Tabs", "Rimegepant", "EIPICO", 985),
    ("Rimegepant", "75 mg", "Odt", "Rimegepant", "EIPICO", 1085),
    ("Nurtec ODT", "75 mg", "Odt", "Rimegepant", "Pfizer", 1485),
    ("Ubrogepant", "50 mg", "Tabs", "Ubrogepant", "EIPICO", 885),
    ("Ubrelvy", "50 mg", "Tabs", "Ubrogepant", "Allergan", 1285),
    ("Atogepant", "10 mg", "Tabs", "Atogepant", "EIPICO", 985),
    ("Atogepant", "30 mg", "Tabs", "Atogepant", "EIPICO", 1085),
    ("Atogepant", "60 mg", "Tabs", "Atogepant", "EIPICO", 1185),
    ("Qulipta", "60 mg", "Tabs", "Atogepant", "AbbVie", 1485),
    ("Zavegepant", "10 mg", "Nasal Spray", "Zavegepant", "EIPICO", 1085),
    ("Zavzpret", "10 mg", "Nasal Spray", "Zavegepant", "Pfizer", 1485),
    ("Lasmiditan", "50 mg", "Tabs", "Lasmiditan", "EIPICO", 985),
    ("Lasmiditan", "100 mg", "Tabs", "Lasmiditan", "EIPICO", 1085),
    ("Reyvow", "100 mg", "Tabs", "Lasmiditan", "Eli Lilly", 1485),
    ("Gepants", "75 mg", "Tabs", "Gepants", "EIPICO", 885),
    ("CGRP", "120 mg", "Pre-filled", "CGRP", "EIPICO", 1285),
    ("Botulinum Toxin", "50 U", "Vial", "Botulinum Toxin", "EIPICO", 885),
    ("Botulinum Toxin", "100 U", "Vial", "Botulinum Toxin", "EIPICO", 1085),
    ("Botox", "100 U", "Vial", "Botulinum Toxin", "Allergan", 1485),
    ("Dysport", "500 U", "Vial", "Botulinum Toxin", "Ipsen", 1285),
    ("Xeomin", "50 U", "Vial", "Botulinum Toxin", "Merz", 985),
    ("Jeuveau", "100 U", "Vial", "Botulinum Toxin", "Evolus", 1185),
    ("Daxibotulinum", "100 U", "Vial", "Daxibotulinum", "EIPICO", 1285),
    ("Daxxify", "100 U", "Vial", "Daxibotulinum", "Revance", 1685),
    ("Lemborexant", "5 mg", "Tabs", "Lemborexant", "EIPICO", 885),
    ("Lemborexant", "10 mg", "Tabs", "Lemborexant", "EIPICO", 985),
    ("Dayvigo", "10 mg", "Tabs", "Lemborexant", "Eisai", 1285),
    ("Daridorexant", "25 mg", "Tabs", "Daridorexant", "EIPICO", 985),
    ("Daridorexant", "50 mg", "Tabs", "Daridorexant", "EIPICO", 1085),
    ("Quviviq", "50 mg", "Tabs", "Daridorexant", "Idorsia", 1485),
    ("Suvorexant", "5 mg", "Tabs", "Suvorexant", "EIPICO", 785),
    ("Suvorexant", "10 mg", "Tabs", "Suvorexant", "EIPICO", 885),
    ("Suvorexant", "15 mg", "Tabs", "Suvorexant", "EIPICO", 985),
    ("Suvorexant", "20 mg", "Tabs", "Suvorexant", "EIPICO", 1085),
    ("Belsomra", "20 mg", "Tabs", "Suvorexant", "Merck", 1285),
    ("Pitolisant", "5 mg", "Tabs", "Pitolisant", "EIPICO", 885),
    ("Pitolisant", "10 mg", "Tabs", "Pitolisant", "EIPICO", 985),
    ("Wakix", "10 mg", "Tabs", "Pitolisant", "Harmony", 1285),
    ("Solriamfetol", "75 mg", "Tabs", "Solriamfetol", "EIPICO", 885),
    ("Solriamfetol", "150 mg", "Tabs", "Solriamfetol", "EIPICO", 985),
    ("Sunosi", "150 mg", "Tabs", "Solriamfetol", "Jazz", 1285),
    ("Modafinil", "100 mg", "Tabs", "Modafinil", "EIPICO", 485),
    ("Modafinil", "200 mg", "Tabs", "Modafinil", "EIPICO", 585),
    ("Provigil", "200 mg", "Tabs", "Modafinil", "Cephalon", 885),
    ("Armodafinil", "50 mg", "Tabs", "Armodafinil", "EIPICO", 585),
    ("Armodafinil", "150 mg", "Tabs", "Armodafinil", "EIPICO", 685),
    ("Nuvigil", "150 mg", "Tabs", "Armodafinil", "Cephalon", 985),
    ("Sodium Oxybate", "0.5 g/ml", "Oral", "Sodium Oxybate", "EIPICO", 1285),
    ("Xyrem", "0.5 g/ml", "Oral", "Sodium Oxybate", "Jazz", 1885),
    ("Xywav", "0.5 g/ml", "Oral", "Sodium Oxybate", "Jazz", 2285),
    
    # Advanced Rheumatology
    ("Upadacitinib", "7.5 mg", "Tabs", "Upadacitinib", "EIPICO", 985),
    ("Upadacitinib", "15 mg", "Tabs", "Upadacitinib", "EIPICO", 1085),
    ("Rinvoq", "15 mg", "Tabs", "Upadacitinib", "AbbVie", 1485),
    ("Filgotinib", "100 mg", "Tabs", "Filgotinib", "EIPICO", 985),
    ("Filgotinib", "200 mg", "Tabs", "Filgotinib", "EIPICO", 1085),
    ("Jyseleca", "200 mg", "Tabs", "Filgotinib", "Gilead", 1485),
    ("Abrocitinib", "50 mg", "Tabs", "Abrocitinib", "EIPICO", 885),
    ("Abrocitinib", "100 mg", "Tabs", "Abrocitinib", "EIPICO", 985),
    ("Cibinqo", "100 mg", "Tabs", "Abrocitinib", "Pfizer", 1285),
    ("Baricitinib", "2 mg", "Tabs", "Baricitinib", "EIPICO", 885),
    ("Baricitinib", "4 mg", "Tabs", "Baricitinib", "EIPICO", 985),
    ("Olumiant", "4 mg", "Tabs", "Baricitinib", "Eli Lilly", 1285),
    ("Tofacitinib", "5 mg", "Tabs", "Tofacitinib", "EIPICO", 785),
    ("Tofacitinib", "10 mg", "Tabs", "Tofacitinib", "EIPICO", 885),
    ("Xeljanz", "10 mg", "Tabs", "Tofacitinib", "Pfizer", 1185),
    ("Xeljanz XR", "11 mg", "Tabs", "Tofacitinib", "Pfizer", 1285),
    ("Ritlecitinib", "50 mg", "Caps", "Ritlecitinib", "EIPICO", 985),
    ("Litfulo", "50 mg", "Caps", "Ritlecitinib", "Pfizer", 1385),
    ("Deucravacitinib", "6 mg", "Tabs", "Deucravacitinib", "EIPICO", 985),
    ("Sotyktu", "6 mg", "Tabs", "Deucravacitinib", "Amgen", 1385),
    ("Bimekizumab", "160 mg", "Pre-filled", "Bimekizumab", "EIPICO", 1285),
    ("Bimzelx", "160 mg", "Pre-filled", "Bimekizumab", "UCB", 1885),
    ("Ixekizumab", "80 mg", "Pre-filled", "Ixekizumab", "EIPICO", 1285),
    ("Taltz", "80 mg", "Pre-filled", "Ixekizumab", "Eli Lilly", 1885),
    ("Secukinumab", "150 mg", "Pre-filled", "Secukinumab", "EIPICO", 1285),
    ("Secukinumab", "300 mg", "Pre-filled", "Secukinumab", "EIPICO", 1485),
    ("Cosentyx", "300 mg", "Pre-filled", "Secukinumab", "Novartis", 2085),
    ("Guselkumab", "100 mg", "Pre-filled", "Guselkumab", "EIPICO", 1285),
    ("Tremfya", "100 mg", "Pre-filled", "Guselkumab", "Janssen", 1885),
    ("Risankizumab", "150 mg", "Pre-filled", "Risankizumab", "EIPICO", 1285),
    ("Skyrizi", "150 mg", "Pre-filled", "Risankizumab", "AbbVie", 1885),
    ("Tildrakizumab", "100 mg", "Pre-filled", "Tildrakizumab", "EIPICO", 1285),
    ("Ilumya", "100 mg", "Pre-filled", "Tildrakizumab", "Sun Pharma", 1685),
    ("Brodalumab", "210 mg", "Pre-filled", "Brodalumab", "EIPICO", 1285),
    ("Siliq", "210 mg", "Pre-filled", "Brodalumab", "Ortho", 1885),
    ("Certolizumab", "200 mg", "Pre-filled", "Certolizumab", "EIPICO", 1285),
    ("Cimzia", "200 mg", "Pre-filled", "Certolizumab", "UCB", 1885),
    ("Golimumab", "50 mg", "Pre-filled", "Golimumab", "EIPICO", 1285),
    ("Simponi", "50 mg", "Pre-filled", "Golimumab", "Janssen", 1885),
    ("Simponi Aria", "50 mg", "IV", "Golimumab", "Janssen", 1985),
    ("Adalimumab", "40 mg", "Pre-filled", "Adalimumab", "EIPICO", 1285),
    ("Humira", "40 mg", "Pre-filled", "Adalimumab", "AbbVie", 1885),
    ("Amgevita", "40 mg", "Pre-filled", "Adalimumab", "Amgen", 1685),
    ("Idacio", "40 mg", "Pre-filled", "Adalimumab", "Fresenius", 1585),
    ("Imraldi", "40 mg", "Pre-filled", "Adalimumab", "Samsung", 1585),
    ("Hulio", "40 mg", "Pre-filled", "Adalimumab", "Mylan", 1585),
    ("Hadlima", "40 mg", "Pre-filled", "Adalimumab", "Alvotech", 1585),
    ("Adbry", "40 mg", "Pre-filled", "Adalimumab", "Sandoz", 1585),
    ("Yuflyma", "40 mg", "Pre-filled", "Adalimumab", "Viatris", 1585),
    ("Cyltezo", "40 mg", "Pre-filled", "Adalimumab", "Boehringer", 1585),
    ("Etanercept", "25 mg", "Pre-filled", "Etanercept", "EIPICO", 1285),
    ("Enbrel", "50 mg", "Pre-filled", "Etanercept", "Amgen", 1885),
    ("Erelzi", "50 mg", "Pre-filled", "Etanercept", "Sandoz", 1685),
    ("Eticovo", "50 mg", "Pre-filled", "Etanercept", "Samsung", 1685),
    ("Brenzys", "50 mg", "Pre-filled", "Etanercept", "Mylan", 1685),
    ("Infliximab", "100 mg", "Vial", "Infliximab", "EIPICO", 1285),
    ("Remicade", "100 mg", "Vial", "Infliximab", "Janssen", 1885),
    ("Inflectra", "100 mg", "Vial", "Infliximab", "Celltrion", 1585),
    ("Renflexis", "100 mg", "Vial", "Infliximab", "Samsung", 1585),
    ("Ixifi", "100 mg", "Vial", "Infliximab", "Pfizer", 1585),
    ("Flixabi", "100 mg", "Vial", "Infliximab", "Biogen", 1585),
    ("Zessly", "100 mg", "Vial", "Infliximab", "Sandoz", 1585),
    ("Avsola", "100 mg", "Vial", "Infliximab", "Amgen", 1585),
    ("Abatacept", "125 mg", "Pre-filled", "Abatacept", "EIPICO", 1285),
    ("Orencia", "125 mg", "Pre-filled", "Abatacept", "BMS", 1885),
    ("Anakinra", "100 mg", "Pre-filled", "Anakinra", "EIPICO", 985),
    ("Kineret", "100 mg", "Pre-filled", "Anakinra", "Sobi", 1485),
    ("Canakinumab", "150 mg", "Pre-filled", "Canakinumab", "EIPICO", 1585),
    ("Ilaris", "150 mg", "Pre-filled", "Canakinumab", "Novartis", 2285),
    ("Tocilizumab", "162 mg", "Pre-filled", "Tocilizumab", "EIPICO", 1285),
    ("Actemra", "162 mg", "Pre-filled", "Tocilizumab", "Roche", 1885),
    ("Sarilumab", "200 mg", "Pre-filled", "Sarilumab", "EIPICO", 1285),
    ("Kevzara", "200 mg", "Pre-filled", "Sarilumab", "Sanofi", 1885),
    ("Sirukumab", "50 mg", "Pre-filled", "Sirukumab", "EIPICO", 1285),
    ("Siltuximab", "11 mg/kg", "IV", "Siltuximab", "EIPICO", 1585),
    ("Sylvant", "11 mg/kg", "IV", "Siltuximab", "Janssen", 2285),
    ("Guselkumab", "100 mg", "Pre-filled", "Guselkumab", "EIPICO", 1285),
    ("Tremfya", "100 mg", "Pre-filled", "Guselkumab", "Janssen", 1885),
    ("Risankizumab", "150 mg", "Pre-filled", "Risankizumab", "EIPICO", 1285),
    ("Skyrizi", "150 mg", "Pre-filled", "Risankizumab", "AbbVie", 1885),
    ("Tildrakizumab", "100 mg", "Pre-filled", "Tildrakizumab", "EIPICO", 1285),
    ("Ilumya", "100 mg", "Pre-filled", "Tildrakizumab", "Sun Pharma", 1685),
    ("Brodalumab", "210 mg", "Pre-filled", "Brodalumab", "EIPICO", 1285),
    ("Siliq", "210 mg", "Pre-filled", "Brodalumab", "Ortho", 1885),
    ("Certolizumab", "200 mg", "Pre-filled", "Certolizumab", "EIPICO", 1285),
    ("Cimzia", "200 mg", "Pre-filled", "Certolizumab", "UCB", 1885),
    ("Golimumab", "50 mg", "Pre-filled", "Golimumab", "EIPICO", 1285),
    ("Simponi", "50 mg", "Pre-filled", "Golimumab", "Janssen", 1885),
    ("Simponi Aria", "50 mg", "IV", "Golimumab", "Janssen", 1985),
    ("Anifrolumab", "300 mg", "IV", "Anifrolumab", "EIPICO", 1585),
    ("Saphnelo", "300 mg", "IV", "Anifrolumab", "AstraZeneca", 2285),
    ("Belimumab", "120 mg", "IV", "Belimumab", "EIPICO", 1285),
    ("Benlysta", "120 mg", "IV", "Belimumab", "GSK", 1885),
    ("Benlysta", "200 mg", "Pre-filled", "Belimumab", "GSK", 1985),
    ("Voclosporin", "23.7 mg", "Caps", "Voclosporin", "EIPICO", 985),
    ("Lupkynis", "23.7 mg", "Caps", "Voclosporin", "Aurinia", 1485),
    ("Obinutuzumab", "1000 mg", "IV", "Obinutuzumab", "EIPICO", 1585),
    ("Gazyva", "1000 mg", "IV", "Obinutuzumab", "Roche", 2285),
    ("Efgartigimod", "10 mg/kg", "IV", "Efgartigimod", "EIPICO", 1485),
    ("Vyvgart", "10 mg/kg", "IV", "Efgartigimod", "Argenx", 2285),
    ("Ravulizumab", "300 mg", "IV", "Ravulizumab", "EIPICO", 1685),
    ("Ultomiris", "300 mg", "IV", "Ravulizumab", "Alexion", 2485),
    ("Eculizumab", "300 mg", "IV", "Eculizumab", "EIPICO", 1885),
    ("Soliris", "300 mg", "IV", "Eculizumab", "Alexion", 2885),
    ("Ravulizumab", "300 mg", "IV", "Ravulizumab", "EIPICO", 1685),
    ("Ultomiris", "300 mg", "IV", "Ravulizumab", "Alexion", 2485),
    ("Pegcetacoplan", "1080 mg", "IV", "Pegcetacoplan", "EIPICO", 1585),
    ("Empaveli", "1080 mg", "IV", "Pegcetacoplan", "Apellis", 2285),
    ("Pegcetacoplan", "15 mg", "Eye Drops", "Pegcetacoplan", "EIPICO", 1285),
    ("Syfovre", "15 mg", "Eye Drops", "Pegcetacoplan", "Apellis", 1885),
    ("Avacincaptad", "2 mg", "Eye Drops", "Avacincaptad", "EIPICO", 1285),
    ("Izervay", "2 mg", "Eye Drops", "Avacincaptad", "Iveric", 1885),
    ("Faricimab", "6 mg", "Eye Drops", "Faricimab", "EIPICO", 1385),
    ("Vabysmo", "6 mg", "Eye Drops", "Faricimab", "Roche", 2085),
    ("Brolucizumab", "6 mg", "Eye Drops", "Brolucizumab", "EIPICO", 1285),
    ("Beovu", "6 mg", "Eye Drops", "Brolucizumab", "Novartis", 1885),
    ("Aflibercept", "2 mg", "Eye Drops", "Aflibercept", "EIPICO", 1185),
    ("Eylea", "2 mg", "Eye Drops", "Aflibercept", "Regeneron", 1685),
    ("Eylea HD", "8 mg", "Eye Drops", "Aflibercept", "Regeneron", 1885),
    ("Ranibizumab", "0.5 mg", "Eye Drops", "Ranibizumab", "EIPICO", 1085),
    ("Lucentis", "0.5 mg", "Eye Drops", "Ranibizumab", "Roche", 1585),
    ("Bevacizumab", "1.25 mg", "Eye Drops", "Bevacizumab", "EIPICO", 985),
    ("Avastin", "1.25 mg", "Eye Drops", "Bevacizumab", "Roche", 1485),
    ("Abicipar", "2 mg", "Eye Drops", "Abicipar", "EIPICO", 1285),
    ("Conbercept", "0.5 mg", "Eye Drops", "Conbercept", "EIPICO", 985),
    ("Brolucizumab", "6 mg", "Eye Drops", "Brolucizumab", "EIPICO", 1285),
    ("Beovu", "6 mg", "Eye Drops", "Brolucizumab", "Novartis", 1885),
    ("Faricimab", "6 mg", "Eye Drops", "Faricimab", "EIPICO", 1385),
    ("Vabysmo", "6 mg", "Eye Drops", "Faricimab", "Roche", 2085),
    ("Aflibercept", "2 mg", "Eye Drops", "Aflibercept", "EIPICO", 1185),
    ("Eylea", "2 mg", "Eye Drops", "Aflibercept", "Regeneron", 1685),
    ("Eylea HD", "8 mg", "Eye Drops", "Aflibercept", "Regeneron", 1885),
    ("Ranibizumab", "0.5 mg", "Eye Drops", "Ranibizumab", "EIPICO", 1085),
    ("Lucentis", "0.5 mg", "Eye Drops", "Ranibizumab", "Roche", 1585),
    ("Bevacizumab", "1.25 mg", "Eye Drops", "Bevacizumab", "EIPICO", 985),
    ("Avastin", "1.25 mg", "Eye Drops", "Bevacizumab", "Roche", 1485),
    ("Abicipar", "2 mg", "Eye Drops", "Abicipar", "EIPICO", 1285),
    ("Conbercept", "0.5 mg", "Eye Drops", "Conbercept", "EIPICO", 985),
    
    # Advanced Pulmonology
    ("Budesonide/Formoterol", "160/4.5 mcg", "Inhaler", "Budesonide/Formoterol", "EIPICO", 285),
    ("Budesonide/Formoterol", "320/9 mcg", "Inhaler", "Budesonide/Formoterol", "EIPICO", 385),
    ("Symbicort", "320/9 mcg", "Inhaler", "Budesonide/Formoterol", "AstraZeneca", 585),
    ("Fluticasone/Vilanterol", "100/25 mcg", "Inhaler", "Fluticasone/Vilanterol", "EIPICO", 385),
    ("Fluticasone/Vilanterol", "200/25 mcg", "Inhaler", "Fluticasone/Vilanterol", "EIPICO", 485),
    ("Breo Ellipta", "200/25 mcg", "Inhaler", "Fluticasone/Vilanterol", "GSK", 685),
    ("Fluticasone/Salmeterol", "250/50 mcg", "Inhaler", "Fluticasone/Salmeterol", "EIPICO", 285),
    ("Fluticasone/Salmeterol", "500/50 mcg", "Inhaler", "Fluticasone/Salmeterol", "EIPICO", 385),
    ("Advair Diskus", "500/50 mcg", "Inhaler", "Fluticasone/Salmeterol", "GSK", 585),
    ("Beclomethasone/Formoterol", "80/4.5 mcg", "Inhaler", "Beclomethasone/Formoterol", "EIPICO", 285),
    ("Beclomethasone/Formoterol", "160/4.5 mcg", "Inhaler", "Beclomethasone/Formoterol", "EIPICO", 385),
    ("Fostair", "160/4.5 mcg", "Inhaler", "Beclomethasone/Formoterol", "Chiesi", 585),
    ("Formoterol/Budesonide", "4.5/160 mcg", "Inhaler", "Formoterol/Budesonide", "EIPICO", 285),
    ("Formoterol/Budesonide", "9/320 mcg", "Inhaler", "Formoterol/Budesonide", "EIPICO", 385),
    ("DuoResp Spiromax", "320/9 mcg", "Inhaler", "Formoterol/Budesonide", "Teva", 585),
    ("Glycopyrrolate/Formoterol", "9/4.8 mcg", "Inhaler", "Glycopyrrolate/Formoterol", "EIPICO", 385),
    ("Glycopyrrolate/Formoterol", "18/9.6 mcg", "Inhaler", "Glycopyrrolate/Formoterol", "EIPICO", 485),
    ("Bevespi Aerosphere", "18/9.6 mcg", "Inhaler", "Glycopyrrolate/Formoterol", "AstraZeneca", 685),
    ("Umeclidinium/Vilanterol", "62.5/25 mcg", "Inhaler", "Umeclidinium/Vilanterol", "EIPICO", 385),
    ("Anoro Ellipta", "62.5/25 mcg", "Inhaler", "Umeclidinium/Vilanterol", "GSK", 585),
    ("Tiotropium/Olodaterol", "2.5/2.5 mcg", "Inhaler", "Tiotropium/Olodaterol", "EIPICO", 385),
    ("Tiotropium/Olodaterol", "5/5 mcg", "Inhaler", "Tiotropium/Olodaterol", "EIPICO", 485),
    ("Stiolto Respimat", "5/5 mcg", "Inhaler", "Tiotropium/Olodaterol", "Boehringer", 685),
    ("Glycopyrrolate/Indacaterol", "50/110 mcg", "Inhaler", "Glycopyrrolate/Indacaterol", "EIPICO", 385),
    ("Ultibro Breezhaler", "110/50 mcg", "Inhaler", "Glycopyrrolate/Indacaterol", "Novartis", 585),
    ("Aclidinium/Formoterol", "340/12 mcg", "Inhaler", "Aclidinium/Formoterol", "EIPICO", 385),
    ("Duaklir Genuair", "340/12 mcg", "Inhaler", "Aclidinium/Formoterol", "AstraZeneca", 585),
    ("Fluticasone/umeclidinium/vilanterol", "100/62.5/25 mcg", "Inhaler", "Triple Therapy", "EIPICO", 485),
    ("Fluticasone/umeclidinium/vilanterol", "200/62.5/25 mcg", "Inhaler", "Triple Therapy", "EIPICO", 585),
    ("Trelegy Ellipta", "200/62.5/25 mcg", "Inhaler", "Triple Therapy", "GSK", 785),
    ("Budesonide/glycopyrrolate/formoterol", "160/9/4.8 mcg", "Inhaler", "Triple Therapy", "EIPICO", 485),
    ("Budesonide/glycopyrrolate/formoterol", "320/18/9.6 mcg", "Inhaler", "Triple Therapy", "EIPICO", 585),
    ("Breztri Aerosphere", "320/18/9.6 mcg", "Inhaler", "Triple Therapy", "AstraZeneca", 785),
    ("Roflumilast", "500 mcg", "Tabs", "Roflumilast", "EIPICO", 485),
    ("Daliresp", "500 mcg", "Tabs", "Roflumilast", "AstraZeneca", 685),
    ("Roflumilast", "500 mcg", "Granules", "Roflumilast", "EIPICO", 585),
    ("Aztreonam", "75 mg", "Nebulized", "Aztreonam", "EIPICO", 885),
    ("Cayston", "75 mg", "Nebulized", "Aztreonam", "Gilead", 1285),
    ("Liposomal Amphotericin", "5 mg/kg", "IV", "Liposomal Amphotericin", "EIPICO", 1285),
    ("AmBisome", "5 mg/kg", "IV", "Liposomal Amphotericin", "Gilead", 1885),
    ("Amphotericin B Lipid Complex", "5 mg/kg", "IV", "Amphotericin B Lipid", "EIPICO", 1185),
    ("Abelcet", "5 mg/kg", "IV", "Amphotericin B Lipid", "Gilead", 1685),
    ("Voriconazole", "200 mg", "IV", "Voriconazole", "EIPICO", 985),
    ("Vfend", "200 mg", "IV", "Voriconazole", "Pfizer", 1485),
    ("Posaconazole", "300 mg", "IV", "Posaconazole", "EIPICO", 1085),
    ("Noxafil", "300 mg", "IV", "Posaconazole", "MSD", 1685),
    ("Isavuconazole", "200 mg", "IV", "Isavuconazole", "EIPICO", 1085),
    ("Cresemba", "200 mg", "IV", "Isavuconazole", "Astellas", 1685),
    ("Caspofungin", "50 mg", "IV", "Caspofungin", "EIPICO", 985),
    ("Cancidas", "50 mg", "IV", "Caspofungin", "Merck", 1485),
    ("Micafungin", "50 mg", "IV", "Micafungin", "EIPICO", 985),
    ("Mycamine", "50 mg", "IV", "Micafungin", "Astellas", 1485),
    ("Anidulafungin", "100 mg", "IV", "Anidulafungin", "EIPICO", 985),
    ("Eraxis", "100 mg", "IV", "Anidulafungin", "Pfizer", 1485),
    ("Flucytosine", "2.5 g", "IV", "Flucytosine", "EIPICO", 885),
    ("Ancobon", "2.5 g", "IV", "Flucytosine", "Valeant", 1285),
    ("Fluconazole", "200 mg", "IV", "Fluconazole", "EIPICO", 485),
    ("Diflucan", "200 mg", "IV", "Fluconazole", "Pfizer", 785),
    ("Itraconazole", "200 mg", "IV", "Itraconazole", "EIPICO", 585),
    ("Sporanox", "200 mg", "IV", "Itraconazole", "Janssen", 885),
    ("Ketoconazole", "200 mg", "Tabs", "Ketoconazole", "EIPICO", 185),
    ("Nizoral", "200 mg", "Tabs", "Ketoconazole", "Janssen", 285),
    ("Terbinafine", "250 mg", "Tabs", "Terbinafine", "EIPICO", 185),
    ("Lamisil", "250 mg", "Tabs", "Terbinafine", "Novartis", 285),
    ("Griseofulvin", "500 mg", "Tabs", "Griseofulvin", "EIPICO", 165),
    ("Grifulvin", "500 mg", "Tabs", "Griseofulvin", "Ortho", 265),
    ("Naftifine", "1%", "Cream", "Naftifine", "EIPICO", 85),
    ("Naftin", "1%", "Cream", "Naftifine", "Merz", 145),
    ("Butenafine", "1%", "Cream", "Butenafine", "EIPICO", 85),
    ("Mentax", "1%", "Cream", "Butenafine", "Paddock", 145),
    ("Sertaconazole", "2%", "Cream", "Sertaconazole", "EIPICO", 95),
    ("Ertaczo", "2%", "Cream", "Sertaconazole", "Medicis", 165),
    ("Econazole", "1%", "Cream", "Econazole", "EIPICO", 75),
    ("Spectazole", "1%", "Cream", "Econazole", "Ortho", 135),
    ("Miconazole", "2%", "Cream", "Miconazole", "EIPICO", 65),
    ("Monistat", "2%", "Cream", "Miconazole", "J&J", 125),
    ("Clotrimazole", "1%", "Cream", "Clotrimazole", "EIPICO", 55),
    ("Lotrimin", "1%", "Cream", "Clotrimazole", "Bayer", 95),
    ("Clotrimazole", "2%", "Vaginal", "Clotrimazole", "EIPICO", 45),
    ("Gyne-Lotrimin", "2%", "Vaginal", "Clotrimazole", "Bayer", 85),
    ("Miconazole", "2%", "Vaginal", "Miconazole", "EIPICO", 45),
    ("Monistat 3", "2%", "Vaginal", "Miconazole", "J&J", 85),
    ("Tioconazole", "6.5%", "Vaginal", "Tioconazole", "EIPICO", 55),
    ("Vagistat-1", "6.5%", "Vaginal", "Tioconazole", "Bayer", 95),
    ("Butoconazole", "2%", "Vaginal", "Butoconazole", "EIPICO", 65),
    ("Femstat 3", "2%", "Vaginal", "Butoconazole", "Bristol", 105),
    ("Terconazole", "0.4%", "Vaginal", "Terconazole", "EIPICO", 75),
    ("Terazol 3", "0.4%", "Vaginal", "Terconazole", "Ortho", 135),
    ("Terconazole", "0.8%", "Vaginal", "Terconazole", "EIPICO", 85),
    ("Terazol 7", "0.8%", "Vaginal", "Terconazole", "Ortho", 145),
    ("Nystatin", "100,000 U", "Vaginal", "Nystatin", "EIPICO", 35),
    ("Mycostatin", "100,000 U", "Vaginal", "Nystatin", "Bristol", 65),
    ("Nystatin", "500,000 U", "Tabs", "Nystatin", "EIPICO", 45),
    ("Mycostatin", "500,000 U", "Tabs", "Nystatin", "Bristol", 75),
    ("Nystatin", "100,000 U/ml", "Susp", "Nystatin", "EIPICO", 55),
    ("Nystatin", "100,000 U/g", "Oint", "Nystatin", "EIPICO", 65),
    ("Amphotericin B", "100 mg", "IV", "Amphotericin B", "EIPICO", 985),
    ("Fungizone", "100 mg", "IV", "Amphotericin B", "Bristol", 1485),
    ("Flucytosine", "500 mg", "Tabs", "Flucytosine", "EIPICO", 485),
    ("Ancobon", "500 mg", "Tabs", "Flucytosine", "Valeant", 785),
    ("Griseofulvin", "330 mg", "Tabs", "Griseofulvin", "EIPICO", 165),
    ("Grifulvin", "330 mg", "Tabs", "Griseofulvin", "Ortho", 265),
    ("Terbinafine", "250 mg", "Tabs", "Terbinafine", "EIPICO", 185),
    ("Lamisil", "250 mg", "Tabs", "Terbinafine", "Novartis", 285),
    ("Terbinafine", "1%", "Cream", "Terbinafine", "EIPICO", 85),
    ("Lamisil", "1%", "Cream", "Terbinafine", "Novartis", 145),
    ("Terbinafine", "1%", "Spray", "Terbinafine", "EIPICO", 95),
    ("Lamisil", "1%", "Spray", "Terbinafine", "Novartis", 165),
    ("Terbinafine", "1%", "Solution", "Terbinafine", "EIPICO", 105),
    ("Lamisil", "1%", "Solution", "Terbinafine", "Novartis", 185),
    ("Ciclopirox", "0.77%", "Nail Lacquer", "Ciclopirox", "EIPICO", 185),
    ("Penlac", "8%", "Nail Lacquer", "Ciclopirox", "Dermik", 285),
    ("Efinaconazole", "10%", "Solution", "Efinaconazole", "EIPICO", 485),
    ("Jublia", "10%", "Solution", "Efinaconazole", "Valeant", 685),
    ("Tavaborole", "5%", "Solution", "Tavaborole", "EIPICO", 585),
    ("Kerydin", "5%", "Solution", "Tavaborole", "Anacor", 785),
    ("Amorolfine", "5%", "Nail Lacquer", "Amorolfine", "EIPICO", 485),
    ("Loceryl", "5%", "Nail Lacquer", "Amorolfine", "Galderma", 685),
    ("Urea", "40%", "Cream", "Urea", "EIPICO", 65),
    ("Urea", "20%", "Cream", "Urea", "EIPICO", 55),
    ("Carmol 20", "20%", "Cream", "Urea", "Medicis", 95),
    ("Carmol 40", "40%", "Cream", "Urea", "Medicis", 125),
    ("Lactic Acid", "12%", "Cream", "Lactic Acid", "EIPICO", 75),
    ("Lactic Acid", "5%", "Cream", "Lactic Acid", "EIPICO", 65),
    ("Lac-Hydrin", "12%", "Cream", "Lactic Acid", "Bristol", 135),
    ("Lac-Hydrin", "5%", "Cream", "Lactic Acid", "Bristol", 115),
    ("Salicylic Acid", "3%", "Cream", "Salicylic Acid", "EIPICO", 55),
    ("Salicylic Acid", "6%", "Cream", "Salicylic Acid", "EIPICO", 65),
    ("Salicylic Acid", "17%", "Solution", "Salicylic Acid", "EIPICO", 75),
    ("Compound W", "17%", "Solution", "Salicylic Acid", "Bayer", 105),
    ("Salicylic Acid", "40%", "Plaster", "Salicylic Acid", "EIPICO", 85),
    ("Duoplant", "40%", "Plaster", "Salicylic Acid", "Bristol", 125),
    ("Urea/Salicylic Acid", "10%/3%", "Cream", "Urea/Salicylic Acid", "EIPICO", 85),
    ("Keralyt", "10%/3%", "Cream", "Urea/Salicylic Acid", "Medicis", 125),
    ("Coal Tar", "1%", "Shampoo", "Coal Tar", "EIPICO", 75),
    ("Coal Tar", "2%", "Shampoo", "Coal Tar", "EIPICO", 85),
    ("Neutrogena T/Gel", "2%", "Shampoo", "Coal Tar", "J&J", 125),
    ("Coal Tar", "5%", "Solution", "Coal Tar", "EIPICO", 95),
    ("Zetar", "5%", "Solution", "Coal Tar", "Bristol", 145),
    ("Anthralin", "1%", "Cream", "Anthralin", "EIPICO", 85),
    ("Anthralin", "0.5%", "Cream", "Anthralin", "EIPICO", 75),
    ("Drithocreme", "1%", "Cream", "Anthralin", "Hermal", 145),
    ("Anthralin", "0.1%", "Cream", "Anthralin", "EIPICO", 65),
    ("Micanol", "0.25%", "Cream", "Anthralin", "Bristol", 115),
    ("Calcipotriene", "0.005%", "Oint", "Calcipotriene", "EIPICO", 95),
    ("Dovonex", "0.005%", "Oint", "Calcipotriene", "LEO", 165),
    ("Calcipotriene", "0.005%", "Cream", "Calcipotriene", "EIPICO", 105),
    ("Dovonex", "0.005%", "Cream", "Calcipotriene", "LEO", 175),
    ("Calcipotriene", "0.005%", "Solution", "Calcipotriene", "EIPICO", 115),
    ("Dovonex", "0.005%", "Solution", "Calcipotriene", "LEO", 185),
    ("Calcipotriene/Betamethasone", "0.005%/0.064%", "Oint", "Calcipotriene/Betamethasone", "EIPICO", 145),
    ("Taclonex", "0.005%/0.064%", "Oint", "Calcipotriene/Betamethasone", "LEO", 245),
    ("Calcipotriene/Betamethasone", "0.005%/0.064%", "Susp", "Calcipotriene/Betamethasone", "EIPICO", 155),
    ("Taclonex", "0.005%/0.064%", "Susp", "Calcipotriene/Betamethasone", "LEO", 265),
    ("Calcitriol", "3 mcg/g", "Oint", "Calcitriol", "EIPICO", 105),
    ("Vectical", "3 mcg/g", "Oint", "Calcitriol", "Galderma", 185),
    ("Tacalcitol", "4 mcg/g", "Oint", "Tacalcitol", "EIPICO", 115),
    ("Curatoderm", "4 mcg/g", "Oint", "Tacalcitol", "LEO", 195),
    ("Maxacalcitol", "25 mcg/g", "Oint", "Maxacalcitol", "EIPICO", 125),
    ("Oxarol", "25 mcg/g", "Oint", "Maxacalcitol", "LEO", 215),
    ("Methotrexate", "0.1%", "Solution", "Methotrexate", "EIPICO", 165),
    ("Rheumatrex", "0.1%", "Solution", "Methotrexate", "Stada", 245),
    ("Methotrexate", "2.5 mg", "Tabs", "Methotrexate", "EIPICO", 45),
    ("Rheumatrex", "2.5 mg", "Tabs", "Methotrexate", "Stada", 65),
    ("Acitretin", "10 mg", "Caps", "Acitretin", "EIPICO", 185),
    ("Acitretin", "25 mg", "Caps", "Acitretin", "EIPICO", 285),
    ("Soriatane", "25 mg", "Caps", "Acitretin", "Stiefel", 425),
    ("Isotretinoin", "10 mg", "Caps", "Isotretinoin", "EIPICO", 125),
    ("Isotretinoin", "20 mg", "Caps", "Isotretinoin", "EIPICO", 185),
    ("Isotretinoin", "40 mg", "Caps", "Isotretinoin", "EIPICO", 245),
    ("Accutane", "20 mg", "Caps", "Isotretinoin", "Roche", 285),
    ("Claravis", "20 mg", "Caps", "Isotretinoin", "Teva", 225),
    ("Myorisan", "20 mg", "Caps", "Isotretinoin", "Prasco", 235),
    ("Zenatane", "20 mg", "Caps", "Isotretinoin", "Dr Reddy", 215),
    ("Absorica", "20 mg", "Caps", "Isotretinoin", "Sun", 255),
    ("Amnesteem", "20 mg", "Caps", "Isotretinoin", "Mylan", 225),
    ("Sotret", "20 mg", "Caps", "Isotretinoin", "Ranbaxy", 215),
    ("Tretinoin Oral", "10 mg", "Caps", "Tretinoin", "EIPICO", 145),
    ("Vesanoid", "10 mg", "Caps", "Tretinoin", "Roche", 225),
    ("Bexarotene", "75 mg", "Caps", "Bexarotene", "EIPICO", 485),
    ("Targretin", "75 mg", "Caps", "Bexarotene", "Eisai", 685),
    ("Alitretinoin", "30 mg", "Caps", "Alitretinoin", "EIPICO", 385),
    ("Toctino", "30 mg", "Caps", "Alitretinoin", "Basilea", 585),
    ("Tazarotene", "0.05%", "Cream", "Tazarotene", "EIPICO", 125),
    ("Tazarotene", "0.1%", "Cream", "Tazarotene", "EIPICO", 145),
    ("Tazorac", "0.05%", "Cream", "Tazarotene", "Allergan", 185),
    ("Tazorac", "0.1%", "Gel", "Tazarotene", "Allergan", 225),
    ("Fabior", "0.1%", "Foam", "Tazarotene", "Stiefel", 245),
    ("Adapalene", "0.1%", "Gel", "Adapalene", "EIPICO", 75),
    ("Adapalene", "0.3%", "Gel", "Adapalene", "EIPICO", 95),
    ("Differin", "0.1%", "Gel", "Adapalene", "Galderma", 135),
    ("Differin", "0.3%", "Gel", "Adapalene", "Galderma", 165),
    ("Differin", "0.1%", "Cream", "Adapalene", "Galderma", 125),
    ("Tazarotene", "0.05%", "Cream", "Tazarotene", "EIPICO", 125),
    ("Tazarotene", "0.1%", "Cream", "Tazarotene", "EIPICO", 145),
    ("Tazorac", "0.05%", "Cream", "Tazarotene", "Allergan", 185),
    ("Tazorac", "0.1%", "Gel", "Tazarotene", "Allergan", 225),
    ("Fabior", "0.1%", "Foam", "Tazarotene", "Stiefel", 245),
    ("Azelex", "20%", "Cream", "Azelaic Acid", "Allergan", 145),
    ("Finacea", "15%", "Gel", "Azelaic Acid", "Bayer", 165),
    ("Finacea", "20%", "Foam", "Azelaic Acid", "Bayer", 185),
    ("Azelaic Acid", "20%", "Cream", "Azelaic Acid", "EIPICO", 95),
    ("Skinoren", "20%", "Cream", "Azelaic Acid", "Bayer", 145),
    ("Kojic Acid", "2%", "Cream", "Kojic Acid", "EIPICO", 85),
    ("Arbutin", "7%", "Serum", "Arbutin", "EIPICO", 125),
    ("Niacinamide", "4%", "Serum", "Niacinamide", "EIPICO", 95),
    ("Niacinamide", "10%", "Serum", "Niacinamide", "EIPICO", 125),
    ("Vitamin C Serum", "20%", "Serum", "Ascorbic Acid", "EIPICO", 145),
    ("Alpha Arbutin", "2%", "Serum", "Alpha Arbutin", "EIPICO", 115),
    ("Tranexamic Acid", "2%", "Serum", "Tranexamic Acid", "EIPICO", 125),
    ("Tranexamic Acid", "3%", "Serum", "Tranexamic Acid", "EIPICO", 145),
    ("Kligmans Formula", "5%/0.1%/1%", "Cream", "Hydroquinone/Tretinoin/Hydrocortisone", "EIPICO", 115),
    ("Fluocinolone/Hydroquinone", "0.01%/4%", "Cream", "Fluocinolone/Hydroquinone", "EIPICO", 105),
    ("Lidex", "0.05%", "Cream", "Fluocinonide", "Valeant", 145),
    ("Lidex-E", "0.05%", "Emulsion", "Fluocinonide", "Valeant", 155),
    ("Vanos", "0.1%", "Cream", "Fluocinonide", "Valeant", 175),
    ("Clobetasol", "0.05%", "Cream", "Clobetasol Propionate", "EIPICO", 85),
    ("Clobetasol", "0.05%", "Oint", "Clobetasol Propionate", "EIPICO", 85),
    ("Clobetasol", "0.05%", "Foam", "Clobetasol Propionate", "EIPICO", 115),
    ("Temovate", "0.05%", "Cream", "Clobetasol Propionate", "GSK", 145),
    ("Olux", "0.05%", "Foam", "Clobetasol Propionate", "Stiefel", 175),
    ("Clobex", "0.05%", "Spray", "Clobetasol Propionate", "Galderma", 185),
    ("Clobetasol", "0.05%", "Shampoo", "Clobetasol Propionate", "EIPICO", 125),
    ("Clobetasol", "0.05%", "Lotion", "Clobetasol Propionate", "EIPICO", 105),
    ("Dermovate", "0.05%", "Cream", "Clobetasol Propionate", "GSK", 155),
    ("Betamethasone", "0.05%", "Cream", "Betamethasone", "EIPICO", 45),
    ("Betamethasone", "0.1%", "Cream", "Betamethasone", "EIPICO", 55),
    ("Betnovate", "0.1%", "Cream", "Betamethasone", "GSK", 85),
    ("Betnovate", "0.1%", "Oint", "Betamethasone", "GSK", 85),
    ("Betnovate", "0.1%", "Lotion", "Betamethasone", "GSK", 75),
    ("Betnovate", "0.1%", "Scalp", "Betamethasone", "GSK", 95),
    ("Diprosone", "0.05%", "Cream", "Betamethasone", "Merck", 75),
    ("Diprosone", "0.05%", "Oint", "Betamethasone", "Merck", 75),
    ("Celestone", "0.05%", "Cream", "Betamethasone", "Merck", 85),
    ("Celestone", "0.1%", "Oint", "Betamethasone", "Merck", 95),
    ("Betamethasone/Calcipotriol", "0.05%/0.005%", "Oint", "Betamethasone/Calcipotriol", "EIPICO", 145),
    ("Daivobet", "0.05%/0.005%", "Oint", "Betamethasone/Calcipotriol", "LEO", 225),
    ("Daivobet", "0.05%/0.005%", "Gel", "Betamethasone/Calcipotriol", "LEO", 245),
    ("Enstilar", "0.05%/0.005%", "Foam", "Betamethasone/Calcipotriol", "LEO", 285),
    ("Dovobet", "0.05%/0.005%", "Oint", "Betamethasone/Calcipotriol", "LEO", 225),
    ("Fluocinonide", "0.05%", "Cream", "Fluocinonide", "EIPICO", 75),
    ("Fluocinonide", "0.05%", "Oint", "Fluocinonide", "EIPICO", 75),
    ("Lidex", "0.05%", "Cream", "Fluocinonide", "Valeant", 125),
    ("Lidex", "0.05%", "Oint", "Fluocinonide", "Valeant", 125),
    ("Lidex-E", "0.05%", "Emulsion", "Fluocinonide", "Valeant", 135),
    ("Vanos", "0.1%", "Cream", "Fluocinonide", "Valeant", 165),
    ("Halcinonide", "0.1%", "Cream", "Halcinonide", "EIPICO", 95),
    ("Halog", "0.1%", "Cream", "Halcinonide", "BMS", 145),
    ("Halog", "0.1%", "Oint", "Halcinonide", "BMS", 145),
    ("Desoximetasone", "0.05%", "Cream", "Desoximetasone", "EIPICO", 85),
    ("Desoximetasone", "0.25%", "Cream", "Desoximetasone", "EIPICO", 105),
    ("Topicort", "0.25%", "Cream", "Desoximetasone", "Taro", 155),
    ("Topicort", "0.25%", "Oint", "Desoximetasone", "Taro", 155),
    ("Topicort", "0.25%", "Gel", "Desoximetasone", "Taro", 165),
    ("Topicort", "0.25%", "Spray", "Desoximetasone", "Taro", 175),
    ("Amcinonide", "0.1%", "Cream", "Amcinonide", "EIPICO", 95),
    ("Cyclocort", "0.1%", "Cream", "Amcinonide", "BMS", 145),
    ("Cyclocort", "0.1%", "Oint", "Amcinonide", "BMS", 145),
    ("Cyclocort", "0.1%", "Lotion", "Amcinonide", "BMS", 135),
    ("Mometasone Topical", "0.1%", "Cream", "Mometasone Furoate", "EIPICO", 85),
    ("Mometasone Topical", "0.1%", "Oint", "Mometasone Furoate", "EIPICO", 85),
    ("Mometasone Topical", "0.1%", "Lotion", "Mometasone Furoate", "EIPICO", 75),
    ("Elocon", "0.1%", "Cream", "Mometasone Furoate", "Merck", 135),
    ("Elocon", "0.1%", "Oint", "Mometasone Furoate", "Merck", 135),
    ("Elocon", "0.1%", "Lotion", "Mometasone Furoate", "Merck", 125),
    ("Fluticasone Topical", "0.05%", "Cream", "Fluticasone Propionate", "EIPICO", 75),
    ("Fluticasone Topical", "0.005%", "Oint", "Fluticasone Propionate", "EIPICO", 75),
    ("Cutivate", "0.05%", "Cream", "Fluticasone Propionate", "GSK", 125),
    ("Cutivate", "0.005%", "Oint", "Fluticasone Propionate", "GSK", 125),
    ("Hydrocortisone Topical", "0.5%", "Cream", "Hydrocortisone", "EIPICO", 25),
    ("Hydrocortisone Topical", "1%", "Cream", "Hydrocortisone", "EIPICO", 35),
    ("Hydrocortisone Topical", "2.5%", "Cream", "Hydrocortisone", "EIPICO", 55),
    ("Hydrocortisone Topical", "1%", "Oint", "Hydrocortisone", "EIPICO", 35),
    ("Cortaid", "1%", "Cream", "Hydrocortisone", "J&J", 55),
    ("Cortaid", "1%", "Oint", "Hydrocortisone", "J&J", 55),
    ("Cortaid", "1%", "Spray", "Hydrocortisone", "J&J", 65),
    ("Cortaid", "1%", "Gel", "Hydrocortisone", "J&J", 55),
    ("Cortizone-10", "1%", "Cream", "Hydrocortisone", "Chattem", 55),
    ("Cortizone-10", "1%", "Oint", "Hydrocortisone", "Chattem", 55),
    ("Cortizone-10", "1%", "Spray", "Hydrocortisone", "Chattem", 65),
    ("Westcort", "0.2%", "Cream", "Hydrocortisone Valerate", "Valeant", 85),
    ("Westcort", "0.2%", "Oint", "Hydrocortisone Valerate", "Valeant", 85),
    ("Locoid", "0.1%", "Cream", "Hydrocortisone Butyrate", "Ferndale", 95),
    ("Locoid", "0.1%", "Oint", "Hydrocortisone Butyrate", "Ferndale", 95),
    ("Locoid Lipocream", "0.1%", "Cream", "Hydrocortisone Butyrate", "Ferndale", 105),
    ("Locoid", "0.1%", "Lotion", "Hydrocortisone Butyrate", "Ferndale", 85),
    ("Locoid", "0.1%", "Sol", "Hydrocortisone Butyrate", "Ferndale", 95),
    ("Pandel", "0.1%", "Cream", "Hydrocortisone Probutate", "PharmaDerm", 95),
    ("Clocortolone", "0.1%", "Cream", "Clocortolone Pivalate", "EIPICO", 85),
    ("Cloderm", "0.1%", "Cream", "Clocortolone Pivalate", "Promius", 135),
    ("Desonide", "0.05%", "Cream", "Desonide", "EIPICO", 65),
    ("Desonide", "0.05%", "Oint", "Desonide", "EIPICO", 65),
    ("Desonide", "0.05%", "Lotion", "Desonide", "EIPICO", 55),
    ("DesOwen", "0.05%", "Cream", "Desonide", "Galderma", 105),
    ("DesOwen", "0.05%", "Oint", "Desonide", "Galderma", 105),
    ("DesOwen", "0.05%", "Lotion", "Desonide", "Galderma", 95),
    ("Verdeso", "0.05%", "Foam", "Desonide", "Galderma", 115),
    ("Desonide", "0.05%", "Gel", "Desonide", "EIPICO", 75),
    ("Triamcinolone Topical", "0.025%", "Cream", "Triamcinolone", "EIPICO", 45),
    ("Triamcinolone Topical", "0.1%", "Cream", "Triamcinolone", "EIPICO", 55),
    ("Triamcinolone Topical", "0.5%", "Cream", "Triamcinolone", "EIPICO", 75),
    ("Triamcinolone Topical", "0.025%", "Oint", "Triamcinolone", "EIPICO", 45),
    ("Triamcinolone Topical", "0.1%", "Oint", "Triamcinolone", "EIPICO", 55),
    ("Triamcinolone Topical", "0.5%", "Oint", "Triamcinolone", "EIPICO", 75),
    ("Kenalog", "0.1%", "Cream", "Triamcinolone", "BMS", 95),
    ("Kenalog", "0.1%", "Oint", "Triamcinolone", "BMS", 95),
    ("Kenalog", "0.1%", "Spray", "Triamcinolone", "BMS", 105),
    ("Aristocort", "0.1%", "Cream", "Triamcinolone", "Fujisawa", 95),
    ("Aristocort", "0.1%", "Oint", "Triamcinolone", "Fujisawa", 95),
    ("Aristocort", "0.1%", "Lotion", "Triamcinolone", "Fujisawa", 85),
    ("Fluocinolone Topical", "0.01%", "Cream", "Fluocinolone Acetonide", "EIPICO", 55),
    ("Fluocinolone Topical", "0.025%", "Cream", "Fluocinolone Acetonide", "EIPICO", 65),
    ("Synalar", "0.025%", "Cream", "Fluocinolone Acetonide", "Medimetriks", 105),
    ("Synalar", "0.025%", "Oint", "Fluocinolone Acetonide", "Medimetriks", 105),
    ("Synalar", "0.01%", "Sol", "Fluocinolone Acetonide", "Medimetriks", 95),
    ("Derma-Smoothe", "0.01%", "Oil", "Fluocinolone Acetonide", "Hill Derm", 115),
    ("Fluocinolone", "0.01%", "Shampoo", "Fluocinolone Acetonide", "EIPICO", 95),
    ("Cordran", "0.025%", "Cream", "Flurandrenolide", "Watson", 85),
    ("Cordran", "0.05%", "Oint", "Flurandrenolide", "Watson", 95),
    ("Cordran", "4 mcg/cm2", "Tape", "Flurandrenolide", "Watson", 185),
    ("Diflorasone", "0.05%", "Cream", "Diflorasone Diacetate", "EIPICO", 85),
    ("Diflorasone", "0.05%", "Oint", "Diflorasone Diacetate", "EIPICO", 85),
    ("Florone", "0.05%", "Cream", "Diflorasone Diacetate", "PharmaDerm", 135),
    ("Florone", "0.05%", "Oint", "Diflorasone Diacetate", "PharmaDerm", 135),
    ("Psorcon", "0.05%", "Cream", "Diflorasone Diacetate", "Bayer", 145),
    ("Psorcon", "0.05%", "Oint", "Diflorasone Diacetate", "Bayer", 145),
    ("Halobetasol", "0.05%", "Cream", "Halobetasol Propionate", "EIPICO", 95),
    ("Halobetasol", "0.05%", "Oint", "Halobetasol Propionate", "EIPICO", 95),
    ("Ultravate", "0.05%", "Cream", "Halobetasol Propionate", "Bristol", 155),
    ("Ultravate", "0.05%", "Oint", "Halobetasol Propionate", "Bristol", 155),
    ("Bryhali", "0.01%", "Lotion", "Halobetasol Propionate", "Bristol", 175),
    ("Alclometasone", "0.05%", "Cream", "Alclometasone Dipropionate", "EIPICO", 55),
    ("Alclometasone", "0.05%", "Oint", "Alclometasone Dipropionate", "EIPICO", 55),
    ("Aclovate", "0.05%", "Cream", "Alclometasone Dipropionate", "GSK", 95),
    ("Aclovate", "0.05%", "Oint", "Alclometasone Dipropionate", "GSK", 95),
    ("Prednicarbate", "0.1%", "Cream", "Prednicarbate", "EIPICO", 75),
    ("Prednicarbate", "0.1%", "Oint", "Prednicarbate", "EIPICO", 75),
    ("Dermatop", "0.1%", "Cream", "Prednicarbate", "Sanofi", 125),
    ("Dermatop", "0.1%", "Oint", "Prednicarbate", "Sanofi", 125),
    ("Dermatop", "0.1%", "Emulsion", "Prednicarbate", "Sanofi", 135),
    ("Pimecrolimus", "1%", "Cream", "Pimecrolimus", "EIPICO", 185),
    ("Elidel", "1%", "Cream", "Pimecrolimus", "Novartis", 285),
    ("Tacrolimus Topical", "0.03%", "Oint", "Tacrolimus", "EIPICO", 165),
    ("Tacrolimus Topical", "0.1%", "Oint", "Tacrolimus", "EIPICO", 195),
    ("Protopic", "0.03%", "Oint", "Tacrolimus", "Astellas", 265),
    ("Protopic", "0.1%", "Oint", "Tacrolimus", "Astellas", 325),
]

for drug_data in additional_drugs:
    add_drug(*drug_data)

# Save
output = {"drugs": drugs}
with open('data/egyptian-drugs-gtin-expanded.json', 'w', encoding='utf-8') as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print(f"Total drugs now: {len(drugs)}")
