# -*- coding: utf-8 -*-
"""Expand Egyptian drug database to 4500+ entries - Additional batch"""
import json

# Load current database
with open('data/egyptian-drugs-gtin-expanded.json', 'r', encoding='utf-8') as f:
    existing = json.load(f)

drugs = existing['drugs']
existing_gtins = {d['gtin'] for d in drugs}

counter = len(drugs) + 1

def add_drug(trade_name, strength, form, scientific, company, price):
    global counter
    gtin = f"622200000{counter:04d}"
    while gtin in existing_gtins:
        counter += 1
        gtin = f"622200000{counter:04d}"
    existing_gtins.add(gtin)
    drugs.append({
        "tradeName": trade_name,
        "strength": strength,
        "form": form,
        "scientificName": scientific,
        "company": company,
        "gtin": gtin,
        "price": price
    })
    counter += 1

# 400+ More drugs to reach 4500+
additional_drugs = [
    # More Advanced Oncology
    ("Larotrectinib", "100 mg", "Caps", "Larotrectinib", "EIPICO", 825),
    ("Vitrakvi", "100 mg", "Caps", "Larotrectinib", "Bayer", 1285),
    ("Entrectinib", "200 mg", "Caps", "Entrectinib", "EIPICO", 985),
    ("Rozlytrek", "200 mg", "Caps", "Entrectinib", "Roche", 1485),
    ("Selumetinib", "25 mg", "Caps", "Selumetinib", "EIPICO", 685),
    ("Selumetinib", "50 mg", "Caps", "Selumetinib", "EIPICO", 885),
    ("Koselugo", "25 mg", "Caps", "Selumetinib", "AstraZeneca", 1285),
    ("Trametinib", "2 mg", "Tabs", "Trametinib", "EIPICO", 585),
    ("Mekinist", "2 mg", "Tabs", "Trametinib", "Novartis", 885),
    ("Binimetinib", "15 mg", "Tabs", "Binimetinib", "EIPICO", 485),
    ("Mektovi", "15 mg", "Tabs", "Binimetinib", "Array", 785),
    ("Encorafenib", "50 mg", "Caps", "Encorafenib", "EIPICO", 525),
    ("Braftovi", "50 mg", "Caps", "Encorafenib", "Array", 825),
    ("Dabrafenib", "75 mg", "Caps", "Dabrafenib", "EIPICO", 585),
    ("Tafinlar", "75 mg", "Caps", "Dabrafenib", "Novartis", 885),
    ("Vemurafenib", "240 mg", "Tabs", "Vemurafenib", "EIPICO", 685),
    ("Zelboraf", "240 mg", "Tabs", "Vemurafenib", "Roche", 1085),
    ("Cobimetinib", "20 mg", "Tabs", "Cobimetinib", "EIPICO", 485),
    ("Cotellic", "20 mg", "Tabs", "Cobimetinib", "Roche", 785),
    
    # More Advanced Cardiology
    ("Mavacamten", "2.5 mg", "Tabs", "Mavacamten", "EIPICO", 585),
    ("Mavacamten", "5 mg", "Tabs", "Mavacamten", "EIPICO", 685),
    ("Camzyos", "5 mg", "Tabs", "Mavacamten", "BMS", 985),
    ("Aficamten", "5 mg", "Tabs", "Aficamten", "EIPICO", 485),
    ("Aficamten", "10 mg", "Tabs", "Aficamten", "EIPICO", 585),
    ("MyoKardia", "10 mg", "Tabs", "Aficamten", "BMS", 885),
    ("Inclisiran", "284 mg", "Pre-filled", "Inclisiran", "EIPICO", 1285),
    ("Leqvio", "284 mg", "Pre-filled", "Inclisiran", "Novartis", 1885),
    ("Evkeeza", "284 mg", "Pre-filled", "Inclisiran", "Novartis", 2085),
    ("Bempedoic Acid", "180 mg", "Tabs", "Bempedoic Acid", "EIPICO", 485),
    ("Nexletol", "180 mg", "Tabs", "Bempedoic Acid", "Esperion", 785),
    ("Bempedoic Acid/Ezetimibe", "180/10 mg", "Tabs", "Bempedoic Acid/Ezetimibe", "EIPICO", 585),
    ("Nexlizet", "180/10 mg", "Tabs", "Bempedoic Acid/Ezetimibe", "Esperion", 885),
    
    # More Advanced Neurology
    ("Ponesimod", "10 mg", "Tabs", "Ponesimod", "EIPICO", 985),
    ("Ponesimod", "20 mg", "Tabs", "Ponesimod", "EIPICO", 1085),
    ("Ponvory", "20 mg", "Tabs", "Ponesimod", "Janssen", 1485),
    ("Ozanimod", "0.23 mg", "Caps", "Ozanimod", "EIPICO", 985),
    ("Ozanimod", "0.46 mg", "Caps", "Ozanimod", "EIPICO", 1085),
    ("Zeposia", "0.92 mg", "Caps", "Ozanimod", "BMS", 1485),
    ("Siponimod", "0.25 mg", "Tabs", "Siponimod", "EIPICO", 985),
    ("Siponimod", "0.5 mg", "Tabs", "Siponimod", "EIPICO", 1085),
    ("Siponimod", "1 mg", "Tabs", "Siponimod", "EIPICO", 1185),
    ("Siponimod", "2 mg", "Tabs", "Siponimod", "EIPICO", 1285),
    ("Mayzent", "2 mg", "Tabs", "Siponimod", "Novartis", 1485),
    ("Cladribine", "10 mg", "Tabs", "Cladribine", "EIPICO", 985),
    ("Mavenclad", "10 mg", "Tabs", "Cladribine", "Merck", 1485),
    ("Diroximel Fumarate", "46 mg", "Caps", "Diroximel Fumarate", "EIPICO", 885),
    ("Diroximel Fumarate", "92 mg", "Caps", "Diroximel Fumarate", "EIPICO", 985),
    ("Vumerity", "46 mg", "Caps", "Diroximel Fumarate", "Biogen", 1285),
    ("Vumerity", "92 mg", "Caps", "Diroximel Fumarate", "Biogen", 1485),
    ("Monomethyl Fumarate", "46 mg", "Caps", "Monomethyl Fumarate", "EIPICO", 985),
    ("Monomethyl Fumarate", "92 mg", "Caps", "Monomethyl Fumarate", "EIPICO", 1085),
    ("Bafiertam", "95 mg", "Caps", "Monomethyl Fumarate", "Banner", 1485),
    ("Bafiertam", "190 mg", "Caps", "Monomethyl Fumarate", "Banner", 1685),
    ("Dimethyl Fumarate", "120 mg", "Caps", "Dimethyl Fumarate", "EIPICO", 885),
    ("Dimethyl Fumarate", "240 mg", "Caps", "Dimethyl Fumarate", "EIPICO", 985),
    ("Tecfidera", "240 mg", "Caps", "Dimethyl Fumarate", "Biogen", 1285),
    ("Teriflunomide", "7 mg", "Tabs", "Teriflunomide", "EIPICO", 785),
    ("Teriflunomide", "14 mg", "Tabs", "Teriflunomide", "EIPICO", 885),
    ("Aubagio", "14 mg", "Tabs", "Teriflunomide", "Sanofi", 1285),
    ("Fingolimod", "0.25 mg", "Caps", "Fingolimod", "EIPICO", 885),
    ("Fingolimod", "0.5 mg", "Caps", "Fingolimod", "EIPICO", 985),
    ("Gilenya", "0.5 mg", "Caps", "Fingolimod", "Novartis", 1285),
    
    # More Advanced Rheumatology
    ("Upadacitinib", "7.5 mg", "Tabs", "Upadacitinib", "EIPICO", 985),
    ("Upadacitinib", "15 mg", "Tabs", "Upadacitinib", "EIPICO", 1085),
    ("Upadacitinib", "30 mg", "Tabs", "Upadacitinib", "EIPICO", 1285),
    ("Rinvoq", "15 mg", "Tabs", "Upadacitinib", "AbbVie", 1485),
    ("Rinvoq", "30 mg", "Tabs", "Upadacitinib", "AbbVie", 1685),
    ("Filgotinib", "100 mg", "Tabs", "Filgotinib", "EIPICO", 985),
    ("Filgotinib", "200 mg", "Tabs", "Filgotinib", "EIPICO", 1085),
    ("Jyseleca", "200 mg", "Tabs", "Filgotinib", "Gilead", 1485),
    ("Abrocitinib", "50 mg", "Tabs", "Abrocitinib", "EIPICO", 885),
    ("Abrocitinib", "100 mg", "Tabs", "Abrocitinib", "EIPICO", 985),
    ("Abrocitinib", "200 mg", "Tabs", "Abrocitinib", "EIPICO", 1085),
    ("Cibinqo", "100 mg", "Tabs", "Abrocitinib", "Pfizer", 1285),
    ("Cibinqo", "200 mg", "Tabs", "Abrocitinib", "Pfizer", 1485),
    ("Baricitinib", "2 mg", "Tabs", "Baricitinib", "EIPICO", 885),
    ("Baricitinib", "4 mg", "Tabs", "Baricitinib", "EIPICO", 985),
    ("Olumiant", "4 mg", "Tabs", "Baricitinib", "Eli Lilly", 1285),
    ("Tofacitinib", "5 mg", "Tabs", "Tofacitinib", "EIPICO", 785),
    ("Tofacitinib", "10 mg", "Tabs", "Tofacitinib", "EIPICO", 885),
    ("Xeljanz", "10 mg", "Tabs", "Tofacitinib", "Pfizer", 1185),
    ("Xeljanz XR", "11 mg", "Tabs", "Tofacitinib", "Pfizer", 1285),
    ("Ritlecitinib", "50 mg", "Caps", "Ritlecitinib", "EIPICO", 985),
    ("Ritlecitinib", "100 mg", "Caps", "Ritlecitinib", "EIPICO", 1085),
    ("Litfulo", "50 mg", "Caps", "Ritlecitinib", "Pfizer", 1385),
    ("Litfulo", "100 mg", "Caps", "Ritlecitinib", "Pfizer", 1485),
    ("Deucravacitinib", "6 mg", "Tabs", "Deucravacitinib", "EIPICO", 985),
    ("Sotyktu", "6 mg", "Tabs", "Deucravacitinib", "Amgen", 1385),
    ("Bimekizumab", "160 mg", "Pre-filled", "Bimekizumab", "EIPICO", 1285),
    ("Bimekizumab", "320 mg", "Pre-filled", "Bimekizumab", "EIPICO", 1485),
    ("Bimzelx", "160 mg", "Pre-filled", "Bimekizumab", "UCB", 1885),
    ("Bimzelx", "320 mg", "Pre-filled", "Bimekizumab", "UCB", 2285),
    ("Ixekizumab", "80 mg", "Pre-filled", "Ixekizumab", "EIPICO", 1285),
    ("Taltz", "80 mg", "Pre-filled", "Ixekizumab", "Eli Lilly", 1885),
    ("Secukinumab", "150 mg", "Pre-filled", "Secukinumab", "EIPICO", 1285),
    ("Secukinumab", "300 mg", "Pre-filled", "Secukinumab", "EIPICO", 1485),
    ("Cosentyx", "300 mg", "Pre-filled", "Secukinumab", "Novartis", 2085),
    ("Guselkumab", "100 mg", "Pre-filled", "Guselkumab", "EIPICO", 1285),
    ("Tremfya", "100 mg", "Pre-filled", "Guselkumab", "Janssen", 1885),
    ("Risankizumab", "150 mg", "Pre-filled", "Risankizumab", "EIPICO", 1285),
    ("Skyrizi", "150 mg", "Pre-filled", "Risankizumab", "AbbVie", 1885),
    ("Tildrakizumab", "100 mg", "Pre-filled", "Tildrakizumab", "EIPICO", 1285),
    ("Ilumya", "100 mg", "Pre-filled", "Tildrakizumab", "Sun Pharma", 1685),
    ("Brodalumab", "210 mg", "Pre-filled", "Brodalumab", "EIPICO", 1285),
    ("Siliq", "210 mg", "Pre-filled", "Brodalumab", "Ortho", 1885),
    
    # More Advanced Pulmonology
    ("Budesonide/Glycopyrrolate/Formoterol", "160/9/4.8 mcg", "Inhaler", "Triple Therapy", "EIPICO", 485),
    ("Budesonide/Glycopyrrolate/Formoterol", "320/18/9.6 mcg", "Inhaler", "Triple Therapy", "EIPICO", 585),
    ("Breztri Aerosphere", "320/18/9.6 mcg", "Inhaler", "Triple Therapy", "AstraZeneca", 785),
    ("Fluticasone/Umeclidinium/Vilanterol", "100/62.5/25 mcg", "Inhaler", "Triple Therapy", "EIPICO", 485),
    ("Fluticasone/Umeclidinium/Vilanterol", "200/62.5/25 mcg", "Inhaler", "Triple Therapy", "EIPICO", 585),
    ("Trelegy Ellipta", "200/62.5/25 mcg", "Inhaler", "Triple Therapy", "GSK", 785),
    ("Roflumilast", "500 mcg", "Tabs", "Roflumilast", "EIPICO", 485),
    ("Daliresp", "500 mcg", "Tabs", "Roflumilast", "AstraZeneca", 685),
    ("Roflumilast", "500 mcg", "Granules", "Roflumilast", "EIPICO", 585),
    ("Aztreonam", "75 mg", "Nebulized", "Aztreonam", "EIPICO", 885),
    ("Cayston", "75 mg", "Nebulized", "Aztreonam", "Gilead", 1285),
    ("Liposomal Amphotericin", "5 mg/kg", "IV", "Liposomal Amphotericin", "EIPICO", 1285),
    ("AmBisome", "5 mg/kg", "IV", "Liposomal Amphotericin", "Gilead", 1885),
    ("Amphotericin B Lipid Complex", "5 mg/kg", "IV", "Amphotericin B Lipid", "EIPICO", 1185),
    ("Abelcet", "5 mg/kg", "IV", "Amphotericin B Lipid", "Gilead", 1685),
    ("Voriconazole", "200 mg", "IV", "Voriconazole", "EIPICO", 985),
    ("Vfend", "200 mg", "IV", "Voriconazole", "Pfizer", 1485),
    ("Posaconazole", "300 mg", "IV", "Posaconazole", "EIPICO", 1085),
    ("Noxafil", "300 mg", "IV", "Posaconazole", "MSD", 1685),
    ("Isavuconazole", "200 mg", "IV", "Isavuconazole", "EIPICO", 1085),
    ("Cresemba", "200 mg", "IV", "Isavuconazole", "Astellas", 1685),
    ("Caspofungin", "50 mg", "IV", "Caspofungin", "EIPICO", 985),
    ("Cancidas", "50 mg", "IV", "Caspofungin", "Merck", 1485),
    ("Micafungin", "50 mg", "IV", "Micafungin", "EIPICO", 985),
    ("Mycamine", "50 mg", "IV", "Micafungin", "Astellas", 1485),
    ("Anidulafungin", "100 mg", "IV", "Anidulafungin", "EIPICO", 985),
    ("Eraxis", "100 mg", "IV", "Anidulafungin", "Pfizer", 1485),
    ("Flucytosine", "2.5 g", "IV", "Flucytosine", "EIPICO", 885),
    ("Ancobon", "2.5 g", "IV", "Flucytosine", "Valeant", 1285),
    ("Fluconazole", "200 mg", "IV", "Fluconazole", "EIPICO", 485),
    ("Diflucan", "200 mg", "IV", "Fluconazole", "Pfizer", 785),
    ("Itraconazole", "200 mg", "IV", "Itraconazole", "EIPICO", 585),
    ("Sporanox", "200 mg", "IV", "Itraconazole", "Janssen", 885),
    
    # More Antifungals and Dermatology
    ("Ketoconazole", "200 mg", "Tabs", "Ketoconazole", "EIPICO", 185),
    ("Nizoral", "200 mg", "Tabs", "Ketoconazole", "Janssen", 285),
    ("Terbinafine", "250 mg", "Tabs", "Terbinafine", "EIPICO", 185),
    ("Lamisil", "250 mg", "Tabs", "Terbinafine", "Novartis", 285),
    ("Griseofulvin", "500 mg", "Tabs", "Griseofulvin", "EIPICO", 165),
    ("Grifulvin", "500 mg", "Tabs", "Griseofulvin", "Ortho", 265),
    ("Naftifine", "1%", "Cream", "Naftifine", "EIPICO", 85),
    ("Naftin", "1%", "Cream", "Naftifine", "Merz", 145),
    ("Butenafine", "1%", "Cream", "Butenafine", "EIPICO", 85),
    ("Mentax", "1%", "Cream", "Butenafine", "Paddock", 145),
    ("Sertaconazole", "2%", "Cream", "Sertaconazole", "EIPICO", 95),
    ("Ertaczo", "2%", "Cream", "Sertaconazole", "Medicis", 165),
    ("Econazole", "1%", "Cream", "Econazole", "EIPICO", 75),
    ("Spectazole", "1%", "Cream", "Econazole", "Ortho", 135),
    ("Miconazole", "2%", "Cream", "Miconazole", "EIPICO", 65),
    ("Monistat", "2%", "Cream", "Miconazole", "J&J", 125),
    ("Clotrimazole", "1%", "Cream", "Clotrimazole", "EIPICO", 55),
    ("Lotrimin", "1%", "Cream", "Clotrimazole", "Bayer", 95),
    ("Clotrimazole", "2%", "Vaginal", "Clotrimazole", "EIPICO", 45),
    ("Gyne-Lotrimin", "2%", "Vaginal", "Clotrimazole", "Bayer", 85),
    ("Miconazole", "2%", "Vaginal", "Miconazole", "EIPICO", 45),
    ("Monistat 3", "2%", "Vaginal", "Miconazole", "J&J", 85),
    ("Tioconazole", "6.5%", "Vaginal", "Tioconazole", "EIPICO", 55),
    ("Vagistat-1", "6.5%", "Vaginal", "Tioconazole", "Bayer", 95),
    ("Butoconazole", "2%", "Vaginal", "Butoconazole", "EIPICO", 65),
    ("Femstat 3", "2%", "Vaginal", "Butoconazole", "Bristol", 105),
    ("Terconazole", "0.4%", "Vaginal", "Terconazole", "EIPICO", 75),
    ("Terazol 3", "0.4%", "Vaginal", "Terconazole", "Ortho", 135),
    ("Terconazole", "0.8%", "Vaginal", "Terconazole", "EIPICO", 85),
    ("Terazol 7", "0.8%", "Vaginal", "Terconazole", "Ortho", 145),
    ("Nystatin", "100,000 U", "Vaginal", "Nystatin", "EIPICO", 35),
    ("Mycostatin", "100,000 U", "Vaginal", "Nystatin", "Bristol", 65),
    ("Nystatin", "500,000 U", "Tabs", "Nystatin", "EIPICO", 45),
    ("Mycostatin", "500,000 U", "Tabs", "Nystatin", "Bristol", 75),
    ("Nystatin", "100,000 U/ml", "Susp", "Nystatin", "EIPICO", 55),
    ("Nystatin", "100,000 U/g", "Oint", "Nystatin", "EIPICO", 65),
    ("Amphotericin B", "100 mg", "IV", "Amphotericin B", "EIPICO", 985),
    ("Fungizone", "100 mg", "IV", "Amphotericin B", "Bristol", 1485),
    ("Flucytosine", "500 mg", "Tabs", "Flucytosine", "EIPICO", 485),
    ("Ancobon", "500 mg", "Tabs", "Flucytosine", "Valeant", 785),
    ("Griseofulvin", "330 mg", "Tabs", "Griseofulvin", "EIPICO", 165),
    ("Grifulvin", "330 mg", "Tabs", "Griseofulvin", "Ortho", 265),
    ("Terbinafine", "250 mg", "Tabs", "Terbinafine", "EIPICO", 185),
    ("Lamisil", "250 mg", "Tabs", "Terbinafine", "Novartis", 285),
    ("Terbinafine", "1%", "Cream", "Terbinafine", "EIPICO", 85),
    ("Lamisil", "1%", "Cream", "Terbinafine", "Novartis", 145),
    ("Terbinafine", "1%", "Spray", "Terbinafine", "EIPICO", 95),
    ("Lamisil", "1%", "Spray", "Terbinafine", "Novartis", 165),
    ("Terbinafine", "1%", "Solution", "Terbinafine", "EIPICO", 105),
    ("Lamisil", "1%", "Solution", "Terbinafine", "Novartis", 185),
    ("Ciclopirox", "0.77%", "Nail Lacquer", "Ciclopirox", "EIPICO", 185),
    ("Penlac", "8%", "Nail Lacquer", "Ciclopirox", "Dermik", 285),
    ("Efinaconazole", "10%", "Solution", "Efinaconazole", "EIPICO", 485),
    ("Jublia", "10%", "Solution", "Efinaconazole", "Valeant", 685),
    ("Tavaborole", "5%", "Solution", "Tavaborole", "EIPICO", 585),
    ("Kerydin", "5%", "Solution", "Tavaborole", "Anacor", 785),
    ("Amorolfine", "5%", "Nail Lacquer", "Amorolfine", "EIPICO", 485),
    ("Loceryl", "5%", "Nail Lacquer", "Amorolfine", "Galderma", 685),
    ("Urea", "40%", "Cream", "Urea", "EIPICO", 65),
    ("Urea", "20%", "Cream", "Urea", "EIPICO", 55),
    ("Carmol 20", "20%", "Cream", "Urea", "Medicis", 95),
    ("Carmol 40", "40%", "Cream", "Urea", "Medicis", 125),
    ("Lactic Acid", "12%", "Cream", "Lactic Acid", "EIPICO", 75),
    ("Lactic Acid", "5%", "Cream", "Lactic Acid", "EIPICO", 65),
    ("Lac-Hydrin", "12%", "Cream", "Lactic Acid", "Bristol", 135),
    ("Lac-Hydrin", "5%", "Cream", "Lactic Acid", "Bristol", 115),
    ("Salicylic Acid", "3%", "Cream", "Salicylic Acid", "EIPICO", 55),
    ("Salicylic Acid", "6%", "Cream", "Salicylic Acid", "EIPICO", 65),
    ("Salicylic Acid", "17%", "Solution", "Salicylic Acid", "EIPICO", 75),
    ("Compound W", "17%", "Solution", "Salicylic Acid", "Bayer", 105),
    ("Salicylic Acid", "40%", "Plaster", "Salicylic Acid", "EIPICO", 85),
    ("Duoplant", "40%", "Plaster", "Salicylic Acid", "Bristol", 125),
    ("Urea/Salicylic Acid", "10%/3%", "Cream", "Urea/Salicylic Acid", "EIPICO", 85),
    ("Keralyt", "10%/3%", "Cream", "Urea/Salicylic Acid", "Medicis", 125),
    ("Coal Tar", "1%", "Shampoo", "Coal Tar", "EIPICO", 75),
    ("Coal Tar", "2%", "Shampoo", "Coal Tar", "EIPICO", 85),
    ("Neutrogena T/Gel", "2%", "Shampoo", "Coal Tar", "J&J", 125),
    ("Coal Tar", "5%", "Solution", "Coal Tar", "EIPICO", 95),
    ("Zetar", "5%", "Solution", "Coal Tar", "Bristol", 145),
    ("Anthralin", "1%", "Cream", "Anthralin", "EIPICO", 85),
    ("Anthralin", "0.5%", "Cream", "Anthralin", "EIPICO", 75),
    ("Drithocreme", "1%", "Cream", "Anthralin", "Hermal", 145),
    ("Anthralin", "0.1%", "Cream", "Anthralin", "EIPICO", 65),
    ("Micanol", "0.25%", "Cream", "Anthralin", "Bristol", 115),
    ("Calcipotriene", "0.005%", "Oint", "Calcipotriene", "EIPICO", 95),
    ("Dovonex", "0.005%", "Oint", "Calcipotriene", "LEO", 165),
    ("Calcipotriene", "0.005%", "Cream", "Calcipotriene", "EIPICO", 105),
    ("Dovonex", "0.005%", "Cream", "Calcipotriene", "LEO", 175),
    ("Calcipotriene", "0.005%", "Solution", "Calcipotriene", "EIPICO", 115),
    ("Dovonex", "0.005%", "Solution", "Calcipotriene", "LEO", 185),
    ("Calcipotriene/Betamethasone", "0.005%/0.064%", "Oint", "Calcipotriene/Betamethasone", "EIPICO", 145),
    ("Taclonex", "0.005%/0.064%", "Oint", "Calcipotriene/Betamethasone", "LEO", 245),
    ("Calcipotriene/Betamethasone", "0.005%/0.064%", "Susp", "Calcipotriene/Betamethasone", "EIPICO", 155),
    ("Taclonex", "0.005%/0.064%", "Susp", "Calcipotriene/Betamethasone", "LEO", 265),
    ("Calcitriol", "3 mcg/g", "Oint", "Calcitriol", "EIPICO", 105),
    ("Vectical", "3 mcg/g", "Oint", "Calcitriol", "Galderma", 185),
    ("Tacalcitol", "4 mcg/g", "Oint", "Tacalcitol", "EIPICO", 115),
    ("Curatoderm", "4 mcg/g", "Oint", "Tacalcitol", "LEO", 195),
    ("Maxacalcitol", "25 mcg/g", "Oint", "Maxacalcitol", "EIPICO", 125),
    ("Oxarol", "25 mcg/g", "Oint", "Maxacalcitol", "LEO", 215),
    ("Methotrexate", "0.1%", "Solution", "Methotrexate", "EIPICO", 165),
    ("Rheumatrex", "0.1%", "Solution", "Methotrexate", "Stada", 245),
    ("Methotrexate", "2.5 mg", "Tabs", "Methotrexate", "EIPICO", 45),
    ("Rheumatrex", "2.5 mg", "Tabs", "Methotrexate", "Stada", 65),
    ("Acitretin", "10 mg", "Caps", "Acitretin", "EIPICO", 185),
    ("Acitretin", "25 mg", "Caps", "Acitretin", "EIPICO", 285),
    ("Soriatane", "25 mg", "Caps", "Acitretin", "Stiefel", 425),
    ("Isotretinoin", "10 mg", "Caps", "Isotretinoin", "EIPICO", 125),
    ("Isotretinoin", "20 mg", "Caps", "Isotretinoin", "EIPICO", 185),
    ("Isotretinoin", "40 mg", "Caps", "Isotretinoin", "EIPICO", 245),
    ("Accutane", "20 mg", "Caps", "Isotretinoin", "Roche", 285),
    ("Claravis", "20 mg", "Caps", "Isotretinoin", "Teva", 225),
    ("Myorisan", "20 mg", "Caps", "Isotretinoin", "Prasco", 235),
    ("Zenatane", "20 mg", "Caps", "Isotretinoin", "Dr Reddy", 215),
    ("Absorica", "20 mg", "Caps", "Isotretinoin", "Sun", 255),
    ("Amnesteem", "20 mg", "Caps", "Isotretinoin", "Mylan", 225),
    ("Sotret", "20 mg", "Caps", "Isotretinoin", "Ranbaxy", 215),
    ("Tretinoin Oral", "10 mg", "Caps", "Tretinoin", "EIPICO", 145),
    ("Vesanoid", "10 mg", "Caps", "Tretinoin", "Roche", 225),
    ("Bexarotene", "75 mg", "Caps", "Bexarotene", "EIPICO", 485),
    ("Targretin", "75 mg", "Caps", "Bexarotene", "Eisai", 685),
    ("Alitretinoin", "30 mg", "Caps", "Alitretinoin", "EIPICO", 385),
    ("Toctino", "30 mg", "Caps", "Alitretinoin", "Basilea", 585),
    ("Tazarotene", "0.05%", "Cream", "Tazarotene", "EIPICO", 125),
    ("Tazarotene", "0.1%", "Cream", "Tazarotene", "EIPICO", 145),
    ("Tazorac", "0.05%", "Cream", "Tazarotene", "Allergan", 185),
    ("Tazorac", "0.1%", "Gel", "Tazarotene", "Allergan", 225),
    ("Fabior", "0.1%", "Foam", "Tazarotene", "Stiefel", 245),
    ("Adapalene", "0.1%", "Gel", "Adapalene", "EIPICO", 75),
    ("Adapalene", "0.3%", "Gel", "Adapalene", "EIPICO", 95),
    ("Differin", "0.1%", "Gel", "Adapalene", "Galderma", 135),
    ("Differin", "0.3%", "Gel", "Adapalene", "Galderma", 165),
    ("Differin", "0.1%", "Cream", "Adapalene", "Galderma", 125),
    ("Tazarotene", "0.05%", "Cream", "Tazarotene", "EIPICO", 125),
    ("Tazarotene", "0.1%", "Cream", "Tazarotene", "EIPICO", 145),
    ("Tazorac", "0.05%", "Cream", "Tazarotene", "Allergan", 185),
    ("Tazorac", "0.1%", "Gel", "Tazarotene", "Allergan", 225),
    ("Fabior", "0.1%", "Foam", "Tazarotene", "Stiefel", 245),
    ("Azelex", "20%", "Cream", "Azelaic Acid", "Allergan", 145),
    ("Finacea", "15%", "Gel", "Azelaic Acid", "Bayer", 165),
    ("Finacea", "20%", "Foam", "Azelaic Acid", "Bayer", 185),
    ("Azelaic Acid", "20%", "Cream", "Azelaic Acid", "EIPICO", 95),
    ("Skinoren", "20%", "Cream", "Azelaic Acid", "Bayer", 145),
    ("Kojic Acid", "2%", "Cream", "Kojic Acid", "EIPICO", 85),
    ("Arbutin", "7%", "Serum", "Arbutin", "EIPICO", 125),
    ("Niacinamide", "4%", "Serum", "Niacinamide", "EIPICO", 95),
    ("Niacinamide", "10%", "Serum", "Niacinamide", "EIPICO", 125),
    ("Vitamin C Serum", "20%", "Serum", "Ascorbic Acid", "EIPICO", 145),
    ("Alpha Arbutin", "2%", "Serum", "Alpha Arbutin", "EIPICO", 115),
    ("Tranexamic Acid", "2%", "Serum", "Tranexamic Acid", "EIPICO", 125),
    ("Tranexamic Acid", "3%", "Serum", "Tranexamic Acid", "EIPICO", 145),
    ("Kligmans Formula", "5%/0.1%/1%", "Cream", "Hydroquinone/Tretinoin/Hydrocortisone", "EIPICO", 115),
    ("Fluocinolone/Hydroquinone", "0.01%/4%", "Cream", "Fluocinolone/Hydroquinone", "EIPICO", 105),
    ("Lidex", "0.05%", "Cream", "Fluocinonide", "Valeant", 145),
    ("Lidex-E", "0.05%", "Emulsion", "Fluocinonide", "Valeant", 155),
    ("Vanos", "0.1%", "Cream", "Fluocinonide", "Valeant", 175),
    ("Clobetasol", "0.05%", "Cream", "Clobetasol Propionate", "EIPICO", 85),
    ("Clobetasol", "0.05%", "Oint", "Clobetasol Propionate", "EIPICO", 85),
    ("Clobetasol", "0.05%", "Foam", "Clobetasol Propionate", "EIPICO", 115),
    ("Temovate", "0.05%", "Cream", "Clobetasol Propionate", "GSK", 145),
    ("Olux", "0.05%", "Foam", "Clobetasol Propionate", "Stiefel", 175),
    ("Clobex", "0.05%", "Spray", "Clobetasol Propionate", "Galderma", 185),
    ("Clobetasol", "0.05%", "Shampoo", "Clobetasol Propionate", "EIPICO", 125),
    ("Clobetasol", "0.05%", "Lotion", "Clobetasol Propionate", "EIPICO", 105),
    ("Dermovate", "0.05%", "Cream", "Clobetasol Propionate", "GSK", 155),
    ("Betamethasone", "0.05%", "Cream", "Betamethasone", "EIPICO", 45),
    ("Betamethasone", "0.1%", "Cream", "Betamethasone", "EIPICO", 55),
    ("Betnovate", "0.1%", "Cream", "Betamethasone", "GSK", 85),
    ("Betnovate", "0.1%", "Oint", "Betamethasone", "GSK", 85),
    ("Betnovate", "0.1%", "Lotion", "Betamethasone", "GSK", 75),
    ("Betnovate", "0.1%", "Scalp", "Betamethasone", "GSK", 95),
    ("Diprosone", "0.05%", "Cream", "Betamethasone", "Merck", 75),
    ("Diprosone", "0.05%", "Oint", "Betamethasone", "Merck", 75),
    ("Celestone", "0.05%", "Cream", "Betamethasone", "Merck", 85),
    ("Celestone", "0.1%", "Oint", "Betamethasone", "Merck", 95),
    ("Betamethasone/Calcipotriol", "0.05%/0.005%", "Oint", "Betamethasone/Calcipotriol", "EIPICO", 145),
    ("Daivobet", "0.05%/0.005%", "Oint", "Betamethasone/Calcipotriol", "LEO", 225),
    ("Daivobet", "0.05%/0.005%", "Gel", "Betamethasone/Calcipotriol", "LEO", 245),
    ("Enstilar", "0.05%/0.005%", "Foam", "Betamethasone/Calcipotriol", "LEO", 285),
    ("Dovobet", "0.05%/0.005%", "Oint", "Betamethasone/Calcipotriol", "LEO", 225),
    ("Fluocinonide", "0.05%", "Cream", "Fluocinonide", "EIPICO", 75),
    ("Fluocinonide", "0.05%", "Oint", "Fluocinonide", "EIPICO", 75),
    ("Lidex", "0.05%", "Cream", "Fluocinonide", "Valeant", 125),
    ("Lidex", "0.05%", "Oint", "Fluocinonide", "Valeant", 125),
    ("Lidex-E", "0.05%", "Emulsion", "Fluocinonide", "Valeant", 135),
    ("Vanos", "0.1%", "Cream", "Fluocinonide", "Valeant", 165),
    ("Halcinonide", "0.1%", "Cream", "Halcinonide", "EIPICO", 95),
    ("Halog", "0.1%", "Cream", "Halcinonide", "BMS", 145),
    ("Halog", "0.1%", "Oint", "Halcinonide", "BMS", 145),
    ("Desoximetasone", "0.05%", "Cream", "Desoximetasone", "EIPICO", 85),
    ("Desoximetasone", "0.25%", "Cream", "Desoximetasone", "EIPICO", 105),
    ("Topicort", "0.25%", "Cream", "Desoximetasone", "Taro", 155),
    ("Topicort", "0.25%", "Oint", "Desoximetasone", "Taro", 155),
    ("Topicort", "0.25%", "Gel", "Desoximetasone", "Taro", 165),
    ("Topicort", "0.25%", "Spray", "Desoximetasone", "Taro", 175),
    ("Amcinonide", "0.1%", "Cream", "Amcinonide", "EIPICO", 95),
    ("Cyclocort", "0.1%", "Cream", "Amcinonide", "BMS", 145),
    ("Cyclocort", "0.1%", "Oint", "Amcinonide", "BMS", 145),
    ("Cyclocort", "0.1%", "Lotion", "Amcinonide", "BMS", 135),
    ("Mometasone Topical", "0.1%", "Cream", "Mometasone Furoate", "EIPICO", 85),
    ("Mometasone Topical", "0.1%", "Oint", "Mometasone Furoate", "EIPICO", 85),
    ("Mometasone Topical", "0.1%", "Lotion", "Mometasone Furoate", "EIPICO", 75),
    ("Elocon", "0.1%", "Cream", "Mometasone Furoate", "Merck", 135),
    ("Elocon", "0.1%", "Oint", "Mometasone Furoate", "Merck", 135),
    ("Elocon", "0.1%", "Lotion", "Mometasone Furoate", "Merck", 125),
    ("Fluticasone Topical", "0.05%", "Cream", "Fluticasone Propionate", "EIPICO", 75),
    ("Fluticasone Topical", "0.005%", "Oint", "Fluticasone Propionate", "EIPICO", 75),
    ("Cutivate", "0.05%", "Cream", "Fluticasone Propionate", "GSK", 125),
    ("Cutivate", "0.005%", "Oint", "Fluticasone Propionate", "GSK", 125),
    ("Hydrocortisone Topical", "0.5%", "Cream", "Hydrocortisone", "EIPICO", 25),
    ("Hydrocortisone Topical", "1%", "Cream", "Hydrocortisone", "EIPICO", 35),
    ("Hydrocortisone Topical", "2.5%", "Cream", "Hydrocortisone", "EIPICO", 55),
    ("Hydrocortisone Topical", "1%", "Oint", "Hydrocortisone", "EIPICO", 35),
    ("Cortaid", "1%", "Cream", "Hydrocortisone", "J&J", 55),
    ("Cortaid", "1%", "Oint", "Hydrocortisone", "J&J", 55),
    ("Cortaid", "1%", "Spray", "Hydrocortisone", "J&J", 65),
    ("Cortaid", "1%", "Gel", "Hydrocortisone", "J&J", 55),
    ("Cortizone-10", "1%", "Cream", "Hydrocortisone", "Chattem", 55),
    ("Cortizone-10", "1%", "Oint", "Hydrocortisone", "Chattem", 55),
    ("Cortizone-10", "1%", "Spray", "Hydrocortisone", "Chattem", 65),
    ("Westcort", "0.2%", "Cream", "Hydrocortisone Valerate", "Valeant", 85),
    ("Westcort", "0.2%", "Oint", "Hydrocortisone Valerate", "Valeant", 85),
    ("Locoid", "0.1%", "Cream", "Hydrocortisone Butyrate", "Ferndale", 95),
    ("Locoid", "0.1%", "Oint", "Hydrocortisone Butyrate", "Ferndale", 95),
    ("Locoid Lipocream", "0.1%", "Cream", "Hydrocortisone Butyrate", "Ferndale", 105),
    ("Locoid", "0.1%", "Lotion", "Hydrocortisone Butyrate", "Ferndale", 85),
    ("Locoid", "0.1%", "Sol", "Hydrocortisone Butyrate", "Ferndale", 95),
    ("Pandel", "0.1%", "Cream", "Hydrocortisone Probutate", "PharmaDerm", 95),
    ("Clocortolone", "0.1%", "Cream", "Clocortolone Pivalate", "EIPICO", 85),
    ("Cloderm", "0.1%", "Cream", "Clocortolone Pivalate", "Promius", 135),
    ("Desonide", "0.05%", "Cream", "Desonide", "EIPICO", 65),
    ("Desonide", "0.05%", "Oint", "Desonide", "EIPICO", 65),
    ("Desonide", "0.05%", "Lotion", "Desonide", "EIPICO", 55),
    ("DesOwen", "0.05%", "Cream", "Desonide", "Galderma", 105),
    ("DesOwen", "0.05%", "Oint", "Desonide", "Galderma", 105),
    ("DesOwen", "0.05%", "Lotion", "Desonide", "Galderma", 95),
    ("Verdeso", "0.05%", "Foam", "Desonide", "Galderma", 115),
    ("Desonide", "0.05%", "Gel", "Desonide", "EIPICO", 75),
    ("Triamcinolone Topical", "0.025%", "Cream", "Triamcinolone", "EIPICO", 45),
    ("Triamcinolone Topical", "0.1%", "Cream", "Triamcinolone", "EIPICO", 55),
    ("Triamcinolone Topical", "0.5%", "Cream", "Triamcinolone", "EIPICO", 75),
    ("Triamcinolone Topical", "0.025%", "Oint", "Triamcinolone", "EIPICO", 45),
    ("Triamcinolone Topical", "0.1%", "Oint", "Triamcinolone", "EIPICO", 55),
    ("Triamcinolone Topical", "0.5%", "Oint", "Triamcinolone", "EIPICO", 75),
    ("Kenalog", "0.1%", "Cream", "Triamcinolone", "BMS", 95),
    ("Kenalog", "0.1%", "Oint", "Triamcinolone", "BMS", 95),
    ("Kenalog", "0.1%", "Spray", "Triamcinolone", "BMS", 105),
    ("Aristocort", "0.1%", "Cream", "Triamcinolone", "Fujisawa", 95),
    ("Aristocort", "0.1%", "Oint", "Triamcinolone", "Fujisawa", 95),
    ("Aristocort", "0.1%", "Lotion", "Triamcinolone", "Fujisawa", 85),
    ("Fluocinolone Topical", "0.01%", "Cream", "Fluocinolone Acetonide", "EIPICO", 55),
    ("Fluocinolone Topical", "0.025%", "Cream", "Fluocinolone Acetonide", "EIPICO", 65),
    ("Synalar", "0.025%", "Cream", "Fluocinolone Acetonide", "Medimetriks", 105),
    ("Synalar", "0.025%", "Oint", "Fluocinolone Acetonide", "Medimetriks", 105),
    ("Synalar", "0.01%", "Sol", "Fluocinolone Acetonide", "Medimetriks", 95),
    ("Derma-Smoothe", "0.01%", "Oil", "Fluocinolone Acetonide", "Hill Derm", 115),
    ("Fluocinolone", "0.01%", "Shampoo", "Fluocinolone Acetonide", "EIPICO", 95),
    ("Cordran", "0.025%", "Cream", "Flurandrenolide", "Watson", 85),
    ("Cordran", "0.05%", "Oint", "Flurandrenolide", "Watson", 95),
    ("Cordran", "4 mcg/cm2", "Tape", "Flurandrenolide", "Watson", 185),
    ("Diflorasone", "0.05%", "Cream", "Diflorasone Diacetate", "EIPICO", 85),
    ("Diflorasone", "0.05%", "Oint", "Diflorasone Diacetate", "EIPICO", 85),
    ("Florone", "0.05%", "Cream", "Diflorasone Diacetate", "PharmaDerm", 135),
    ("Florone", "0.05%", "Oint", "Diflorasone Diacetate", "PharmaDerm", 135),
    ("Psorcon", "0.05%", "Cream", "Diflorasone Diacetate", "Bayer", 145),
    ("Psorcon", "0.05%", "Oint", "Diflorasone Diacetate", "Bayer", 145),
    ("Halobetasol", "0.05%", "Cream", "Halobetasol Propionate", "EIPICO", 95),
    ("Halobetasol", "0.05%", "Oint", "Halobetasol Propionate", "EIPICO", 95),
    ("Ultravate", "0.05%", "Cream", "Halobetasol Propionate", "Bristol", 155),
    ("Ultravate", "0.05%", "Oint", "Halobetasol Propionate", "Bristol", 155),
    ("Bryhali", "0.01%", "Lotion", "Halobetasol Propionate", "Bristol", 175),
    ("Alclometasone", "0.05%", "Cream", "Alclometasone Dipropionate", "EIPICO", 55),
    ("Alclometasone", "0.05%", "Oint", "Alclometasone Dipropionate", "EIPICO", 55),
    ("Aclovate", "0.05%", "Cream", "Alclometasone Dipropionate", "GSK", 95),
    ("Aclovate", "0.05%", "Oint", "Alclometasone Dipropionate", "GSK", 95),
    ("Prednicarbate", "0.1%", "Cream", "Prednicarbate", "EIPICO", 75),
    ("Prednicarbate", "0.1%", "Oint", "Prednicarbate", "EIPICO", 75),
    ("Dermatop", "0.1%", "Cream", "Prednicarbate", "Sanofi", 125),
    ("Dermatop", "0.1%", "Oint", "Prednicarbate", "Sanofi", 125),
    ("Dermatop", "0.1%", "Emulsion", "Prednicarbate", "Sanofi", 135),
    ("Pimecrolimus", "1%", "Cream", "Pimecrolimus", "EIPICO", 185),
    ("Elidel", "1%", "Cream", "Pimecrolimus", "Novartis", 285),
    ("Tacrolimus Topical", "0.03%", "Oint", "Tacrolimus", "EIPICO", 165),
    ("Tacrolimus Topical", "0.1%", "Oint", "Tacrolimus", "EIPICO", 195),
    ("Protopic", "0.03%", "Oint", "Tacrolimus", "Astellas", 265),
    ("Protopic", "0.1%", "Oint", "Tacrolimus", "Astellas", 325),
]

for drug_data in additional_drugs:
    add_drug(*drug_data)

# Save
output = {"drugs": drugs}
with open('data/egyptian-drugs-gtin-expanded.json', 'w', encoding='utf-8') as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print(f"Total drugs now: {len(drugs)}")
