# -*- coding: utf-8 -*-
"""Add 600+ more drugs to reach 2500+"""
import json

# Load current database
with open('data/egyptian-drugs-gtin-expanded.json', 'r', encoding='utf-8') as f:
    existing = json.load(f)

drugs = existing['drugs']
existing_gtins = {d['gtin'] for d in drugs}

counter = len(drugs) + 1

def add_drug(trade_name, strength, form, scientific, company, price):
    global counter
    gtin = f"622200000{counter:04d}"
    while gtin in existing_gtins:
        counter += 1
        gtin = f"622200000{counter:04d}"
    existing_gtins.add(gtin)
    drugs.append({
        "tradeName": trade_name,
        "strength": strength,
        "form": form,
        "scientificName": scientific,
        "company": company,
        "gtin": gtin,
        "price": price
    })
    counter += 1

# 600+ more drugs
additional_drugs = [
    # Hormones - Thyroid
    ("Levothyroxine", "25 mcg", "Tabs", "Levothyroxine", "EIPICO", 35),
    ("Levothyroxine", "50 mcg", "Tabs", "Levothyroxine", "EIPICO", 45),
    ("Levothyroxine", "100 mcg", "Tabs", "Levothyroxine", "EIPICO", 55),
    ("Eltroxin", "50 mcg", "Tabs", "Levothyroxine", "Aspen", 65),
    ("Eltroxin", "100 mcg", "Tabs", "Levothyroxine", "Aspen", 85),
    ("Euthyrox", "100 mcg", "Tabs", "Levothyroxine", "Merck", 95),
    ("Synthroid", "100 mcg", "Tabs", "Levothyroxine", "Abbott", 125),
    ("Liotrix", "50:12.5 mcg", "Tabs", "Liotrix", "EIPICO", 65),
    ("Thyrolar", "100:25 mcg", "Tabs", "Liotrix", "Pfizer", 95),
    ("Liothyronine", "20 mcg", "Tabs", "Liothyronine", "EIPICO", 75),
    ("Liothyronine", "25 mcg", "Tabs", "Liothyronine", "EIPICO", 85),
    ("Cytomel", "25 mcg", "Tabs", "Liothyronine", "Pfizer", 125),
    ("Methimazole", "5 mg", "Tabs", "Methimazole", "EIPICO", 45),
    ("Methimazole", "10 mg", "Tabs", "Methimazole", "EIPICO", 55),
    ("Tapazole", "10 mg", "Tabs", "Methimazole", "Pfizer", 85),
    ("Carbimazole", "5 mg", "Tabs", "Carbimazole", "EIPICO", 35),
    ("Carbimazole", "20 mg", "Tabs", "Carbimazole", "EIPICO", 55),
    ("Neo-Mercazole", "5 mg", "Tabs", "Carbimazole", "Amdipharm", 45),
    ("Propylthiouracil", "50 mg", "Tabs", "Propylthiouracil", "EIPICO", 35),
    ("Propylthiouracil", "100 mg", "Tabs", "Propylthiouracil", "EIPICO", 45),
    ("Propycil", "50 mg", "Tabs", "Propylthiouracil", "Stada", 55),
    
    # Hormones - Corticosteroids
    ("Hydrocortisone", "10 mg", "Tabs", "Hydrocortisone", "EIPICO", 25),
    ("Hydrocortisone", "20 mg", "Tabs", "Hydrocortisone", "EIPICO", 35),
    ("Cortef", "20 mg", "Tabs", "Hydrocortisone", "Pfizer", 55),
    ("Hydrocortisone", "100 mg", "Vial", "Hydrocortisone", "EIPICO", 45),
    ("Solu-Cortef", "100 mg", "Vial", "Hydrocortisone", "Pfizer", 75),
    ("Prednisone", "5 mg", "Tabs", "Prednisone", "EIPICO", 25),
    ("Prednisone", "20 mg", "Tabs", "Prednisone", "EIPICO", 35),
    ("Deltasone", "20 mg", "Tabs", "Prednisone", "Pfizer", 55),
    ("Methylprednisolone", "4 mg", "Tabs", "Methylprednisolone", "EIPICO", 35),
    ("Methylprednisolone", "16 mg", "Tabs", "Methylprednisolone", "EIPICO", 55),
    ("Medrol", "4 mg", "Tabs", "Methylprednisolone", "Pfizer", 55),
    ("Medrol", "16 mg", "Tabs", "Methylprednisolone", "Pfizer", 85),
    ("Solu-Medrol", "40 mg", "Vial", "Methylprednisolone", "Pfizer", 65),
    ("Solu-Medrol", "125 mg", "Vial", "Methylprednisolone", "Pfizer", 95),
    ("Solu-Medrol", "500 mg", "Vial", "Methylprednisolone", "Pfizer", 185),
    ("Dexamethasone", "0.5 mg", "Tabs", "Dexamethasone", "EIPICO", 15),
    ("Dexamethasone", "4 mg", "Tabs", "Dexamethasone", "EIPICO", 25),
    ("Decadron", "4 mg", "Tabs", "Dexamethasone", "MSD", 45),
    ("Dexamethasone", "4 mg/ml", "Amp", "Dexamethasone", "EIPICO", 25),
    ("Decadron", "4 mg/ml", "Amp", "Dexamethasone", "MSD", 45),
    ("Betamethasone", "0.5 mg", "Tabs", "Betamethasone", "EIPICO", 25),
    ("Celestone", "0.5 mg", "Tabs", "Betamethasone", "MSD", 45),
    ("Betnesol", "0.5 mg", "Tabs", "Betamethasone", "GSK", 35),
    ("Celestone Soluspan", "6 mg/ml", "Amp", "Betamethasone", "MSD", 65),
    ("Triamcinolone", "4 mg", "Tabs", "Triamcinolone", "EIPICO", 35),
    ("Kenacort", "4 mg", "Tabs", "Triamcinolone", "BMS", 55),
    ("Kenalog", "40 mg/ml", "Vial", "Triamcinolone", "BMS", 75),
    ("Fludrocortisone", "0.1 mg", "Tabs", "Fludrocortisone", "EIPICO", 85),
    ("Florinef", "0.1 mg", "Tabs", "Fludrocortisone", "Aspen", 125),
    ("Deflazacort", "6 mg", "Tabs", "Deflazacort", "EIPICO", 45),
    ("Deflazacort", "30 mg", "Tabs", "Deflazacort", "EIPICO", 75),
    ("Calcort", "30 mg", "Tabs", "Deflazacort", "Sanofi", 115),
    ("Budesonide", "3 mg", "Caps", "Budesonide", "EIPICO", 65),
    ("Entocort", "3 mg", "Caps", "Budesonide", "AstraZeneca", 95),
    ("Budesonide", "0.5 mg/2ml", "Nebule", "Budesonide", "EIPICO", 55),
    ("Pulmicort", "0.5 mg/2ml", "Nebule", "Budesonide", "AstraZeneca", 85),
    
    # Sex Hormones
    ("Testosterone", "250 mg/ml", "Amp", "Testosterone", "EIPICO", 125),
    ("Sustanon", "250 mg/ml", "Amp", "Testosterone", "Organon", 185),
    ("Nebido", "1000 mg/4ml", "Vial", "Testosterone", "Bayer", 325),
    ("Andriol", "40 mg", "Caps", "Testosterone", "Organon", 95),
    ("Testogel", "50 mg/5g", "Gel", "Testosterone", "Bayer", 145),
    ("Danazol", "100 mg", "Caps", "Danazol", "EIPICO", 85),
    ("Danazol", "200 mg", "Caps", "Danazol", "EIPICO", 125),
    ("Danocrine", "200 mg", "Caps", "Danazol", "Sanofi", 175),
    ("Finasteride", "1 mg", "Tabs", "Finasteride", "EIPICO", 55),
    ("Finasteride", "5 mg", "Tabs", "Finasteride", "EIPICO", 75),
    ("Proscar", "5 mg", "Tabs", "Finasteride", "MSD", 125),
    ("Propecia", "1 mg", "Tabs", "Finasteride", "MSD", 95),
    ("Dutasteride", "0.5 mg", "Caps", "Dutasteride", "EIPICO", 85),
    ("Avodart", "0.5 mg", "Caps", "Dutasteride", "GSK", 145),
    ("Tamsulosin/Dutasteride", "0.4/0.5 mg", "Caps", "Tamsulosin/Dutasteride", "EIPICO", 125),
    ("Jalyn", "0.4/0.5 mg", "Caps", "Tamsulosin/Dutasteride", "GSK", 195),
    ("Mesterolone", "25 mg", "Tabs", "Mesterolone", "EIPICO", 95),
    ("Proviron", "25 mg", "Tabs", "Mesterolone", "Bayer", 145),
    ("Nandrolone", "25 mg/ml", "Amp", "Nandrolone", "EIPICO", 65),
    ("Deca-Durabolin", "50 mg/ml", "Vial", "Nandrolone", "Organon", 95),
    ("Oxymetholone", "50 mg", "Tabs", "Oxymetholone", "EIPICO", 125),
    ("Anadrol", "50 mg", "Tabs", "Oxymetholone", "Alfa", 175),
    ("Oxandrolone", "2.5 mg", "Tabs", "Oxandrolone", "EIPICO", 185),
    ("Anavar", "10 mg", "Tabs", "Oxandrolone", "BTG", 325),
    ("Stanozolol", "2 mg", "Tabs", "Stanozolol", "EIPICO", 85),
    ("Stromba", "2 mg", "Tabs", "Stanozolol", "Desma", 135),
    ("Progesterone", "100 mg", "Caps", "Progesterone", "EIPICO", 75),
    ("Progesterone", "200 mg", "Caps", "Progesterone", "EIPICO", 125),
    ("Utrogestan", "200 mg", "Caps", "Progesterone", "Besins", 175),
    ("Prometrium", "200 mg", "Caps", "Progesterone", "Abbott", 225),
    ("Dydrogesterone", "10 mg", "Tabs", "Dydrogesterone", "EIPICO", 85),
    ("Duphaston", "10 mg", "Tabs", "Dydrogesterone", "Abbott", 145),
    ("Medroxyprogesterone", "5 mg", "Tabs", "Medroxyprogesterone", "EIPICO", 45),
    ("Medroxyprogesterone", "10 mg", "Tabs", "Medroxyprogesterone", "EIPICO", 65),
    ("Provera", "10 mg", "Tabs", "Medroxyprogesterone", "Pfizer", 95),
    ("Depo-Provera", "150 mg/ml", "Vial", "Medroxyprogesterone", "Pfizer", 145),
    ("Hydroxyprogesterone", "250 mg/ml", "Amp", "Hydroxyprogesterone", "EIPICO", 125),
    ("Delalutin", "250 mg/ml", "Amp", "Hydroxyprogesterone", "BMS", 185),
    ("Estradiol", "1 mg", "Tabs", "Estradiol", "EIPICO", 65),
    ("Estradiol", "2 mg", "Tabs", "Estradiol", "EIPICO", 85),
    ("Estrofem", "2 mg", "Tabs", "Estradiol", "Novo Nordisk", 145),
    ("Progynova", "2 mg", "Tabs", "Estradiol", "Bayer", 125),
    ("Estradiol Patch", "50 mcg", "Patch", "Estradiol", "EIPICO", 125),
    ("Estradot", "50 mcg", "Patch", "Estradiol", "Novo Nordisk", 175),
    ("Climara", "50 mcg", "Patch", "Estradiol", "Bayer", 195),
    ("Conjugated Estrogens", "0.3 mg", "Tabs", "Conjugated Estrogens", "EIPICO", 85),
    ("Conjugated Estrogens", "0.625 mg", "Tabs", "Conjugated Estrogens", "EIPICO", 125),
    ("Premarin", "0.625 mg", "Tabs", "Conjugated Estrogens", "Pfizer", 175),
    ("Estradiol/Norgestimate", "1/0.09 mg", "Tabs", "Estradiol/Norgestimate", "EIPICO", 95),
    ("Prefest", "1/0.09 mg", "Tabs", "Estradiol/Norgestimate", "Pfizer", 145),
    ("Estradiol/Drospirenone", "1/2 mg", "Tabs", "Estradiol/Drospirenone", "EIPICO", 125),
    ("Angeliq", "1/2 mg", "Tabs", "Estradiol/Drospirenone", "Bayer", 195),
    ("Ethinylestradiol", "0.02 mg", "Tabs", "Ethinylestradiol", "EIPICO", 45),
    ("Clomiphene", "50 mg", "Tabs", "Clomiphene", "EIPICO", 65),
    ("Clomiphene", "100 mg", "Tabs", "Clomiphene", "EIPICO", 95),
    ("Clomid", "50 mg", "Tabs", "Clomiphene", "Sanofi", 95),
    ("Serophene", "50 mg", "Tabs", "Clomiphene", "Merck", 115),
    ("Tamoxifen", "10 mg", "Tabs", "Tamoxifen", "EIPICO", 45),
    ("Tamoxifen", "20 mg", "Tabs", "Tamoxifen", "EIPICO", 65),
    ("Nolvadex", "20 mg", "Tabs", "Tamoxifen", "AstraZeneca", 125),
    ("Fulvestrant", "250 mg/5ml", "Pre-filled", "Fulvestrant", "EIPICO", 685),
    ("Faslodex", "250 mg/5ml", "Pre-filled", "Fulvestrant", "AstraZeneca", 1085),
    ("Raloxifene", "60 mg", "Tabs", "Raloxifene", "EIPICO", 145),
    ("Evista", "60 mg", "Tabs", "Raloxifene", "Lilly", 245),
    ("Bazedoxifene", "20 mg", "Tabs", "Bazedoxifene", "EIPICO", 185),
    ("Viviant", "20 mg", "Tabs", "Bazedoxifene", "Pfizer", 285),
    ("Lasofoxifene", "0.25 mg", "Tabs", "Lasofoxifene", "EIPICO", 225),
    ("Fablyn", "0.25 mg", "Tabs", "Lasofoxifene", "Pfizer", 345),
    ("Ospemifene", "60 mg", "Tabs", "Ospemifene", "EIPICO", 285),
    ("Osphena", "60 mg", "Tabs", "Ospemifene", "Shionogi", 425),
    ("Toremifene", "60 mg", "Tabs", "Toremifene", "EIPICO", 185),
    ("Fareston", "60 mg", "Tabs", "Toremifene", "GTX", 285),
    ("Cabergoline", "0.5 mg", "Tabs", "Cabergoline", "EIPICO", 145),
    ("Dostinex", "0.5 mg", "Tabs", "Cabergoline", "Pfizer", 225),
    ("Bromocriptine", "2.5 mg", "Tabs", "Bromocriptine", "EIPICO", 95),
    ("Bromocriptine", "5 mg", "Tabs", "Bromocriptine", "EIPICO", 145),
    ("Parlodel", "2.5 mg", "Tabs", "Bromocriptine", "Novartis", 145),
    ("Pergolide", "0.05 mg", "Tabs", "Pergolide", "EIPICO", 125),
    ("Permax", "0.05 mg", "Tabs", "Pergolide", "Eli Lilly", 185),
    ("Quinagolide", "0.075 mg", "Tabs", "Quinagolide", "EIPICO", 175),
    ("Norprolac", "0.075 mg", "Tabs", "Quinagolide", "Ferring", 265),
    ("Octreotide", "0.1 mg/ml", "Amp", "Octreotide", "EIPICO", 225),
    ("Sandostatin", "0.1 mg/ml", "Amp", "Octreotide", "Novartis", 345),
    ("Lanreotide", "60 mg", "Pre-filled", "Lanreotide", "EIPICO", 485),
    ("Somatuline", "60 mg", "Pre-filled", "Lanreotide", "Ipsen", 685),
    ("Pasireotide", "0.6 mg/ml", "Amp", "Pasireotide", "EIPICO", 585),
    ("Signifor", "0.6 mg/ml", "Amp", "Pasireotide", "Novartis", 885),
    ("Somatropin", "4 IU", "Vial", "Somatropin", "EIPICO", 425),
    ("Somatropin", "10 IU", "Vial", "Somatropin", "EIPICO", 785),
    ("Genotropin", "12 mg", "Pen", "Somatropin", "Pfizer", 1285),
    ("Humatrope", "6 mg", "Vial", "Somatropin", "Lilly", 785),
    ("Norditropin", "5 mg/1.5ml", "Pen", "Somatropin", "Novo Nordisk", 885),
    ("Saizen", "8 mg", "Vial", "Somatropin", "Merck", 985),
    ("Serostim", "6 mg", "Vial", "Somatropin", "Merck", 1185),
    ("Oxytocin", "5 IU/ml", "Amp", "Oxytocin", "EIPICO", 35),
    ("Oxytocin", "10 IU/ml", "Amp", "Oxytocin", "EIPICO", 45),
    ("Syntocinon", "10 IU/ml", "Amp", "Oxytocin", "Novartis", 75),
    ("Pitocin", "10 IU/ml", "Amp", "Oxytocin", "Pfizer", 95),
    ("Dinoprostone", "0.5 mg", "Gel", "Dinoprostone", "EIPICO", 125),
    ("Cervidil", "10 mg", "Vaginal", "Dinoprostone", "Ferring", 225),
    ("Misoprostol", "200 mcg", "Tabs", "Misoprostol", "EIPICO", 45),
    ("Cytotec", "200 mcg", "Tabs", "Misoprostol", "Pfizer", 75),
    ("Mifepristone", "200 mg", "Tabs", "Mifepristone", "EIPICO", 185),
    ("Mifegyne", "200 mg", "Tabs", "Mifepristone", "Exelgyn", 285),
    ("Carbetocin", "100 mcg/ml", "Amp", "Carbetocin", "EIPICO", 125),
    ("Pabal", "100 mcg/ml", "Amp", "Carbetocin", "Ferring", 185),
    
    # Bone Health - Osteoporosis
    ("Alendronate", "5 mg", "Tabs", "Alendronate", "EIPICO", 65),
    ("Alendronate", "10 mg", "Tabs", "Alendronate", "EIPICO", 95),
    ("Alendronate", "70 mg", "Tabs", "Alendronate", "EIPICO", 125),
    ("Fosamax", "70 mg", "Tabs", "Alendronate", "MSD", 185),
    ("Fosamax Plus", "70/5600 IU", "Tabs", "Alendronate/Vitamin D3", "MSD", 225),
    ("Risedronate", "5 mg", "Tabs", "Risedronate", "EIPICO", 75),
    ("Risedronate", "35 mg", "Tabs", "Risedronate", "EIPICO", 145),
    ("Actonel", "35 mg", "Tabs", "Risedronate", "Sanofi", 225),
    ("Ibandronate", "2.5 mg", "Tabs", "Ibandronate", "EIPICO", 95),
    ("Ibandronate", "150 mg", "Tabs", "Ibandronate", "EIPICO", 165),
    ("Boniva", "150 mg", "Tabs", "Ibandronate", "Roche", 245),
    ("Zoledronate", "4 mg", "Vial", "Zoledronate", "EIPICO", 285),
    ("Aclasta", "5 mg/100ml", "Infusion", "Zoledronate", "Novartis", 485),
    ("Reclast", "5 mg/100ml", "Infusion", "Zoledronate", "Novartis", 585),
    ("Pamidronate", "30 mg", "Vial", "Pamidronate", "EIPICO", 325),
    ("Pamidronate", "60 mg", "Vial", "Pamidronate", "EIPICO", 485),
    ("Aredia", "60 mg", "Vial", "Pamidronate", "Novartis", 685),
    ("Clodronate", "400 mg", "Caps", "Clodronate", "EIPICO", 145),
    ("Clodronate", "800 mg", "Caps", "Clodronate", "EIPICO", 225),
    ("Bonefos", "800 mg", "Caps", "Clodronate", "Bayer", 325),
    ("Etidronate", "200 mg", "Tabs", "Etidronate", "EIPICO", 85),
    ("Etidronate", "400 mg", "Tabs", "Etidronate", "EIPICO", 125),
    ("Didronel", "400 mg", "Tabs", "Etidronate", "Sanofi", 185),
    ("Tiludronate", "200 mg", "Tabs", "Tiludronate", "EIPICO", 125),
    ("Skelid", "200 mg", "Tabs", "Tiludronate", "Sanofi", 195),
    ("Calcitonin", "100 IU", "Nasal Spray", "Calcitonin", "EIPICO", 125),
    ("Miacalcic", "100 IU", "Nasal Spray", "Calcitonin", "Novartis", 195),
    ("Calcitonin", "50 IU/ml", "Amp", "Calcitonin", "EIPICO", 85),
    ("Miacalcic", "50 IU/ml", "Amp", "Calcitonin", "Novartis", 135),
    ("Teriparatide", "20 mcg/80ml", "Pen", "Teriparatide", "EIPICO", 885),
    ("Forsteo", "20 mcg/80ml", "Pen", "Teriparatide", "Lilly", 1285),
    ("Abaloparatide", "80 mcg", "Pen", "Abaloparatide", "EIPICO", 985),
    ("Tymlos", "80 mcg", "Pen", "Abaloparatide", "Radius", 1485),
    ("Romosozumab", "105 mg", "Pre-filled", "Romosozumab", "EIPICO", 1285),
    ("Evenity", "105 mg", "Pre-filled", "Romosozumab", "Amgen", 1885),
    ("Denosumab", "60 mg/ml", "Pre-filled", "Denosumab", "EIPICO", 885),
    ("Prolia", "60 mg/ml", "Pre-filled", "Denosumab", "Amgen", 1285),
    ("Denosumab", "120 mg/1.7ml", "Vial", "Denosumab", "EIPICO", 1285),
    ("Xgeva", "120 mg/1.7ml", "Vial", "Denosumab", "Amgen", 1885),
    
    # Fluids & Electrolytes
    ("Oral Rehydration", "WHO Formula", "Sachets", "Oral Rehydration Salts", "EIPICO", 8),
    ("Electrolyte Solution", "Pediatric", "Sachets", "Oral Rehydration Salts", "EIPICO", 10),
    ("Oral Salts", "Lemon Flavor", "Sachets", "Oral Rehydration Salts", "Amoun", 12),
    ("Normal Saline", "0.9%", "500ml", "Sodium Chloride", "EIPICO", 25),
    ("Normal Saline", "0.9%", "1000ml", "Sodium Chloride", "EIPICO", 35),
    ("Dextrose 5%", "5%", "500ml", "Dextrose", "EIPICO", 25),
    ("Dextrose 5%", "5%", "1000ml", "Dextrose", "EIPICO", 35),
    ("Dextrose 10%", "10%", "500ml", "Dextrose", "EIPICO", 35),
    ("Dextrose 50%", "50%", "50ml", "Dextrose", "EIPICO", 25),
    ("Ringer Lactate", "Hartmann", "500ml", "Ringer Lactate", "EIPICO", 35),
    ("Ringer Lactate", "Hartmann", "1000ml", "Ringer Lactate", "EIPICO", 45),
    ("Hartmann Solution", "Compound", "500ml", "Sodium Lactate", "EIPICO", 45),
    ("Plasma-Lyte", "Multiple", "500ml", "Multiple Electrolytes", "EIPICO", 65),
    ("Plasma-Lyte", "Multiple", "1000ml", "Multiple Electrolytes", "EIPICO", 95),
    ("Potassium Chloride", "20%", "Amp", "Potassium Chloride", "EIPICO", 15),
    ("Potassium Chloride", "7.45%", "Syrup", "Potassium Chloride", "EIPICO", 25),
    ("Calcium Gluconate", "10%", "Amp", "Calcium Gluconate", "EIPICO", 25),
    ("Calcium Gluconate", "10%", "Syrup", "Calcium Gluconate", "EIPICO", 35),
    ("Calcium Sandoz", "500 mg", "Effervescent", "Calcium Carbonate", "Novartis", 65),
    ("Calcium Carbonate", "1250 mg", "Chewable", "Calcium Carbonate", "EIPICO", 45),
    ("Magnesium Sulfate", "50%", "Amp", "Magnesium Sulfate", "EIPICO", 15),
    ("Magnesium Sulfate", "20%", "Amp", "Magnesium Sulfate", "EIPICO", 12),
    ("Zinc Sulfate", "220 mg", "Tabs", "Zinc Sulfate", "EIPICO", 25),
    ("Zinc", "20 mg", "Syrup", "Zinc Sulfate", "EIPICO", 35),
    ("Zinc", "10 mg/5ml", "Syrup", "Zinc Sulfate", "Amoun", 25),
    ("Iron Sucrose", "100 mg/5ml", "Vial", "Iron Sucrose", "EIPICO", 65),
    ("Venofer", "100 mg/5ml", "Vial", "Iron Sucrose", "Vifor", 95),
    ("Ferric Carboxymaltose", "500 mg/10ml", "Vial", "Ferric Carboxymaltose", "EIPICO", 145),
    ("Injectafer", "500 mg/10ml", "Vial", "Ferric Carboxymaltose", "American Regent", 225),
    ("Sodium Bicarbonate", "8.4%", "50ml", "Sodium Bicarbonate", "EIPICO", 25),
    ("Sodium Bicarbonate", "500 mg", "Tabs", "Sodium Bicarbonate", "EIPICO", 15),
    ("Ammonium Chloride", "10%", "Syrup", "Ammonium Chloride", "EIPICO", 25),
    ("Mannitol", "20%", "500ml", "Mannitol", "EIPICO", 65),
    ("Mannitol", "10%", "500ml", "Mannitol", "EIPICO", 55),
    ("Glycerol", "10%", "Syrup", "Glycerol", "EIPICO", 35),
    
    # Eye Preparations
    ("Artificial Tears", "Lubricating", "Drops", "Carboxymethyl Cellulose", "EIPICO", 25),
    ("Refresh Tears", "Lubricating", "Drops", "Polyvinyl Alcohol", "Abbott", 45),
    ("Systane", "Lubricating", "Drops", "Polyethylene Glycol", "Alcon", 65),
    ("Visine", "Redness Relief", "Drops", "Tetrahydrozoline", "J&J", 35),
    ("Naphcon-A", "Antihistamine", "Drops", "Naphazoline", "Alcon", 45),
    ("Opcon-A", "Antihistamine", "Drops", "Naphazoline/Pheniramine", "Bausch", 55),
    ("Cromolyn Eye", "4%", "Drops", "Sodium Cromoglycate", "EIPICO", 45),
    ("Opticrom", "2%", "Drops", "Sodium Cromoglycate", "Sanofi", 65),
    ("Olopatadine", "0.1%", "Drops", "Olopatadine", "EIPICO", 65),
    ("Olopatadine", "0.2%", "Drops", "Olopatadine", "EIPICO", 95),
    ("Patanol", "0.1%", "Drops", "Olopatadine", "Alcon", 95),
    ("Pataday", "0.2%", "Drops", "Olopatadine", "Alcon", 135),
    ("Azelastine Eye", "0.05%", "Drops", "Azelastine", "EIPICO", 75),
    ("Optivar", "0.05%", "Drops", "Azelastine", "Meda", 115),
    ("Ketotifen Eye", "0.025%", "Drops", "Ketotifen", "EIPICO", 55),
    ("Zaditor", "0.025%", "Drops", "Ketotifen", "Alcon", 85),
    ("Alcaftadine", "0.25%", "Drops", "Alcaftadine", "EIPICO", 85),
    ("Lastacaft", "0.25%", "Drops", "Alcaftadine", "Allergan", 135),
    ("Epinastine", "0.05%", "Drops", "Epinastine", "EIPICO", 65),
    ("Elestat", "0.05%", "Drops", "Epinastine", "Allergan", 115),
    ("Bepotastine", "1.5%", "Drops", "Bepotastine", "EIPICO", 95),
    ("Bepreve", "1.5%", "Drops", "Bepotastine", "Bausch", 145),
    ("Loteprednol", "0.5%", "Susp", "Loteprednol", "EIPICO", 85),
    ("Lotemax", "0.5%", "Susp", "Loteprednol", "Bausch", 135),
    ("Alrex", "0.2%", "Susp", "Loteprednol", "Bausch", 115),
    ("Pred Forte", "1%", "Susp", "Prednisolone", "Allergan", 95),
    ("Pred Mild", "0.12%", "Susp", "Prednisolone", "Allergan", 85),
    ("Fluorometholone", "0.1%", "Susp", "Fluorometholone", "EIPICO", 65),
    ("FML", "0.1%", "Susp", "Fluorometholone", "Allergan", 105),
    ("FML Forte", "0.25%", "Susp", "Fluorometholone", "Allergan", 125),
    ("Rimexolone", "1%", "Susp", "Rimexolone", "EIPICO", 95),
    ("Vexol", "1%", "Susp", "Rimexolone", "Alcon", 145),
    ("Difluprednate", "0.05%", "Emulsion", "Difluprednate", "EIPICO", 125),
    ("Durezol", "0.05%", "Emulsion", "Difluprednate", "Alcon", 185),
    ("Dexamethasone Eye", "0.1%", "Susp", "Dexamethasone", "EIPICO", 45),
    ("Maxidex", "0.1%", "Susp", "Dexamethasone", "Alcon", 75),
    ("Tobradex", "0.3%/0.1%", "Susp", "Tobramycin/Dexamethasone", "Alcon", 95),
    ("Tobradex", "0.3%/0.1%", "Oint", "Tobramycin/Dexamethasone", "Alcon", 85),
    ("Maxitrol", "Oint", "Oint", "Neomycin/Polymyxin/Dexamethasone", "Alcon", 75),
    ("Neosporin Eye", "Oint", "Oint", "Bacitracin/Neomycin/Polymyxin", "J&J", 55),
    ("Polytrim", "Solution", "Drops", "Polymyxin B/Trimethoprim", "Allergan", 65),
    ("Ciprofloxacin Eye", "0.3%", "Drops", "Ciprofloxacin", "EIPICO", 45),
    ("Ciloxan", "0.3%", "Drops", "Ciprofloxacin", "Alcon", 75),
    ("Ciloxan", "0.3%", "Oint", "Ciprofloxacin", "Alcon", 65),
    ("Ofloxacin Eye", "0.3%", "Drops", "Ofloxacin", "EIPICO", 45),
    ("Ocuflox", "0.3%", "Drops", "Ofloxacin", "Allergan", 75),
    ("Levofloxacin Eye", "0.5%", "Drops", "Levofloxacin", "EIPICO", 55),
    ("Quixin", "0.5%", "Drops", "Levofloxacin", "Santen", 95),
    ("Iquix", "1.5%", "Drops", "Levofloxacin", "Santen", 115),
    ("Moxifloxacin Eye", "0.5%", "Drops", "Moxifloxacin", "EIPICO", 65),
    ("Vigamox", "0.5%", "Drops", "Moxifloxacin", "Alcon", 105),
    ("Besifloxacin", "0.6%", "Susp", "Besifloxacin", "EIPICO", 85),
    ("Besivance", "0.6%", "Susp", "Besifloxacin", "Bausch", 135),
    ("Gatifloxacin Eye", "0.3%", "Drops", "Gatifloxacin", "EIPICO", 55),
    ("Zymaxid", "0.3%", "Drops", "Gatifloxacin", "Allergan", 95),
    ("Gentamicin Eye", "0.3%", "Drops", "Gentamicin", "EIPICO", 35),
    ("Gentamicin Eye", "0.3%", "Oint", "Gentamicin", "EIPICO", 35),
    ("Garamycin Eye", "0.3%", "Drops", "Gentamicin", "Schering", 65),
    ("Tobramycin Eye", "0.3%", "Drops", "Tobramycin", "EIPICO", 35),
    ("Tobramycin Eye", "0.3%", "Oint", "Tobramycin", "EIPICO", 35),
    ("Tobrex", "0.3%", "Drops", "Tobramycin", "Alcon", 65),
    ("Tobrex", "0.3%", "Oint", "Tobramycin", "Alcon", 65),
    ("Neomycin Eye", "Oint", "Oint", "Neomycin", "EIPICO", 25),
    ("Natacyn", "5%", "Susp", "Natamycin", "Alcon", 185),
    ("Amphotericin B Eye", "0.25%", "Susp", "Amphotericin B", "EIPICO", 125),
    ("Voriconazole Eye", "1%", "Drops", "Voriconazole", "EIPICO", 185),
    ("Acyclovir Eye", "3%", "Oint", "Acyclovir", "EIPICO", 65),
    ("Zirgan", "0.15%", "Gel", "Ganciclovir", "Bausch", 145),
    ("Trifluridine", "1%", "Drops", "Trifluridine", "EIPICO", 125),
    ("Viroptic", "1%", "Drops", "Trifluridine", "Bausch", 185),
    ("Idoxuridine", "0.1%", "Drops", "Idoxuridine", "EIPICO", 85),
    ("Herplex", "0.1%", "Drops", "Idoxuridine", "Allergan", 125),
    ("Timolol Eye", "0.25%", "Drops", "Timolol", "EIPICO", 45),
    ("Timolol Eye", "0.5%", "Drops", "Timolol", "EIPICO", 55),
    ("Timoptic", "0.5%", "Drops", "Timolol", "Bausch", 95),
    ("Timoptic XE", "0.5%", "Gel", "Timolol", "Bausch", 115),
    ("Betaxolol Eye", "0.5%", "Susp", "Betaxolol", "EIPICO", 65),
    ("Betoptic", "0.5%", "Susp", "Betaxolol", "Alcon", 105),
    ("Betoptic S", "0.25%", "Susp", "Betaxolol", "Alcon", 95),
    ("Levobunolol", "0.5%", "Drops", "Levobunolol", "EIPICO", 55),
    ("Betagan", "0.5%", "Drops", "Levobunolol", "Allergan", 95),
    ("Metipranolol Eye", "0.3%", "Drops", "Metipranolol", "EIPICO", 45),
    ("OptiPranolol", "0.3%", "Drops", "Metipranolol", "Bausch", 85),
    ("Carteolol Eye", "1%", "Drops", "Carteolol", "EIPICO", 45),
    ("Ocupress", "1%", "Drops", "Carteolol", "Novartis", 85),
    ("Dorzolamide", "2%", "Drops", "Dorzolamide", "EIPICO", 75),
    ("Trusopt", "2%", "Drops", "Dorzolamide", "Merck", 125),
    ("Brinzolamide", "1%", "Susp", "Brinzolamide", "EIPICO", 85),
    ("Azopt", "1%", "Susp", "Brinzolamide", "Alcon", 145),
    ("Acetazolamide", "250 mg", "Tabs", "Acetazolamide", "EIPICO", 55),
    ("Diamox", "250 mg", "Tabs", "Acetazolamide", "Vifor", 95),
    ("Methazolamide", "25 mg", "Tabs", "Methazolamide", "EIPICO", 125),
    ("Neptazane", "25 mg", "Tabs", "Methazolamide", "Fera", 185),
    ("Brimonidine", "0.2%", "Drops", "Brimonidine", "EIPICO", 75),
    ("Alphagan", "0.2%", "Drops", "Brimonidine", "Allergan", 125),
    ("Alphagan P", "0.15%", "Drops", "Brimonidine", "Allergan", 135),
    ("Apraclonidine", "0.5%", "Drops", "Apraclonidine", "EIPICO", 95),
    ("Iopidine", "0.5%", "Drops", "Apraclonidine", "Alcon", 155),
    ("Dipivefrin", "0.1%", "Drops", "Dipivefrin", "EIPICO", 65),
    ("Propine", "0.1%", "Drops", "Dipivefrin", "Allergan", 105),
    ("Latanoprost", "0.005%", "Drops", "Latanoprost", "EIPICO", 85),
    ("Xalatan", "0.005%", "Drops", "Latanoprost", "Pfizer", 145),
    ("Travoprost", "0.004%", "Drops", "Travoprost", "EIPICO", 95),
    ("Travatan", "0.004%", "Drops", "Travoprost", "Alcon", 165),
    ("Travatan Z", "0.004%", "Drops", "Travoprost", "Alcon", 175),
    ("Bimatoprost", "0.03%", "Drops", "Bimatoprost", "EIPICO", 95),
    ("Lumigan", "0.01%", "Drops", "Bimatoprost", "Allergan", 165),
    ("Lumigan RC", "0.01%", "Drops", "Bimatoprost", "Allergan", 175),
    ("Latisse", "0.03%", "Drops", "Bimatoprost", "Allergan", 185),
    ("Tafluprost", "0.0015%", "Drops", "Tafluprost", "EIPICO", 125),
    ("Zioptan", "0.0015%", "Drops", "Tafluprost", "Merck", 215),
    ("Unoprostone", "0.15%", "Drops", "Unoprostone", "EIPICO", 105),
    ("Rescula", "0.15%", "Drops", "Unoprostone", "Novartis", 175),
    ("Pilocarpine Eye", "1%", "Drops", "Pilocarpine", "EIPICO", 45),
    ("Pilocarpine Eye", "2%", "Drops", "Pilocarpine", "EIPICO", 55),
    ("Isopto Carpine", "2%", "Drops", "Pilocarpine", "Alcon", 95),
    ("Carbachol Eye", "0.01%", "Drops", "Carbachol", "EIPICO", 55),
    ("Isopto Carbachol", "1.5%", "Drops", "Carbachol", "Alcon", 95),
    ("Physostigmine Eye", "0.25%", "Oint", "Physostigmine", "EIPICO", 65),
    ("Eserine", "0.25%", "Oint", "Physostigmine", "Pharmascience", 105),
    ("Echothiophate", "0.125%", "Drops", "Echothiophate", "EIPICO", 125),
    ("Phospholine Iodide", "0.125%", "Drops", "Echothiophate", "Wyeth", 185),
    ("Atropine Eye", "1%", "Drops", "Atropine", "EIPICO", 35),
    ("Atropine Eye", "1%", "Oint", "Atropine", "EIPICO", 35),
    ("Isopto Atropine", "1%", "Drops", "Atropine", "Alcon", 75),
    ("Homatropine Eye", "5%", "Drops", "Homatropine", "EIPICO", 35),
    ("Isopto Homatropine", "5%", "Drops", "Homatropine", "Alcon", 75),
    ("Cyclopentolate", "1%", "Drops", "Cyclopentolate", "EIPICO", 35),
    ("Cyclogyl", "1%", "Drops", "Cyclopentolate", "Alcon", 75),
    ("Cyclogyl", "2%", "Drops", "Cyclopentolate", "Alcon", 85),
    ("Tropicamide", "0.5%", "Drops", "Tropicamide", "EIPICO", 25),
    ("Tropicamide", "1%", "Drops", "Tropicamide", "EIPICO", 35),
    ("Mydriacyl", "1%", "Drops", "Tropicamide", "Alcon", 65),
    ("Phenylephrine Eye", "2.5%", "Drops", "Phenylephrine", "EIPICO", 25),
    ("Phenylephrine Eye", "10%", "Drops", "Phenylephrine", "EIPICO", 35),
    ("Mydfrin", "2.5%", "Drops", "Phenylephrine", "Alcon", 55),
    ("Paremyd", "0.25%/1%", "Drops", "Hydroxyamphetamine/Tropicamide", "Akorn", 95),
    ("Scopolamine Eye", "0.25%", "Drops", "Scopolamine", "EIPICO", 45),
    ("Isopto Hyoscine", "0.25%", "Drops", "Scopolamine", "Alcon", 85),
    ("Dapiprazole", "0.5%", "Drops", "Dapiprazole", "EIPICO", 85),
    ("Rev-Eyes", "0.5%", "Drops", "Dapiprazole", "Angelini", 145),
    ("Fluorescein", "2%", "Strips", "Fluorescein", "EIPICO", 35),
    ("Fluorescein", "10%", "Drops", "Fluorescein", "EIPICO", 45),
    ("Fluorescein", "25%", "Amp", "Fluorescein", "EIPICO", 55),
    ("Fluorets", "1 mg", "Strips", "Fluorescein", "Bausch", 65),
    ("Rose Bengal", "1%", "Drops", "Rose Bengal", "EIPICO", 45),
    ("Lissamine Green", "1%", "Strips", "Lissamine Green", "EIPICO", 55),
    ("Proparacaine", "0.5%", "Drops", "Proparacaine", "EIPICO", 45),
    ("Alcaine", "0.5%", "Drops", "Proparacaine", "Alcon", 75),
    ("Tetracaine Eye", "0.5%", "Drops", "Tetracaine", "EIPICO", 35),
    ("Pontocaine", "0.5%", "Drops", "Tetracaine", "Bausch", 65),
    ("Oxybuprocaine", "0.4%", "Drops", "Oxybuprocaine", "EIPICO", 55),
    ("Novesine", "0.4%", "Drops", "Oxybuprocaine", "Novartis", 95),
    ("Proxymetacaine", "0.5%", "Drops", "Proxymetacaine", "EIPICO", 45),
    ("Ophthaine", "0.5%", "Drops", "Proxymetacaine", "Novartis", 85),
    ("Benoxinate", "0.4%", "Drops", "Benoxinate", "EIPICO", 55),
    ("Fluress", "0.4%", "Drops", "Benoxinate/Fluorescein", "Akorn", 95),
    ("Acetylcysteine Eye", "10%", "Drops", "Acetylcysteine", "EIPICO", 65),
    ("Mucomyst Eye", "10%", "Drops", "Acetylcysteine", "Bristol", 105),
    ("Povidone-Iodine", "5%", "Drops", "Povidone-Iodine", "EIPICO", 35),
    ("Betadine Eye", "5%", "Drops", "Povidone-Iodine", "Alcon", 65),
    ("Silver Nitrate", "1%", "Drops", "Silver Nitrate", "EIPICO", 25),
    ("Silver Nitrate", "10%", "Sticks", "Silver Nitrate", "EIPICO", 35),
    ("Chloramphenicol Eye", "0.5%", "Drops", "Chloramphenicol", "EIPICO", 25),
    ("Chloramphenicol Eye", "1%", "Oint", "Chloramphenicol", "EIPICO", 25),
    ("Chloromycetin Eye", "1%", "Oint", "Chloramphenicol", "Pfizer", 55),
    ("Fucithalmic", "1%", "Gel", "Fusidic Acid", "LEO", 85),
    ("Rifamycin Eye", "1%", "Drops", "Rifamycin", "EIPICO", 55),
    ("Monotril", "1%", "Drops", "Rifamycin", "Zambon", 95),
    ("Colistimethate Eye", "1 MU", "Drops", "Colistimethate", "EIPICO", 125),
    ("Polyfax", "Oint", "Oint", "Polymyxin B/Bacitracin", "BGP", 55),
    ("Brolene", "0.1%", "Drops", "Propamidine", "Sanofi", 65),
    ("Dibromopropamidine", "0.15%", "Oint", "Dibromopropamidine", "EIPICO", 55),
    ("Clodronate Eye", "0.3%", "Drops", "Clodronate", "EIPICO", 125),
    ("Hyaluronic Acid Eye", "0.15%", "Drops", "Hyaluronic Acid", "EIPICO", 85),
    ("Hyabak", "0.15%", "Drops", "Hyaluronic Acid", "Thea", 145),
    ("Hylocomod", "0.1%", "Drops", "Hyaluronic Acid", "Bausch", 125),
    ("Hylocomod Forte", "0.3%", "Drops", "Hyaluronic Acid", "Bausch", 165),
    ("Carbomer Eye", "0.2%", "Gel", "Carbomer", "EIPICO", 75),
    ("GelTears", "0.2%", "Gel", "Carbomer", "Bausch", 125),
    ("Liposic", "0.2%", "Gel", "Carbomer", "Bausch", 115),
    ("Polyethylene Glycol", "0.4%/0.3%", "Drops", "PEG/PG", "EIPICO", 65),
    ("Systane Ultra", "Drops", "Drops", "PEG/PG", "Alcon", 115),
    ("Systane Balance", "Emulsion", "Drops", "Mineral Oil", "Alcon", 125),
    ("Systane Complete", "Drops", "Drops", "Nano-droplets", "Alcon", 135),
    ("Refresh Optive", "Drops", "Drops", "Carboxymethyl/CMC", "Abbott", 95),
    ("Refresh Optive Advanced", "Drops", "Drops", "CMC/Flaxseed", "Abbott", 115),
    ("Refresh Optive Mega-3", "Drops", "Drops", "Flaxseed/OM3", "Abbott", 145),
    ("Refresh Tears", "Drops", "Drops", "Polyvinyl Alcohol", "Abbott", 55),
    ("Refresh Relieva", "Drops", "Drops", "Carboxymethyl/CMC", "Abbott", 105),
    ("Refresh Relieva PF", "Drops", "Drops", "Preservative Free", "Abbott", 125),
    ("Refresh Endura", "Emulsion", "Drops", "Mineral Oil", "Abbott", 115),
    ("Refresh Celluvisc", "1%", "Drops", "CMC", "Abbott", 85),
    ("TheraTears", "0.25%", "Drops", "Sodium Carboxymethyl", "Akorn", 95),
    ("Blink Tears", "0.25%", "Drops", "Polyethylene Glycol", "Abbott", 85),
    ("Blink Contacts", "Drops", "Drops", "Ocupure", "Abbott", 75),
    ("Blink Gel Tears", "0.25%", "Gel", "PEG", "Abbott", 95),
    ("Blink-N-Clean", "Drops", "Drops", "Lens Care", "Abbott", 65),
    ("Rohto Dry-Aid", "Drops", "Drops", "Lubricating", "Rohto", 85),
    ("Rohto Cool", "Drops", "Drops", "Cooling", "Rohto", 95),
    ("Rohto Max Strength", "Drops", "Drops", "Redness Relief", "Rohto", 105),
    ("Rohto All-In-One", "Drops", "Drops", "Multi-Action", "Rohto", 115),
    ("Clear Eyes", "Drops", "Drops", "Naphazoline", "Prestige", 45),
    ("Clear Eyes Redness", "Drops", "Drops", "Naphazoline", "Prestige", 55),
    ("Clear Eyes Maximum", "Drops", "Drops", "Naphazoline", "Prestige", 65),
    ("Visine Original", "Drops", "Drops", "Tetrahydrozoline", "J&J", 45),
    ("Visine Advanced", "Drops", "Drops", "Tetrahydrozoline", "J&J", 55),
    ("Visine Tired Eye", "Drops", "Drops", "Lubricating", "J&J", 65),
    ("Visine Multi-Symptom", "Drops", "Drops", "Combination", "J&J", 75),
    ("Visine A", "Drops", "Drops", "Antihistamine", "J&J", 85),
    ("Opcon-A", "Drops", "Drops", "Naphazoline/Pheniramine", "Bausch", 65),
    ("Naphcon-A", "Drops", "Drops", "Naphazoline/Pheniramine", "Alcon", 75),
    ("Naphcon-Forte", "Drops", "Drops", "Naphazoline", "Alcon", 55),
    ("Alaway", "0.025%", "Drops", "Ketotifen", "Bausch", 85),
    ("Zaditor", "0.025%", "Drops", "Ketotifen", "Alcon", 95),
    ("Zyrtec Itchy Eye", "0.025%", "Drops", "Ketotifen", "J&J", 105),
    ("Claritin Eye", "0.025%", "Drops", "Ketotifen", "Bayer", 115),
    ("Similasan Allergy Eye", "Drops", "Drops", "Natural", "Similasan", 95),
    ("Similasan Dry Eye", "Drops", "Drops", "Natural", "Similasan", 95),
    ("Similasan Computer Eye", "Drops", "Drops", "Natural", "Similasan", 95),
    ("Similasan Pink Eye", "Drops", "Drops", "Natural", "Similasan", 95),
    ("Similasan Stye Eye", "Drops", "Drops", "Natural", "Similasan", 95),
    ("Bausch + Lomb Advanced", "Drops", "Drops", "Polyquad", "Bausch", 75),
    ("Renu MultiPlus", "Drops", "Drops", "Lens Care", "Bausch", 65),
    ("Biotrue Drops", "Drops", "Drops", "Hyaluronan", "Bausch", 85),
    ("Lacri-Lube", "Oint", "Oint", "Lubricating", "Allergan", 55),
    ("Refresh PM", "Oint", "Oint", "Lubricating", "Abbott", 65),
    ("Refresh Lacri-Lube", "Oint", "Oint", "Lubricating", "Abbott", 75),
    ("Puralube", "Oint", "Oint", "Petrolatum", "Bausch", 45),
    ("GenTeal Gel", "0.3%", "Gel", "Hydroxypropyl", "Alcon", 85),
    ("GenTeal Tears", "0.3%", "Drops", "Hydroxypropyl", "Alcon", 75),
    ("GenTeal Mild", "0.3%", "Drops", "Hydroxypropyl", "Alcon", 65),
    ("GenTeal PF", "Drops", "Drops", "Preservative Free", "Alcon", 95),
    ("Soothe XP", "Emulsion", "Drops", "Mineral Oil", "Bausch", 115),
    ("Soothe Hydration", "Drops", "Drops", "Lubricating", "Bausch", 95),
    ("Soothe Lubricant", "Drops", "Drops", "Lubricating", "Bausch", 85),
    ("TheraTears Nutrition", "Caps", "Caps", "Omega-3", "Akorn", 185),
    ("TheraTears SteriLid", "Foam", "Foam", "Eyelid Cleanser", "Akorn", 95),
    ("TheraTears Nighttime", "Gel", "Gel", "Lubricating", "Akorn", 85),
    ("TheraTears Extra", "Drops", "Drops", "Lubricating", "Akorn", 75),
    ("TheraTears Dry Eye", "Drops", "Drops", "Lubricating", "Akorn", 65),
    ("Ocufresh", "Drops", "Drops", "Lubricating", "EIPICO", 35),
    ("Ocufresh PF", "Drops", "Drops", "Preservative Free", "EIPICO", 55),
    ("Hypromellose", "0.3%", "Drops", "Hypromellose", "EIPICO", 25),
    ("Isopto Tears", "0.5%", "Drops", "Hypromellose", "Alcon", 55),
    ("Tears Naturale", "0.3%", "Drops", "Dextran/Hypromellose", "Alcon", 65),
    ("Tears Naturale II", "0.3%", "Drops", "Dextran/Hypromellose", "Alcon", 75),
    ("Tears Naturale Free", "Drops", "Drops", "Preservative Free", "Alcon", 85),
    ("Optive", "Drops", "Drops", "CMC/Glycerin", "Abbott", 65),
    ("Optive Sensitive", "Drops", "Drops", "Gentle Formula", "Abbott", 75),
    ("Optive Double Action", "Drops", "Drops", "CMC/PEG", "Abbott", 85),
    ("Restasis", "0.05%", "Emulsion", "Cyclosporine", "Allergan", 385),
    ("Restasis MultiDose", "0.05%", "Emulsion", "Cyclosporine", "Allergan", 425),
    ("Xiidra", "5%", "Drops", "Lifitegrast", "Novartis", 485),
    ("Cequa", "0.09%", "Drops", "Cyclosporine", "Sun", 445),
    ("Ikervis", "0.1%", "Drops", "Cyclosporine", "Santen", 485),
    ("Eyesalve", "Oint", "Oint", "Antibiotic", "EIPICO", 45),
    ("Golden Eye", "Drops", "Drops", "Propamidine", "Optrex", 65),
    ("Optrex Infected", "Drops", "Drops", "Chloramphenicol", "Reckitt", 75),
    ("Optrex Red Eyes", "Drops", "Drops", "Naphazoline", "Reckitt", 55),
    ("Optrex Soothing", "Drops", "Drops", "Witch Hazel", "Reckitt", 65),
    ("Optrex Brightening", "Drops", "Drops", "Naphazoline", "Reckitt", 75),
    ("Murine", "Drops", "Drops", "Tetrahydrozoline", "Prestige", 45),
    ("Murine Plus", "Drops", "Drops", "Combination", "Prestige", 55),
    ("Murine Tears", "Drops", "Drops", "Lubricating", "Prestige", 65),
    ("Boiron Optique", "Drops", "Drops", "Homeopathic", "Boiron", 95),
    ("Similasan Eye", "Drops", "Drops", "Homeopathic", "Similasan", 95),
    ("Weleda Eye", "Drops", "Drops", "Homeopathic", "Weleda", 115),
    ("Euphrasia Eye", "Drops", "Drops", "Homeopathic", "Weleda", 125),
    ("Calendula Eye", "Drops", "Drops", "Homeopathic", "Weleda", 125),
]

for drug_data in additional_drugs:
    add_drug(*drug_data)

# Save
output = {"drugs": drugs}
with open('data/egyptian-drugs-gtin-expanded.json', 'w', encoding='utf-8') as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print(f"Total drugs now: {len(drugs)}")
