# -*- coding: utf-8 -*-
"""Expand Egyptian drug database to 2500+ entries"""
import json

# Load current database
with open('data/egyptian-drugs-gtin-expanded.json', 'r', encoding='utf-8') as f:
    existing = json.load(f)

drugs = existing['drugs']
existing_gtins = {d['gtin'] for d in drugs}

counter = len(drugs) + 1

def add_drug(trade_name, strength, form, scientific, company, price):
    global counter
    gtin = f"622200000{counter:04d}"
    while gtin in existing_gtins:
        counter += 1
        gtin = f"622200000{counter:04d}"
    existing_gtins.add(gtin)
    drugs.append({
        "tradeName": trade_name,
        "strength": strength,
        "form": form,
        "scientificName": scientific,
        "company": company,
        "gtin": gtin,
        "price": price
    })
    counter += 1

# 900+ More Egyptian drugs to reach 2500+
additional_drugs = [
    # Oncology - Chemotherapy
    ("Methotrexate", "2.5 mg", "Tabs", "Methotrexate", "EIPICO", 45),
    ("Methotrexate", "10 mg", "Tabs", "Methotrexate", "EIPICO", 85),
    ("Methotrexate", "25 mg/ml", "Vial", "Methotrexate", "EIPICO", 125),
    ("Rheumatrex", "2.5 mg", "Tabs", "Methotrexate", "Stada", 65),
    ("Trexall", "5 mg", "Tabs", "Methotrexate", "Teva", 95),
    ("Cyclophosphamide", "50 mg", "Tabs", "Cyclophosphamide", "EIPICO", 55),
    ("Cyclophosphamide", "200 mg", "Vial", "Cyclophosphamide", "EIPICO", 145),
    ("Cytoxan", "25 mg", "Tabs", "Cyclophosphamide", "BMS", 85),
    ("Cytoxan", "500 mg", "Vial", "Cyclophosphamide", "BMS", 225),
    ("Endoxan", "50 mg", "Tabs", "Cyclophosphamide", "Baxter", 75),
    ("Endoxan", "1 g", "Vial", "Cyclophosphamide", "Baxter", 285),
    ("Fluorouracil", "250 mg/5ml", "Vial", "Fluorouracil", "EIPICO", 125),
    ("Fluorouracil", "500 mg/10ml", "Vial", "Fluorouracil", "EIPICO", 185),
    ("Adrucil", "2.5 g/50ml", "Vial", "Fluorouracil", "Teva", 325),
    ("Efudix", "5%", "Cream", "Fluorouracil", "Medac", 145),
    ("Capecitabine", "150 mg", "Tabs", "Capecitabine", "EIPICO", 225),
    ("Capecitabine", "500 mg", "Tabs", "Capecitabine", "EIPICO", 485),
    ("Xeloda", "150 mg", "Tabs", "Capecitabine", "Roche", 325),
    ("Xeloda", "500 mg", "Tabs", "Capecitabine", "Roche", 685),
    ("Gemcitabine", "200 mg", "Vial", "Gemcitabine", "EIPICO", 425),
    ("Gemcitabine", "1 g", "Vial", "Gemcitabine", "EIPICO", 885),
    ("Gemzar", "200 mg", "Vial", "Gemcitabine", "Lilly", 525),
    ("Gemzar", "1 g", "Vial", "Gemcitabine", "Lilly", 1085),
    ("Paclitaxel", "30 mg/5ml", "Vial", "Paclitaxel", "EIPICO", 425),
    ("Paclitaxel", "100 mg/16.7ml", "Vial", "Paclitaxel", "EIPICO", 925),
    ("Paclitaxel", "300 mg/50ml", "Vial", "Paclitaxel", "EIPICO", 2285),
    ("Taxol", "30 mg/5ml", "Vial", "Paclitaxel", "BMS", 525),
    ("Taxol", "100 mg/16.7ml", "Vial", "Paclitaxel", "BMS", 1125),
    ("Abraxane", "100 mg", "Vial", "Paclitaxel Albumin", "Celgene", 1585),
    ("Docetaxel", "20 mg/0.5ml", "Vial", "Docetaxel", "EIPICO", 385),
    ("Docetaxel", "80 mg/2ml", "Vial", "Docetaxel", "EIPICO", 925),
    ("Taxotere", "20 mg/0.5ml", "Vial", "Docetaxel", "Sanofi", 485),
    ("Taxotere", "80 mg/4ml", "Vial", "Docetaxel", "Sanofi", 1125),
    ("Vincristine", "1 mg/ml", "Vial", "Vincristine", "EIPICO", 225),
    ("Vincristine", "2 mg/2ml", "Vial", "Vincristine", "EIPICO", 385),
    ("Oncovin", "1 mg/ml", "Vial", "Vincristine", "Lilly", 325),
    ("Vinblastine", "10 mg", "Vial", "Vinblastine", "EIPICO", 285),
    ("Velban", "10 mg", "Vial", "Vinblastine", "Lilly", 425),
    ("Vinorelbine", "10 mg/ml", "Vial", "Vinorelbine", "EIPICO", 485),
    ("Vinorelbine", "50 mg/5ml", "Vial", "Vinorelbine", "EIPICO", 1285),
    ("Navelbine", "10 mg/ml", "Vial", "Vinorelbine", "Pierre Fabre", 685),
    ("Navelbine", "50 mg/5ml", "Vial", "Vinorelbine", "Pierre Fabre", 1685),
    ("Etoposide", "20 mg/ml", "Amp", "Etoposide", "EIPICO", 185),
    ("Etoposide", "100 mg/5ml", "Vial", "Etoposide", "EIPICO", 425),
    ("Vepesid", "50 mg", "Caps", "Etoposide", "BMS", 125),
    ("Vepesid", "100 mg/5ml", "Vial", "Etoposide", "BMS", 525),
    ("Irinotecan", "40 mg/2ml", "Vial", "Irinotecan", "EIPICO", 585),
    ("Irinotecan", "100 mg/5ml", "Vial", "Irinotecan", "EIPICO", 1085),
    ("Camptosar", "40 mg/2ml", "Vial", "Irinotecan", "Pfizer", 785),
    ("Camptosar", "100 mg/5ml", "Vial", "Irinotecan", "Pfizer", 1425),
    ("Oxaliplatin", "50 mg", "Vial", "Oxaliplatin", "EIPICO", 685),
    ("Oxaliplatin", "100 mg", "Vial", "Oxaliplatin", "EIPICO", 1185),
    ("Eloxatin", "50 mg", "Vial", "Oxaliplatin", "Sanofi", 885),
    ("Eloxatin", "100 mg", "Vial", "Oxaliplatin", "Sanofi", 1525),
    ("Carboplatin", "150 mg", "Vial", "Carboplatin", "EIPICO", 425),
    ("Carboplatin", "450 mg", "Vial", "Carboplatin", "EIPICO", 985),
    ("Paraplatin", "150 mg", "Vial", "Carboplatin", "BMS", 585),
    ("Paraplatin", "450 mg", "Vial", "Carboplatin", "BMS", 1285),
    ("Cisplatin", "10 mg", "Vial", "Cisplatin", "EIPICO", 185),
    ("Cisplatin", "50 mg", "Vial", "Cisplatin", "EIPICO", 485),
    ("Platinol", "10 mg", "Vial", "Cisplatin", "BMS", 285),
    ("Platinol", "50 mg", "Vial", "Cisplatin", "BMS", 685),
    ("Doxorubicin", "10 mg", "Vial", "Doxorubicin", "EIPICO", 225),
    ("Doxorubicin", "50 mg", "Vial", "Doxorubicin", "EIPICO", 785),
    ("Adriamycin", "10 mg", "Vial", "Doxorubicin", "Pfizer", 325),
    ("Adriamycin", "50 mg", "Vial", "Doxorubicin", "Pfizer", 985),
    ("Epirubicin", "10 mg", "Vial", "Epirubicin", "EIPICO", 285),
    ("Epirubicin", "50 mg", "Vial", "Epirubicin", "EIPICO", 885),
    ("Ellence", "10 mg", "Vial", "Epirubicin", "Pfizer", 425),
    ("Ellence", "50 mg", "Vial", "Epirubicin", "Pfizer", 1185),
    ("Daunorubicin", "20 mg", "Vial", "Daunorubicin", "EIPICO", 385),
    ("Cerubidine", "20 mg", "Vial", "Daunorubicin", "Sanofi", 525),
    ("Idarubicin", "5 mg", "Vial", "Idarubicin", "EIPICO", 425),
    ("Idarubicin", "10 mg", "Vial", "Idarubicin", "EIPICO", 685),
    ("Idamycin", "5 mg", "Vial", "Idarubicin", "Pfizer", 585),
    ("Mitomycin", "2 mg", "Vial", "Mitomycin", "EIPICO", 285),
    ("Mitomycin", "10 mg", "Vial", "Mitomycin", "EIPICO", 685),
    ("Mutamycin", "2 mg", "Vial", "Mitomycin", "BMS", 385),
    ("Bleomycin", "15 mg", "Vial", "Bleomycin", "EIPICO", 325),
    ("Blenoxane", "15 mg", "Vial", "Bleomycin", "BMS", 485),
    ("Hydroxyurea", "500 mg", "Caps", "Hydroxyurea", "EIPICO", 125),
    ("Hydrea", "500 mg", "Caps", "Hydroxyurea", "BMS", 185),
    ("Droxia", "200 mg", "Caps", "Hydroxyurea", "BMS", 95),
    ("Droxia", "400 mg", "Caps", "Hydroxyurea", "BMS", 145),
    ("Mercaptopurine", "50 mg", "Tabs", "Mercaptopurine", "EIPICO", 85),
    ("Purinethol", "50 mg", "Tabs", "Mercaptopurine", "Teva", 125),
    ("Thioguanine", "40 mg", "Tabs", "Thioguanine", "EIPICO", 95),
    ("Lanvis", "40 mg", "Tabs", "Thioguanine", "GSK", 145),
    ("Fludarabine", "10 mg", "Vial", "Fludarabine", "EIPICO", 385),
    ("Fludara", "50 mg", "Vial", "Fludarabine", "Bayer", 585),
    ("Cladribine", "10 mg", "Vial", "Cladribine", "EIPICO", 425),
    ("Leustatin", "10 mg", "Vial", "Cladribine", "Janssen", 625),
    ("Cytarabine", "100 mg", "Vial", "Cytarabine", "EIPICO", 185),
    ("Cytarabine", "500 mg", "Vial", "Cytarabine", "EIPICO", 485),
    ("Cytosar", "100 mg", "Vial", "Cytarabine", "Pfizer", 285),
    ("Cytosar", "500 mg", "Vial", "Cytarabine", "Pfizer", 685),
    ("Azacitidine", "100 mg", "Vial", "Azacitidine", "EIPICO", 885),
    ("Vidaza", "100 mg", "Vial", "Azacitidine", "BMS", 1285),
    ("Decitabine", "50 mg", "Vial", "Decitabine", "EIPICO", 685),
    ("Dacogen", "50 mg", "Vial", "Decitabine", "Janssen", 985),
    ("Bortezomib", "3.5 mg", "Vial", "Bortezomib", "EIPICO", 1285),
    ("Velcade", "3.5 mg", "Vial", "Bortezomib", "Janssen", 1885),
    ("Lenalidomide", "5 mg", "Caps", "Lenalidomide", "EIPICO", 885),
    ("Lenalidomide", "10 mg", "Caps", "Lenalidomide", "EIPICO", 1285),
    ("Lenalidomide", "25 mg", "Caps", "Lenalidomide", "EIPICO", 2285),
    ("Revlimid", "5 mg", "Caps", "Lenalidomide", "Celgene", 1285),
    ("Revlimid", "25 mg", "Caps", "Lenalidomide", "Celgene", 3285),
    ("Thalidomide", "50 mg", "Caps", "Thalidomide", "EIPICO", 485),
    ("Thalidomide", "100 mg", "Caps", "Thalidomide", "EIPICO", 785),
    ("Thalomid", "50 mg", "Caps", "Thalidomide", "Celgene", 685),
    ("Pomalidomide", "1 mg", "Caps", "Pomalidomide", "EIPICO", 685),
    ("Pomalidomide", "4 mg", "Caps", "Pomalidomide", "EIPICO", 1285),
    ("Pomalyst", "4 mg", "Caps", "Pomalidomide", "Celgene", 1885),
    ("Imatinib", "100 mg", "Tabs", "Imatinib", "EIPICO", 485),
    ("Imatinib", "400 mg", "Tabs", "Imatinib", "EIPICO", 1285),
    ("Gleevec", "100 mg", "Tabs", "Imatinib", "Novartis", 685),
    ("Gleevec", "400 mg", "Tabs", "Imatinib", "Novartis", 1885),
    ("Dasatinib", "20 mg", "Tabs", "Dasatinib", "EIPICO", 585),
    ("Dasatinib", "100 mg", "Tabs", "Dasatinib", "EIPICO", 1585),
    ("Sprycel", "100 mg", "Tabs", "Dasatinib", "BMS", 2285),
    ("Nilotinib", "150 mg", "Caps", "Nilotinib", "EIPICO", 685),
    ("Nilotinib", "200 mg", "Caps", "Nilotinib", "EIPICO", 885),
    ("Tasigna", "150 mg", "Caps", "Nilotinib", "Novartis", 985),
    ("Tasigna", "200 mg", "Caps", "Nilotinib", "Novartis", 1285),
    ("Sunitinib", "12.5 mg", "Caps", "Sunitinib", "EIPICO", 885),
    ("Sunitinib", "50 mg", "Caps", "Sunitinib", "EIPICO", 2285),
    ("Sutent", "12.5 mg", "Caps", "Sunitinib", "Pfizer", 1285),
    ("Sutent", "50 mg", "Caps", "Sunitinib", "Pfizer", 3285),
    ("Sorafenib", "200 mg", "Tabs", "Sorafenib", "EIPICO", 1285),
    ("Nexavar", "200 mg", "Tabs", "Sorafenib", "Bayer", 2285),
    ("Erlotinib", "100 mg", "Tabs", "Erlotinib", "EIPICO", 885),
    ("Erlotinib", "150 mg", "Tabs", "Erlotinib", "EIPICO", 1185),
    ("Tarceva", "150 mg", "Tabs", "Erlotinib", "Roche", 1885),
    ("Gefitinib", "250 mg", "Tabs", "Gefitinib", "EIPICO", 785),
    ("Iressa", "250 mg", "Tabs", "Gefitinib", "AstraZeneca", 1285),
    ("Lapatinib", "250 mg", "Tabs", "Lapatinib", "EIPICO", 885),
    ("Tykerb", "250 mg", "Tabs", "Lapatinib", "GSK", 1585),
    ("Vemurafenib", "240 mg", "Tabs", "Vemurafenib", "EIPICO", 2285),
    ("Zelboraf", "240 mg", "Tabs", "Vemurafenib", "Roche", 3585),
    ("Crizotinib", "200 mg", "Caps", "Crizotinib", "EIPICO", 1885),
    ("Crizotinib", "250 mg", "Caps", "Crizotinib", "EIPICO", 2285),
    ("Xalkori", "250 mg", "Caps", "Crizotinib", "Pfizer", 3285),
    ("Ruxolitinib", "5 mg", "Tabs", "Ruxolitinib", "EIPICO", 1285),
    ("Ruxolitinib", "20 mg", "Tabs", "Ruxolitinib", "EIPICO", 3285),
    ("Jakafi", "20 mg", "Tabs", "Ruxolitinib", "Novartis", 4885),
    ("Ibrutinib", "140 mg", "Caps", "Ibrutinib", "EIPICO", 985),
    ("Imbruvica", "140 mg", "Caps", "Ibrutinib", "Janssen", 1585),
    ("Idelalisib", "100 mg", "Tabs", "Idelalisib", "EIPICO", 1285),
    ("Idelalisib", "150 mg", "Tabs", "Idelalisib", "EIPICO", 1885),
    ("Zydelig", "150 mg", "Tabs", "Idelalisib", "Gilead", 2885),
    ("Abiraterone", "250 mg", "Tabs", "Abiraterone", "EIPICO", 885),
    ("Zytiga", "250 mg", "Tabs", "Abiraterone", "Janssen", 1285),
    ("Enzalutamide", "40 mg", "Caps", "Enzalutamide", "EIPICO", 885),
    ("Xtandi", "40 mg", "Caps", "Enzalutamide", "Astellas", 1285),
    ("Tamoxifen", "10 mg", "Tabs", "Tamoxifen", "EIPICO", 65),
    ("Tamoxifen", "20 mg", "Tabs", "Tamoxifen", "EIPICO", 95),
    ("Nolvadex", "10 mg", "Tabs", "Tamoxifen", "AstraZeneca", 95),
    ("Nolvadex-D", "20 mg", "Tabs", "Tamoxifen", "AstraZeneca", 145),
    ("Toremifene", "60 mg", "Tabs", "Toremifene", "EIPICO", 185),
    ("Fareston", "60 mg", "Tabs", "Toremifene", "GTX", 285),
    ("Letrozole", "2.5 mg", "Tabs", "Letrozole", "EIPICO", 125),
    ("Femara", "2.5 mg", "Tabs", "Letrozole", "Novartis", 225),
    ("Anastrozole", "1 mg", "Tabs", "Anastrozole", "EIPICO", 95),
    ("Arimidex", "1 mg", "Tabs", "Anastrozole", "AstraZeneca", 185),
    ("Exemestane", "25 mg", "Tabs", "Exemestane", "EIPICO", 125),
    ("Aromasin", "25 mg", "Tabs", "Exemestane", "Pfizer", 225),
    ("Fulvestrant", "50 mg/ml", "Pre-filled", "Fulvestrant", "EIPICO", 685),
    ("Faslodex", "250 mg/5ml", "Pre-filled", "Fulvestrant", "AstraZeneca", 1285),
    ("Leuprorelin", "3.75 mg", "Vial", "Leuprorelin", "EIPICO", 425),
    ("Leuprorelin", "11.25 mg", "Vial", "Leuprorelin", "EIPICO", 985),
    ("Lupron", "3.75 mg", "Vial", "Leuprorelin", "Abbott", 585),
    ("Eligard", "7.5 mg", "Vial", "Leuprorelin", "Tolmar", 685),
    ("Goserelin", "3.6 mg", "Implant", "Goserelin", "EIPICO", 485),
    ("Goserelin", "10.8 mg", "Implant", "Goserelin", "EIPICO", 985),
    ("Zoladex", "3.6 mg", "Implant", "Goserelin", "AstraZeneca", 685),
    ("Zoladex LA", "10.8 mg", "Implant", "Goserelin", "AstraZeneca", 1285),
    ("Degarelix", "80 mg", "Vial", "Degarelix", "EIPICO", 585),
    ("Firmagon", "80 mg", "Vial", "Degarelix", "Ferring", 885),
    ("Triptorelin", "3.75 mg", "Vial", "Triptorelin", "EIPICO", 425),
    ("Decapeptyl", "3.75 mg", "Vial", "Triptorelin", "Ipsen", 585),
    ("Rituximab", "100 mg", "Vial", "Rituximab", "EIPICO", 1285),
    ("Rituximab", "500 mg", "Vial", "Rituximab", "EIPICO", 4285),
    ("Rituxan", "500 mg", "Vial", "Rituximab", "Roche", 5885),
    ("MabThera", "500 mg", "Vial", "Rituximab", "Roche", 5885),
    ("Trastuzumab", "150 mg", "Vial", "Trastuzumab", "EIPICO", 2285),
    ("Herceptin", "150 mg", "Vial", "Trastuzumab", "Roche", 3585),
    ("Pertuzumab", "420 mg", "Vial", "Pertuzumab", "EIPICO", 4285),
    ("Perjeta", "420 mg", "Vial", "Pertuzumab", "Roche", 6285),
    ("Bevacizumab", "100 mg", "Vial", "Bevacizumab", "EIPICO", 1285),
    ("Bevacizumab", "400 mg", "Vial", "Bevacizumab", "EIPICO", 4285),
    ("Avastin", "400 mg", "Vial", "Bevacizumab", "Roche", 5885),
    ("Cetuximab", "100 mg", "Vial", "Cetuximab", "EIPICO", 1285),
    ("Cetuximab", "200 mg", "Vial", "Cetuximab", "EIPICO", 2285),
    ("Erbitux", "200 mg", "Vial", "Cetuximab", "BMS", 3285),
    ("Panitumumab", "100 mg", "Vial", "Panitumumab", "EIPICO", 1285),
    ("Panitumumab", "400 mg", "Vial", "Panitumumab", "EIPICO", 4285),
    ("Vectibix", "400 mg", "Vial", "Panitumumab", "Amgen", 5885),
    ("Ipilimumab", "50 mg", "Vial", "Ipilimumab", "EIPICO", 3285),
    ("Yervoy", "200 mg", "Vial", "Ipilimumab", "BMS", 8885),
    ("Nivolumab", "40 mg", "Vial", "Nivolumab", "EIPICO", 2285),
    ("Nivolumab", "100 mg", "Vial", "Nivolumab", "EIPICO", 5285),
    ("Opdivo", "100 mg", "Vial", "Nivolumab", "BMS", 7585),
    ("Pembrolizumab", "50 mg", "Vial", "Pembrolizumab", "EIPICO", 2285),
    ("Pembrolizumab", "100 mg", "Vial", "Pembrolizumab", "EIPICO", 4285),
    ("Keytruda", "100 mg", "Vial", "Pembrolizumab", "MSD", 6285),
    ("Atezolizumab", "1200 mg", "Vial", "Atezolizumab", "EIPICO", 6285),
    ("Tecentriq", "1200 mg", "Vial", "Atezolizumab", "Roche", 9285),
    ("Durvalumab", "500 mg", "Vial", "Durvalumab", "EIPICO", 4285),
    ("Imfinzi", "500 mg", "Vial", "Durvalumab", "AstraZeneca", 6285),
    ("Filgrastim", "30 MU", "Vial", "Filgrastim", "EIPICO", 485),
    ("Filgrastim", "48 MU", "Vial", "Filgrastim", "EIPICO", 685),
    ("Neupogen", "30 MU", "Vial", "Filgrastim", "Amgen", 685),
    ("Pegfilgrastim", "6 mg", "Pre-filled", "Pegfilgrastim", "EIPICO", 885),
    ("Neulasta", "6 mg", "Pre-filled", "Pegfilgrastim", "Amgen", 1285),
    ("Epoetin Alfa", "2000 IU", "Vial", "Epoetin Alfa", "EIPICO", 125),
    ("Epoetin Alfa", "4000 IU", "Vial", "Epoetin Alfa", "EIPICO", 185),
    ("Eprex", "4000 IU", "Vial", "Epoetin Alfa", "Janssen", 285),
    ("Darbepoetin", "25 mcg", "Vial", "Darbepoetin", "EIPICO", 225),
    ("Darbepoetin", "40 mcg", "Vial", "Darbepoetin", "EIPICO", 325),
    ("Aranesp", "40 mcg", "Vial", "Darbepoetin", "Amgen", 485),
    ("Interferon Alfa", "3 MU", "Vial", "Interferon Alfa", "EIPICO", 185),
    ("Interferon Alfa", "5 MU", "Vial", "Interferon Alfa", "EIPICO", 285),
    ("Intron A", "5 MU", "Vial", "Interferon Alfa", "MSD", 385),
    ("Peginterferon", "180 mcg", "Pre-filled", "Peginterferon", "EIPICO", 485),
    ("Pegasys", "180 mcg", "Pre-filled", "Peginterferon", "Roche", 685),
    ("Aldesleukin", "18 MU", "Vial", "Aldesleukin", "EIPICO", 1285),
    ("Proleukin", "18 MU", "Vial", "Aldesleukin", "Novartis", 1885),
    ("Denileukin", "300 mcg", "Vial", "Denileukin", "EIPICO", 2285),
    ("Ontak", "300 mcg", "Vial", "Denileukin", "Eisai", 3285),
    ("Asparaginase", "10000 IU", "Vial", "Asparaginase", "EIPICO", 485),
    ("Elspar", "10000 IU", "Vial", "Asparaginase", "Merck", 685),
]

for drug_data in additional_drugs:
    add_drug(*drug_data)

# Save
output = {"drugs": drugs}
with open('data/egyptian-drugs-gtin-expanded.json', 'w', encoding='utf-8') as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print(f"Total drugs now: {len(drugs)}")
