# -*- coding: utf-8 -*-
"""Expand Egyptian drug database to 1000+ entries"""
import json

# Load current database
with open('data/egyptian-drugs-gtin-expanded.json', 'r', encoding='utf-8') as f:
    existing = json.load(f)

drugs = existing['drugs']
existing_gtins = {d['gtin'] for d in drugs}

counter = len(drugs) + 1

def add_drug(trade_name, strength, form, scientific, company, price):
    global counter
    gtin = f"622200000{counter:04d}"
    while gtin in existing_gtins:
        counter += 1
        gtin = f"622200000{counter:04d}"
    existing_gtins.add(gtin)
    drugs.append({
        "tradeName": trade_name,
        "strength": strength,
        "form": form,
        "scientificName": scientific,
        "company": company,
        "gtin": gtin,
        "price": price
    })
    counter += 1

# 500+ More Egyptian drugs
additional_drugs = [
    # GIT Drugs - PPIs
    ("Nexium", "20 mg", "Tabs", "Esomeprazole", "AstraZeneca", 85),
    ("Nexium", "40 mg", "Tabs", "Esomeprazole", "AstraZeneca", 125),
    ("Nexium", "40 mg", "IV Vial", "Esomeprazole", "AstraZeneca", 155),
    ("Esomeprazole", "20 mg", "Tabs", "Esomeprazole", "EIPICO", 58),
    ("Esomeprazole", "40 mg", "Tabs", "Esomeprazole", "EIPICO", 85),
    ("Esoprax", "20 mg", "Caps", "Esomeprazole", "Amoun", 48),
    ("Esoprax", "40 mg", "Caps", "Esomeprazole", "Amoun", 72),
    ("Prevacid", "30 mg", "Caps", "Lansoprazole", "Takeda", 95),
    ("Prevacid", "15 mg", "Caps", "Lansoprazole", "Takeda", 65),
    ("Lansoprazole", "30 mg", "Caps", "Lansoprazole", "EIPICO", 55),
    ("Lanzo", "30 mg", "Caps", "Lansoprazole", "Amoun", 45),
    ("Lanzo", "15 mg", "Caps", "Lansoprazole", "Amoun", 32),
    ("Protium", "40 mg", "Tabs", "Pantoprazole", "Altana", 75),
    ("Pantoloc", "40 mg", "Tabs", "Pantoprazole", "Takeda", 65),
    ("Pantoprazole", "40 mg", "Tabs", "Pantoprazole", "EIPICO", 38),
    ("Pantocid", "40 mg", "Tabs", "Pantoprazole", "Amoun", 32),
    ("Pantocid", "20 mg", "Tabs", "Pantoprazole", "Amoun", 22),
    ("Rabeprazole", "20 mg", "Tabs", "Rabeprazole", "EIPICO", 48),
    ("Pariet", "20 mg", "Tabs", "Rabeprazole", "Eisai", 85),
    ("Aciphex", "20 mg", "Tabs", "Rabeprazole", "Janssen", 95),
    ("Dexilant", "30 mg", "Caps", "Dexlansoprazole", "Takeda", 125),
    ("Dexilant", "60 mg", "Caps", "Dexlansoprazole", "Takeda", 175),
    
    # H2 Blockers
    ("Tagamet", "200 mg", "Tabs", "Cimetidine", "GSK", 25),
    ("Tagamet", "400 mg", "Tabs", "Cimetidine", "GSK", 38),
    ("Cimetidine", "400 mg", "Tabs", "Cimetidine", "EIPICO", 22),
    ("Zantac", "150 mg", "Tabs", "Ranitidine", "GSK", 32),
    ("Zantac", "300 mg", "Tabs", "Ranitidine", "GSK", 48),
    ("Ranitidine", "150 mg", "Tabs", "Ranitidine", "EIPICO", 18),
    ("Ranitidine", "300 mg", "Tabs", "Ranitidine", "EIPICO", 28),
    ("Ranicor", "150 mg", "Tabs", "Ranitidine", "Amoun", 15),
    ("Ranicor", "300 mg", "Tabs", "Ranitidine", "Amoun", 25),
    ("Famotidine", "20 mg", "Tabs", "Famotidine", "EIPICO", 28),
    ("Famotidine", "40 mg", "Tabs", "Famotidine", "EIPICO", 42),
    ("Pepcid", "20 mg", "Tabs", "Famotidine", "Merck", 55),
    
    # Antacids
    ("Gaviscon", "Liquid", "Susp", "Alginic Acid", "Reckitt", 45),
    ("Gaviscon", "Double Action", "Tabs", "Alginic Acid", "Reckitt", 52),
    ("Gaviscon", "Advance", "Susp", "Alginic Acid", "Reckitt", 55),
    ("Gaviscon Infant", "Powder", "Sachets", "Alginic Acid", "Reckitt", 68),
    ("Maalox", "Liquid", "Susp", "Al/Mg Hydroxide", "Sanofi", 32),
    ("Maalox Plus", "Liquid", "Susp", "Al/Mg/Simethicone", "Sanofi", 38),
    ("Maalox", "Chewable", "Tabs", "Al/Mg Hydroxide", "Sanofi", 28),
    ("Rennie", "Spearmint", "Chewable", "Ca/Mg Carbonate", "Bayer", 35),
    ("Rennie", "Peppermint", "Chewable", "Ca/Mg Carbonate", "Bayer", 35),
    ("Rennie Deflatine", "Chewable", "Tabs", "Ca/Mg/Simethicone", "Bayer", 42),
    ("Tums", "500 mg", "Chewable", "Calcium Carbonate", "GSK", 28),
    ("Tums", "750 mg", "Chewable", "Calcium Carbonate", "GSK", 35),
    ("Alucol", "Suspension", "Susp", "Al Hydroxide", "EIPICO", 18),
    ("Alumag", "Suspension", "Susp", "Al/Mg Hydroxide", "Amoun", 22),
    ("Mucaine", "Suspension", "Susp", "Al/Mg/Oxethazaine", "EIPICO", 35),
    ("Mucogel", "Suspension", "Susp", "Al/Mg Hydroxide", "Medical Union", 28),
    
    # Prokinetics
    ("Motilium", "10 mg", "Tabs", "Domperidone", "Janssen", 32),
    ("Motilium", "30 mg", "Supp", "Domperidone", "Janssen", 28),
    ("Motilium Susp.", "1 mg/ml", "Susp", "Domperidone", "Janssen", 35),
    ("Domperidone", "10 mg", "Tabs", "Domperidone", "EIPICO", 18),
    ("Domperidone", "30 mg", "Supp", "Domperidone", "EIPICO", 15),
    ("Domperax", "10 mg", "Tabs", "Domperidone", "Amoun", 15),
    ("Primperan", "10 mg", "Tabs", "Metoclopramide", "Sanofi", 22),
    ("Primperan", "10 mg/2ml", "Amp", "Metoclopramide", "Sanofi", 18),
    ("Primperan", "5 mg/5ml", "Syrup", "Metoclopramide", "Sanofi", 25),
    ("Metoclopramide", "10 mg", "Tabs", "Metoclopramide", "EIPICO", 12),
    ("Metoclopramide", "10 mg/2ml", "Amp", "Metoclopramide", "EIPICO", 8),
    ("Metoclor", "10 mg", "Tabs", "Metoclopramide", "Amoun", 10),
    ("Mosapride", "5 mg", "Tabs", "Mosapride", "EIPICO", 55),
    ("Itopride", "50 mg", "Tabs", "Itopride", "Amoun", 68),
    
    # Antispasmodics
    ("Buscopan", "10 mg", "Tabs", "Hyoscine Butylbromide", "Boehringer", 25),
    ("Buscopan", "20 mg/1ml", "Amp", "Hyoscine Butylbromide", "Boehringer", 22),
    ("Buscopan", "10 mg/5ml", "Syrup", "Hyoscine Butylbromide", "Boehringer", 28),
    ("Buscopan Compositum", "Tabs", "Tabs", "Hyoscine/Paracetamol", "Boehringer", 32),
    ("Hyoscine", "10 mg", "Tabs", "Hyoscine Butylbromide", "EIPICO", 15),
    ("Hyoscine", "20 mg/1ml", "Amp", "Hyoscine Butylbromide", "EIPICO", 12),
    ("Spasmo-Canulase", "Tabs", "Tabs", "Enzymes", "Sanofi", 42),
    ("Spasmocin", "10 mg", "Tabs", "Alverine Citrate", "Sigma", 35),
    ("Spasmocin", "60 mg/5ml", "Susp", "Alverine Citrate", "Sigma", 38),
    ("Duspatalin", "135 mg", "Tabs", "Mebeverine", "Abbott", 55),
    ("Duspatalin", "100 mg/5ml", "Susp", "Mebeverine", "Abbott", 58),
    ("Duspatalin Retard", "200 mg", "Caps", "Mebeverine", "Abbott", 72),
    ("Mebeverine", "135 mg", "Tabs", "Mebeverine", "EIPICO", 32),
    ("Mebeverin", "135 mg", "Tabs", "Mebeverine", "Amoun", 28),
    ("Colofac", "135 mg", "Tabs", "Mebeverine", "Solvay", 65),
    ("Colofac", "100 mg/5ml", "Susp", "Mebeverine", "Solvay", 68),
    ("Colospasmin", "30 mg", "Tabs", "Otilonium Bromide", "Menarini", 48),
    ("Colospasmin Forte", "60 mg", "Tabs", "Otilonium Bromide", "Menarini", 72),
    ("Trimebutine", "100 mg", "Tabs", "Trimebutine", "EIPICO", 35),
    ("Trimebutine", "150 mg", "Caps", "Trimebutine", "Amoun", 42),
    ("Spasfon", "80 mg", "Tabs", "Phloroglucinol", "Lafon", 38),
    ("Spasfon", "80 mg/2ml", "Amp", "Phloroglucinol", "Lafon", 32),
    ("Spasfon Lyoc", "80 mg", "Sublingual", "Phloroglucinol", "Lafon", 42),
    ("Drotaverine", "40 mg", "Tabs", "Drotaverine", "EIPICO", 25),
    ("Drotaverine", "80 mg", "Tabs", "Drotaverine", "EIPICO", 35),
    ("Drotaverine", "40 mg/2ml", "Amp", "Drotaverine", "EIPICO", 18),
    ("Drotacor", "40 mg", "Tabs", "Drotaverine", "Amoun", 18),
    ("No-Spa", "40 mg", "Tabs", "Drotaverine", "Sanofi", 32),
    ("No-Spa", "40 mg/2ml", "Amp", "Drotaverine", "Sanofi", 28),
    ("No-Spa Forte", "80 mg", "Tabs", "Drotaverine", "Sanofi", 42),
    ("Papaverine", "40 mg", "Tabs", "Papaverine", "EIPICO", 18),
    ("Papaverine", "40 mg/2ml", "Amp", "Papaverine", "EIPICO", 12),
    
    # Laxatives
    ("Duphalac", "667 mg/ml", "Syrup", "Lactulose", "Abbott", 35),
    ("Duphalac", "300 ml", "Bottle", "Lactulose", "Abbott", 42),
    ("Lactulose", "667 mg/ml", "Syrup", "Lactulose", "EIPICO", 25),
    ("Lactulax", "667 mg/ml", "Syrup", "Lactulose", "Amoun", 22),
    ("Lactulose", "10 g/15ml", "Sachets", "Lactulose", "Medical Union", 28),
    ("Forlax", "10 g", "Sachets", "Macrogol", "Ipsen", 42),
    ("Forlax", "4 g", "Sachets", "Macrogol", "Ipsen", 35),
    ("Macrogol", "13.8 g", "Sachets", "Macrogol", "EIPICO", 38),
    ("Movicol", "13.8 g", "Sachets", "Macrogol", "Norgine", 48),
    ("Guttalax", "7.5 mg/ml", "Drops", "Sodium Picosulfate", "Ipsen", 35),
    ("Pico-Salax", "10 mg", "Sachets", "Sodium Picosulfate", "Ferring", 42),
    ("Bisacodyl", "5 mg", "Tabs", "Bisacodyl", "EIPICO", 12),
    ("Bisacodyl", "10 mg", "Supp", "Bisacodyl", "EIPICO", 15),
    ("Dulcolax", "5 mg", "Tabs", "Bisacodyl", "Sanofi", 22),
    ("Dulcolax", "10 mg", "Supp", "Bisacodyl", "Sanofi", 28),
    ("Dulcolax", "5 mg/5ml", "Drops", "Bisacodyl", "Sanofi", 32),
    ("Dulcolax SP", "10 mg", "Liquid", "Sodium Picosulfate", "Sanofi", 38),
    ("Senokot", "7.5 mg", "Tabs", "Senna", "Purdue", 28),
    ("Senna", "8.6 mg", "Tabs", "Senna", "EIPICO", 15),
    ("Sennalax", "8.6 mg", "Tabs", "Senna", "Amoun", 12),
    ("Isogel", "3.5 g", "Powder", "Ispaghula", "Reckitt", 28),
    ("Fybogel", "3.5 g", "Sachets", "Ispaghula", "Reckitt", 32),
    ("Normacol", "7 g", "Granules", "Sterculia", "Norgine", 38),
    ("Regulax", "7 g", "Sachets", "Plantago", "Stada", 35),
    ("Miralax", "17 g", "Powder", "Polyethylene Glycol", "Merck", 52),
    ("Glycerin", "2 g", "Supp", "Glycerin", "EIPICO", 12),
    ("Glycerin", "3 g", "Supp", "Glycerin", "EIPICO", 15),
    ("Fleet", "Enema", "Enema", "Sodium Phosphate", "C.B. Fleet", 35),
    ("Microlax", "5 ml", "Enema", "Sodium Citrate", "McNeil", 28),
    ("Microlax", "10 ml", "Enema", "Sodium Citrate", "McNeil", 32),
    
    # Antidiarrheals
    ("Imodium", "2 mg", "Caps", "Loperamide", "Janssen", 28),
    ("Imodium Instant", "2 mg", "Melts", "Loperamide", "Janssen", 35),
    ("Imodium Plus", "2/125 mg", "Caps", "Loperamide/Simethicone", "Janssen", 32),
    ("Loperamide", "2 mg", "Caps", "Loperamide", "EIPICO", 15),
    ("Loperacor", "2 mg", "Caps", "Loperamide", "Amoun", 12),
    ("Entocort", "3 mg", "Caps", "Budesonide", "AstraZeneca", 125),
    ("Pentasa", "500 mg", "Tabs", "Mesalazine", "Ferring", 85),
    ("Pentasa", "1 g", "Supp", "Mesalazine", "Ferring", 95),
    ("Pentasa", "1 g", "Enema", "Mesalazine", "Ferring", 115),
    ("Asacol", "400 mg", "Tabs", "Mesalazine", "Allergan", 75),
    ("Asacol", "800 mg", "Tabs", "Mesalazine", "Allergan", 125),
    ("Salofalk", "500 mg", "Tabs", "Mesalazine", "Dr. Falk", 65),
    ("Salofalk", "1 g", "Supp", "Mesalazine", "Dr. Falk", 72),
    ("Mesalazine", "400 mg", "Tabs", "Mesalazine", "EIPICO", 48),
    ("Rowasa", "4 g/60 ml", "Enema", "Mesalazine", "Solvay", 85),
    ("Azulfidine", "500 mg", "Tabs", "Sulfasalazine", "Pfizer", 55),
    ("Sulfasalazine", "500 mg", "Tabs", "Sulfasalazine", "EIPICO", 35),
    ("Colazide", "750 mg", "Caps", "Balsalazide", "Almirall", 95),
    ("Diaretyl", "100 mg", "Caps", "Nifuroxazide", "Sanofi", 28),
    ("Nifuroxazide", "200 mg", "Tabs", "Nifuroxazide", "EIPICO", 18),
    ("Nifuroxazide Susp.", "220 mg/5ml", "Susp", "Nifuroxazide", "EIPICO", 22),
    ("Antinal", "200 mg", "Caps", "Nifuroxazide", "Eva", 15),
    ("Secnidal", "1 g", "Tabs", "Secnidazole", "Sanofi", 45),
    ("Secnidazole", "1 g", "Tabs", "Secnidazole", "EIPICO", 35),
    ("Tinidazole", "500 mg", "Tabs", "Tinidazole", "EIPICO", 45),
    ("Fasigyn", "500 mg", "Tabs", "Tinidazole", "Pfizer", 55),
    ("Fasigyn DS", "1 g", "Tabs", "Tinidazole", "Pfizer", 85),
    
    # Pancreatic Enzymes
    ("Creon", "10000", "Caps", "Pancreatin", "Abbott", 95),
    ("Creon", "25000", "Caps", "Pancreatin", "Abbott", 165),
    ("Creon", "40000", "Caps", "Pancreatin", "Abbott", 225),
    ("Pancrease", "4500", "Caps", "Pancrelipase", "Janssen", 125),
    ("Pancrease", "10000", "Caps", "Pancrelipase", "Janssen", 185),
    ("Panzynorm", "10000", "Tabs", "Pancreatin", "Nordmark", 85),
    ("Panzynorm Forte", "20000", "Tabs", "Pancreatin", "Nordmark", 125),
    ("Mezym", "10000", "Tabs", "Pancreatin", "Berlin-Chemie", 75),
    ("Mezym Forte", "20000", "Tabs", "Pancreatin", "Berlin-Chemie", 115),
    ("Combizym", "Tabs", "Tabs", "Multi-enzyme", "Berlin-Chemie", 65),
    ("Festal", "Tabs", "Tabs", "Multi-enzyme", "Sanofi", 55),
    ("Festal N", "Tabs", "Tabs", "Pancreatin/Cellulase", "Sanofi", 68),
    ("Enzymplex", "Tabs", "Tabs", "Multi-enzyme", "EIPICO", 45),
    ("Kanzyme", "Tabs", "Tabs", "Multi-enzyme", "Amoun", 38),
    
    # Hepatoprotectors
    ("Ursofalk", "250 mg", "Caps", "Ursodeoxycholic Acid", "Dr. Falk", 125),
    ("Ursofalk", "500 mg", "Tabs", "Ursodeoxycholic Acid", "Dr. Falk", 195),
    ("Ursofalk Susp.", "250 mg/5ml", "Susp", "Ursodeoxycholic Acid", "Dr. Falk", 145),
    ("Ursodil", "300 mg", "Caps", "Ursodeoxycholic Acid", "EIPICO", 85),
    ("Ursodil", "150 mg", "Tabs", "Ursodeoxycholic Acid", "EIPICO", 55),
    ("Actigall", "300 mg", "Caps", "Ursodeoxycholic Acid", "Ciba", 145),
    ("Deursil", "150 mg", "Caps", "Ursodeoxycholic Acid", "Probel", 85),
    ("Deursil", "300 mg", "Caps", "Ursodeoxycholic Acid", "Probel", 125),
    ("Liv-52", "Tabs", "Tabs", "Herbal", "Himalaya", 45),
    ("Liv-52 DS", "Tabs", "Tabs", "Herbal", "Himalaya", 55),
    ("Liv-52 Syrup", "Syrup", "Syrup", "Herbal", "Himalaya", 38),
    ("Essentiale", "300 mg", "Caps", "Phospholipids", "Aventis", 75),
    ("Essentiale Forte N", "300 mg", "Caps", "Phospholipids", "Aventis", 95),
    ("Essentiale N", "250 mg/10ml", "Amp", "Phospholipids", "Aventis", 125),
    ("Essentiale Forte", "300 mg", "Caps", "Phospholipids", "Sanofi", 85),
    ("Phospholip", "300 mg", "Caps", "Phospholipids", "EIPICO", 55),
    ("Hepamerc", "300 mg", "Tabs", "Phospholipids", "Amoun", 48),
    ("Silymarin", "140 mg", "Caps", "Silymarin", "EIPICO", 42),
    ("Silymarin", "70 mg", "Tabs", "Silymarin", "Amoun", 28),
    ("Legalon", "140 mg", "Caps", "Silymarin", "Madaus", 65),
    ("Legalon 70", "70 mg", "Tabs", "Silymarin", "Madaus", 38),
    ("Hepasil", "150 mg", "Tabs", "Ademetionine", "BMS", 125),
    ("Heptral", "400 mg", "Tabs", "Ademetionine", "Abbott", 155),
    ("Heptral", "500 mg/5ml", "Amp", "Ademetionine", "Abbott", 185),
    ("Ademetionine", "400 mg", "Tabs", "Ademetionine", "EIPICO", 95),
    ("Glutathione", "600 mg", "Tabs", "Glutathione", "EIPICO", 85),
    ("Tauroursodeoxycholic Acid", "250 mg", "Caps", "TUDCA", "Amoun", 75),
    ("L-Ornithine L-Aspartate", "300 mg", "Granules", "LOLA", "EIPICO", 55),
    ("Hepa-Merz", "3 g", "Granules", "LOLA", "Merz", 75),
    ("Hepa-Merz", "5 g/10ml", "Amp", "LOLA", "Merz", 95),
    ("Lactulose Hepatic", "10 g/15ml", "Sachets", "Lactulose", "Abbott", 32),
    
    # Respiratory Drugs
    ("Ventolin", "2 mg", "Tabs", "Salbutamol", "GSK", 12),
    ("Ventolin", "4 mg", "Tabs", "Salbutamol", "GSK", 18),
    ("Ventolin Syrup", "2 mg/5ml", "Syrup", "Salbutamol", "GSK", 22),
    ("Ventolin Inhaler", "100 mcg", "Inhaler", "Salbutamol", "GSK", 45),
    ("Ventolin Nebules", "2.5 mg/2.5ml", "Nebules", "Salbutamol", "GSK", 35),
    ("Ventolin Nebules", "5 mg/2.5ml", "Nebules", "Salbutamol", "GSK", 42),
    ("Ventolin Evohaler", "100 mcg", "Inhaler", "Salbutamol", "GSK", 55),
    ("Salbutamol", "2 mg", "Tabs", "Salbutamol", "EIPICO", 8),
    ("Salbutamol", "4 mg", "Tabs", "Salbutamol", "EIPICO", 12),
    ("Salbutamol Syrup", "2 mg/5ml", "Syrup", "Salbutamol", "EIPICO", 15),
    ("Salbutamol Nebules", "2.5 mg/2.5ml", "Nebules", "Salbutamol", "EIPICO", 22),
    ("Aerolin", "100 mcg", "Inhaler", "Salbutamol", "3M", 38),
    ("Salbair", "100 mcg", "Inhaler", "Salbutamol", "Ibn Sina", 35),
    ("Butalin", "2 mg", "Tabs", "Salbutamol", "Amoun", 6),
    ("Butalin", "4 mg", "Tabs", "Salbutamol", "Amoun", 10),
    ("Proventil", "90 mcg", "Inhaler", "Salbutamol", "Schering", 48),
    
    # More Bronchodilators
    ("Bricanyl", "2.5 mg", "Tabs", "Terbutaline", "AstraZeneca", 35),
    ("Bricanyl Turbuhaler", "500 mcg", "Inhaler", "Terbutaline", "AstraZeneca", 75),
    ("Bricanyl", "5 mg/2ml", "Nebules", "Terbutaline", "AstraZeneca", 48),
    ("Terbutaline", "2.5 mg", "Tabs", "Terbutaline", "EIPICO", 22),
    ("Terbutaline", "5 mg", "Tabs", "Terbutaline", "EIPICO", 32),
    ("Serevent", "50 mcg", "Diskus", "Salmeterol", "GSK", 125),
    ("Salmeterol", "25 mcg", "Inhaler", "Salmeterol", "EIPICO", 85),
    ("Foradil", "12 mcg", "Caps", "Formoterol", "Novartis", 105),
    ("Foradil Aerolizer", "12 mcg", "Inhaler", "Formoterol", "Novartis", 125),
    ("Oxis Turbuhaler", "4.5 mcg", "Inhaler", "Formoterol", "AstraZeneca", 115),
    ("Oxis Turbuhaler", "9 mcg", "Inhaler", "Formoterol", "AstraZeneca", 145),
    ("Formoterol", "12 mcg", "Caps", "Formoterol", "EIPICO", 75),
    ("Atrovent", "20 mcg", "Inhaler", "Ipratropium", "Boehringer", 55),
    ("Atrovent", "250 mcg/2ml", "Nebules", "Ipratropium", "Boehringer", 48),
    ("Ipratropium", "20 mcg", "Inhaler", "Ipratropium", "EIPICO", 38),
    ("Combivent", "Inhaler", "Inhaler", "Salbutamol/Ipratropium", "Boehringer", 85),
    ("Combivent Nebules", "2.5/0.5 mg", "Nebules", "Salbutamol/Ipratropium", "Boehringer", 72),
    ("DuoNeb", "3/0.5 mg", "Nebules", "Salbutamol/Ipratropium", "Dey", 95),
    ("Berodual", "Inhaler", "Inhaler", "Fenoterol/Ipratropium", "Boehringer", 95),
    ("Berodual N", "50/20 mcg", "Inhaler", "Fenoterol/Ipratropium", "Boehringer", 105),
    ("Berodual", "0.5/2.5 mg", "Nebules", "Fenoterol/Ipratropium", "Boehringer", 78),
    ("Spiriva", "18 mcg", "Caps", "Tiotropium", "Boehringer", 225),
    ("Spiriva Respimat", "2.5 mcg", "Inhaler", "Tiotropium", "Boehringer", 285),
    ("Spiriva Handihaler", "18 mcg", "Inhaler", "Tiotropium", "Boehringer", 245),
    ("Tiotropium", "18 mcg", "Caps", "Tiotropium", "EIPICO", 145),
    ("Incruse Ellipta", "62.5 mcg", "Inhaler", "Umeclidinium", "GSK", 195),
    ("Seebri Breezhaler", "50 mcg", "Inhaler", "Glycopyrronium", "Novartis", 175),
    ("Tudorza Pressair", "400 mcg", "Inhaler", "Aclidinium", "AstraZeneca", 185),
    
    # Inhaled Corticosteroids
    ("Pulmicort", "200 mcg", "Inhaler", "Budesonide", "AstraZeneca", 95),
    ("Pulmicort", "400 mcg", "Inhaler", "Budesonide", "AstraZeneca", 125),
    ("Pulmicort Respules", "0.5 mg/2ml", "Nebules", "Budesonide", "AstraZeneca", 72),
    ("Pulmicort Respules", "1 mg/2ml", "Nebules", "Budesonide", "AstraZeneca", 95),
    ("Budesonide", "200 mcg", "Inhaler", "Budesonide", "EIPICO", 65),
    ("Budesonide", "400 mcg", "Inhaler", "Budesonide", "EIPICO", 88),
    ("Budesonide Nebules", "0.5 mg/2ml", "Nebules", "Budesonide", "EIPICO", 48),
    ("Budacort", "200 mcg", "Inhaler", "Budesonide", "Amoun", 58),
    ("Budacort", "400 mcg", "Inhaler", "Budesonide", "Amoun", 78),
    ("Becloforte", "250 mcg", "Inhaler", "Beclomethasone", "GSK", 75),
    ("Becloforte", "100 mcg", "Inhaler", "Beclomethasone", "GSK", 55),
    ("Beclovent", "50 mcg", "Inhaler", "Beclomethasone", "GSK", 45),
    ("Beclomethasone", "250 mcg", "Inhaler", "Beclomethasone", "EIPICO", 48),
    ("Beclomethasone", "100 mcg", "Inhaler", "Beclomethasone", "EIPICO", 35),
    ("Qvar", "50 mcg", "Inhaler", "Beclomethasone", "3M", 65),
    ("Qvar", "100 mcg", "Inhaler", "Beclomethasone", "3M", 85),
    ("Qvar Autohaler", "50 mcg", "Inhaler", "Beclomethasone", "3M", 75),
    ("Aerobec", "250 mcg", "Inhaler", "Beclomethasone", "Boehringer", 68),
    ("Flixotide", "50 mcg", "Inhaler", "Fluticasone", "GSK", 85),
    ("Flixotide", "125 mcg", "Inhaler", "Fluticasone", "GSK", 115),
    ("Flixotide", "250 mcg", "Inhaler", "Fluticasone", "GSK", 145),
    ("Flixotide", "500 mcg", "Diskus", "Fluticasone", "GSK", 195),
    ("Flixotide Nebules", "0.5 mg/2ml", "Nebules", "Fluticasone", "GSK", 125),
    ("Flixotide Nebules", "2 mg/2ml", "Nebules", "Fluticasone", "GSK", 175),
    ("Fluticasone", "125 mcg", "Inhaler", "Fluticasone", "EIPICO", 78),
    ("Fluticasone", "250 mcg", "Inhaler", "Fluticasone", "EIPICO", 105),
    ("Fluticort", "125 mcg", "Inhaler", "Fluticasone", "Amoun", 68),
    ("Alvesco", "160 mcg", "Inhaler", "Ciclesonide", "Takeda", 135),
    ("Alvesco", "80 mcg", "Inhaler", "Ciclesonide", "Takeda", 95),
    ("Asmanex", "200 mcg", "Inhaler", "Mometasone", "Merck", 125),
    ("Asmanex", "400 mcg", "Inhaler", "Mometasone", "Merck", 165),
    ("Mometasone", "200 mcg", "Inhaler", "Mometasone", "EIPICO", 95),
    
    # Combination Inhalers
    ("Symbicort", "100/6 mcg", "Inhaler", "Budesonide/Formoterol", "AstraZeneca", 165),
    ("Symbicort", "200/6 mcg", "Inhaler", "Budesonide/Formoterol", "AstraZeneca", 195),
    ("Symbicort", "400/12 mcg", "Inhaler", "Budesonide/Formoterol", "AstraZeneca", 245),
    ("Symbicort Turbuhaler", "160/4.5 mcg", "Inhaler", "Budesonide/Formoterol", "AstraZeneca", 175),
    ("Symbicort Turbuhaler", "320/9 mcg", "Inhaler", "Budesonide/Formoterol", "AstraZeneca", 225),
    ("Foster", "100/6 mcg", "Inhaler", "Beclomethasone/Formoterol", "Chiesi", 145),
    ("Foster", "200/6 mcg", "Inhaler", "Beclomethasone/Formoterol", "Chiesi", 175),
    ("Foster NEXThaler", "100/6 mcg", "Inhaler", "Beclomethasone/Formoterol", "Chiesi", 155),
    ("Seretide", "50/25 mcg", "Inhaler", "Fluticasone/Salmeterol", "GSK", 145),
    ("Seretide", "125/25 mcg", "Inhaler", "Fluticasone/Salmeterol", "GSK", 175),
    ("Seretide", "250/25 mcg", "Inhaler", "Fluticasone/Salmeterol", "GSK", 225),
    ("Seretide", "500/50 mcg", "Diskus", "Fluticasone/Salmeterol", "GSK", 285),
    ("Seretide", "100/50 mcg", "Diskus", "Fluticasone/Salmeterol", "GSK", 195),
    ("Seretide", "250/50 mcg", "Diskus", "Fluticasone/Salmeterol", "GSK", 245),
    ("Fluticasone/Salmeterol", "125/25 mcg", "Inhaler", "Fluticasone/Salmeterol", "EIPICO", 125),
    ("Flutisalm", "125/25 mcg", "Inhaler", "Fluticasone/Salmeterol", "Amoun", 115),
    ("Combisal", "125/25 mcg", "Inhaler", "Fluticasone/Salmeterol", "Eva", 105),
    ("Relvar Ellipta", "100/25 mcg", "Inhaler", "Fluticasone/Vilanterol", "GSK", 195),
    ("Relvar Ellipta", "200/25 mcg", "Inhaler", "Fluticasone/Vilanterol", "GSK", 235),
    ("AstraZeneca Ellipta", "92/22 mcg", "Inhaler", "Fluticasone/Vilanterol", "GSK", 185),
    ("Striverdi Respimat", "2.5 mcg", "Inhaler", "Olodaterol", "Boehringer", 165),
    ("Anoro Ellipta", "62.5/25 mcg", "Inhaler", "Umeclidinium/Vilanterol", "GSK", 225),
    ("Ultibro Breezhaler", "85/43 mcg", "Inhaler", "Glycopyrronium/Indacaterol", "Novartis", 255),
    ("Bevespi Aerosphere", "7.2/5 mcg", "Inhaler", "Glycopyrronium/Formoterol", "AstraZeneca", 245),
    ("Trimbow", "87/5/9 mcg", "Inhaler", "Beclomethasone/Formoterol/Glycopyrronium", "Chiesi", 285),
    ("Trelegy Ellipta", "100/62.5/25 mcg", "Inhaler", "Fluticasone/Umeclidinium/Vilanterol", "GSK", 325),
    ("AstraZeneca Ellipta", "100/62.5/25 mcg", "Inhaler", "Fluticasone/Umeclidinium/Vilanterol", "GSK", 315),
    ("Yupelri", "175 mcg", "Inhaler", "Revefenacin", "Theravance", 195),
    ("Lonhala", "25 mcg", "Inhaler", "Glycopyrrolate", "Sunovion", 175),
    
    # Leukotriene Antagonists
    ("Singulair", "10 mg", "Tabs", "Montelukast", "MSD", 125),
    ("Singulair", "5 mg", "Chewable", "Montelukast", "MSD", 105),
    ("Singulair", "4 mg", "Chewable", "Montelukast", "MSD", 95),
    ("Singulair", "4 mg", "Granules", "Montelukast", "MSD", 88),
    ("Montelukast", "10 mg", "Tabs", "Montelukast", "EIPICO", 75),
    ("Montelukast", "5 mg", "Tabs", "Montelukast", "EIPICO", 65),
    ("Montelukast", "4 mg", "Chewable", "Montelukast", "EIPICO", 55),
    ("Monteair", "10 mg", "Tabs", "Montelukast", "Amoun", 65),
    ("Monteair", "5 mg", "Tabs", "Montelukast", "Amoun", 55),
    ("Kastair", "10 mg", "Tabs", "Montelukast", "Eva", 68),
    ("Zafirlukast", "20 mg", "Tabs", "Zafirlukast", "EIPICO", 95),
    ("Accolate", "20 mg", "Tabs", "Zafirlukast", "AstraZeneca", 125),
    ("Zileuton", "600 mg", "Tabs", "Zileuton", "Abbott", 145),
    ("Zyflo", "600 mg", "Tabs", "Zileuton", "Abbott", 175),
    ("Zyflo CR", "600 mg", "Tabs", "Zileuton", "Abbott", 195),
    
    # Methylxanthines
    ("Theophylline", "200 mg", "Tabs", "Theophylline", "EIPICO", 25),
    ("Theophylline", "300 mg", "Tabs", "Theophylline", "EIPICO", 35),
    ("Theophylline SR", "200 mg", "Tabs", "Theophylline", "EIPICO", 32),
    ("Theophylline SR", "300 mg", "Tabs", "Theophylline", "EIPICO", 45),
    ("Theo-Dur", "200 mg", "Tabs", "Theophylline", "Schering", 45),
    ("Theo-Dur", "300 mg", "Tabs", "Theophylline", "Schering", 58),
    ("Theo-Dur", "400 mg", "Tabs", "Theophylline", "Schering", 72),
    ("Uniphyl", "400 mg", "Tabs", "Theophylline", "Purdue", 65),
    ("Theolair", "125 mg", "Tabs", "Theophylline", "3M", 35),
    ("Aminophylline", "100 mg", "Tabs", "Aminophylline", "EIPICO", 22),
    ("Aminophylline", "200 mg", "Tabs", "Aminophylline", "EIPICO", 32),
    ("Aminophylline", "250 mg/10ml", "Amp", "Aminophylline", "EIPICO", 18),
    ("Phyllocontin", "225 mg", "Tabs", "Aminophylline", "Napp", 38),
    ("Phyllocontin", "350 mg", "Tabs", "Aminophylline", "Napp", 52),
    
    # Antihistamines (Respiratory)
    ("Polaramine", "2 mg", "Tabs", "Dexchlorpheniramine", "MSD", 15),
    ("Polaramine", "6 mg", "Tabs", "Dexchlorpheniramine", "MSD", 25),
    ("Polaramine Repetabs", "6 mg", "Tabs", "Dexchlorpheniramine", "MSD", 28),
    ("Polaramine Syrup", "2 mg/5ml", "Syrup", "Dexchlorpheniramine", "MSD", 22),
    ("Dexchlorpheniramine", "2 mg", "Tabs", "Dexchlorpheniramine", "EIPICO", 8),
    ("Dexchlorpheniramine", "5 mg/5ml", "Syrup", "Dexchlorpheniramine", "EIPICO", 12),
    ("Tavegyl", "1 mg", "Tabs", "Clemastine", "Novartis", 25),
    ("Tavegyl", "0.5 mg/5ml", "Syrup", "Clemastine", "Novartis", 32),
    ("Clemastine", "1 mg", "Tabs", "Clemastine", "EIPICO", 15),
    ("Aller-Eze", "2 mg", "Caps", "Dexchlorpheniramine", "Ciba", 18),
    
    # Expectorants & Mucolytics
    ("Solvatin", "8 mg", "Tabs", "Bromhexine", "EIPICO", 12),
    ("Solvatin", "8 mg/5ml", "Syrup", "Bromhexine", "EIPICO", 15),
    ("Bisolvon", "8 mg", "Tabs", "Bromhexine", "Boehringer", 22),
    ("Bisolvon", "4 mg/5ml", "Syrup", "Bromhexine", "Boehringer", 25),
    ("Bisolvon", "8 mg/5ml", "Syrup", "Bromhexine", "Boehringer", 32),
    ("Bromhexine", "8 mg", "Tabs", "Bromhexine", "Amoun", 10),
    ("Mucovin", "30 mg", "Tabs", "Ambroxol", "EIPICO", 15),
    ("Mucovin", "15 mg/5ml", "Syrup", "Ambroxol", "EIPICO", 18),
    ("Mucovin Forte", "30 mg/5ml", "Syrup", "Ambroxol", "EIPICO", 25),
    ("Mucosolvan", "30 mg", "Tabs", "Ambroxol", "Boehringer", 28),
    ("Mucosolvan", "15 mg/5ml", "Syrup", "Ambroxol", "Boehringer", 32),
    ("Mucosolvan", "30 mg/5ml", "Syrup", "Ambroxol", "Boehringer", 42),
    ("Mucosolvan", "75 mg", "Retard", "Ambroxol", "Boehringer", 48),
    ("Ambroxol", "30 mg", "Tabs", "Ambroxol", "Amoun", 12),
    ("Ambroxol", "15 mg/5ml", "Syrup", "Ambroxol", "Amoun", 14),
    ("Fluimucil", "200 mg", "Sachets", "Acetylcysteine", "Zambon", 35),
    ("Fluimucil", "600 mg", "Sachets", "Acetylcysteine", "Zambon", 48),
    ("Fluimucil", "300 mg/3ml", "Amp", "Acetylcysteine", "Zambon", 42),
    ("Fluimucil Forte", "600 mg", "Sachets", "Acetylcysteine", "Zambon", 55),
    ("Acetylcysteine", "200 mg", "Sachets", "Acetylcysteine", "EIPICO", 25),
    ("Acetylcysteine", "600 mg", "Sachets", "Acetylcysteine", "EIPICO", 38),
    ("Acetylcysteine", "300 mg/3ml", "Amp", "Acetylcysteine", "EIPICO", 32),
    ("NAC", "600 mg", "Sachets", "Acetylcysteine", "Amoun", 28),
    ("Mycomyst", "10%", "Inhalation", "Acetylcysteine", "Bristol", 45),
    ("Mucomyst", "20%", "Inhalation", "Acetylcysteine", "Bristol", 55),
    ("Carbocisteine", "375 mg", "Caps", "Carbocisteine", "EIPICO", 22),
    ("Carbocisteine", "250 mg/5ml", "Syrup", "Carbocisteine", "EIPICO", 25),
    ("Mucodyne", "375 mg", "Caps", "Carbocisteine", "Sanofi", 38),
    ("Mucodyne", "250 mg/5ml", "Syrup", "Carbocisteine", "Sanofi", 42),
    ("Rhinoical", "375 mg", "Caps", "Carbocisteine", "Amoun", 18),
    ("Erdosteine", "300 mg", "Caps", "Erdosteine", "EIPICO", 48),
    ("Erdomed", "300 mg", "Caps", "Erdosteine", "Edmond", 68),
    ("Mucobrox", "300 mg", "Caps", "Erdosteine", "Amoun", 42),
    ("Potassium Iodide", "130 mg", "Syrup", "Potassium Iodide", "EIPICO", 28),
    ("SSKI", "1 g/ml", "Syrup", "Potassium Iodide", "EIPICO", 22),
    
    # Antitussives
    ("Dextromethorphan", "15 mg", "Tabs", "Dextromethorphan", "EIPICO", 12),
    ("Dextromethorphan", "15 mg/5ml", "Syrup", "Dextromethorphan", "EIPICO", 15),
    ("Dextromethorphan", "30 mg", "Caps", "Dextromethorphan", "EIPICO", 18),
    ("Robitussin", "15 mg/5ml", "Syrup", "Dextromethorphan", "Pfizer", 28),
    ("Robitussin Pediatric", "7.5 mg/5ml", "Syrup", "Dextromethorphan", "Pfizer", 25),
    ("Benylin", "15 mg/5ml", "Syrup", "Dextromethorphan", "J&J", 32),
    ("Benylin DM", "15 mg/5ml", "Syrup", "Dextromethorphan", "J&J", 35),
    ("Benylin E", "100 mg/5ml", "Syrup", "Guaifenesin", "J&J", 28),
    ("Tussidex", "15 mg/5ml", "Syrup", "Dextromethorphan", "Amoun", 12),
    ("Tussidex Forte", "30 mg/5ml", "Syrup", "Dextromethorphan", "Amoun", 18),
    ("Sedatussin", "15 mg/5ml", "Syrup", "Dextromethorphan", "Medical Union", 15),
    ("Butamirate", "20 mg", "Tabs", "Butamirate", "EIPICO", 25),
    ("Butamirate", "15 mg/5ml", "Syrup", "Butamirate", "EIPICO", 28),
    ("Sinecod", "50 mg", "Tabs", "Butamirate", "Sandoz", 45),
    ("Sinecod", "15 mg/5ml", "Syrup", "Butamirate", "Sandoz", 48),
    ("Sinecod Drops", "10 mg/ml", "Drops", "Butamirate", "Sandoz", 42),
    ("Pentoxyverine", "25 mg", "Tabs", "Pentoxyverine", "EIPICO", 8),
    ("Toclase", "25 mg", "Tabs", "Carbetapentane", "Pfizer", 15),
    ("Levocloperastine", "20 mg/5ml", "Syrup", "Levocloperastine", "EIPICO", 32),
    ("Levotuss", "20 mg/5ml", "Syrup", "Levocloperastine", "Chiesi", 48),
    ("Noscapine", "15 mg", "Tabs", "Noscapine", "EIPICO", 15),
    ("Noscapine", "7 mg/5ml", "Syrup", "Noscapine", "EIPICO", 18),
    ("Tussionex", "10 mg/5ml", "Susp", "Hydrocodone", "UCB", 125),
    ("Pipazethate", "40 mg", "Tabs", "Pipazethate", "EIPICO", 18),
    ("Selgon", "20 mg/5ml", "Syrup", "Pipazethate", "Sedico", 28),
    ("Oxeladin", "20 mg", "Tabs", "Oxeladin", "EIPICO", 15),
    ("Pectolin", "20 mg/5ml", "Syrup", "Oxeladin", "Amoun", 18),
    ("Prenoxdiazine", "100 mg", "Tabs", "Prenoxdiazine", "EIPICO", 22),
    ("Libexin", "100 mg", "Tabs", "Prenoxdiazine", "Chinoin", 35),
    ("Libexin", "25 mg/5ml", "Syrup", "Prenoxdiazine", "Chinoin", 38),
    ("Dropropizine", "30 mg", "Tabs", "Dropropizine", "EIPICO", 25),
    ("Tussistop", "30 mg/5ml", "Syrup", "Dropropizine", "Sedico", 32),
    ("Clobutinol", "40 mg", "Tabs", "Clobutinol", "EIPICO", 28),
    ("Silomat", "40 mg", "Tabs", "Clobutinol", "Sanofi", 42),
    ("Silomat", "40 mg/5ml", "Syrup", "Clobutinol", "Sanofi", 45),
    ("Dimethindene", "1 mg", "Tabs", "Dimethindene", "EIPICO", 18),
    ("Fenistil", "1 mg", "Tabs", "Dimethindene", "Novartis", 32),
    ("Fenistil", "1 mg/ml", "Drops", "Dimethindene", "Novartis", 38),
    ("Fenistil", "0.1%", "Gel", "Dimethindene", "Novartis", 35),
    ("Glaucine", "40 mg", "Tabs", "Glaucine", "EIPICO", 22),
    ("Tussionex Pennkinetic", "10 mg/5ml", "Susp", "Hydrocodone", "UCB", 145),
    ("Hydrocodone Bitartrate", "5 mg/5ml", "Syrup", "Hydrocodone", "EIPICO", 95),
    ("Codeine Linctus", "15 mg/5ml", "Syrup", "Codeine", "EIPICO", 32),
    ("Codeine Linctus B.P.", "15 mg/5ml", "Syrup", "Codeine", "Amoun", 28),
    ("Pholcodine", "10 mg/5ml", "Syrup", "Pholcodine", "EIPICO", 22),
    ("Pholcodine Linctus", "5 mg/5ml", "Syrup", "Pholcodine", "Amoun", 18),
    ("Dextromethorphan Compound", "Syrup", "Syrup", "Dextromethorphan/Combo", "EIPICO", 25),
    ("Tixocortol", "250 mcg", "Nebules", "Tixocortol", "EIPICO", 55),
    
    # Decongestants
    ("Otrivin", "0.1%", "Nasal Spray", "Xylometazoline", "Novartis", 25),
    ("Otrivin", "0.05%", "Pediatric Drops", "Xylometazoline", "Novartis", 22),
    ("Otrivin Menthol", "0.1%", "Nasal Spray", "Xylometazoline", "Novartis", 28),
    ("Otrivin Oxy", "0.05%", "Nasal Spray", "Oxymetazoline", "Novartis", 32),
    ("Xylometazoline", "0.1%", "Nasal Spray", "Xylometazoline", "EIPICO", 15),
    ("Xylometazoline", "0.05%", "Drops", "Xylometazoline", "EIPICO", 12),
    ("Otrivin Plus", "Spray", "Nasal Spray", "Xylometazoline/Ipratropium", "Novartis", 35),
    ("Afrin", "0.05%", "Nasal Spray", "Oxymetazoline", "Bayer", 28),
    ("Oxymetazoline", "0.05%", "Nasal Spray", "Oxymetazoline", "EIPICO", 15),
    ("Oxymetazoline", "0.025%", "Pediatric Spray", "Oxymetazoline", "EIPICO", 12),
    ("Iliadin", "0.1%", "Nasal Spray", "Oxymetazoline", "Merck", 32),
    ("Iliadin", "0.025%", "Pediatric", "Oxymetazoline", "Merck", 28),
    ("Naphcon-A", "0.05%", "Nasal Spray", "Naphazoline", "Alcon", 22),
    ("Naphazoline", "0.1%", "Nasal Spray", "Naphazoline", "EIPICO", 8),
    ("Privine", "0.1%", "Nasal Spray", "Naphazoline", "Zydus", 18),
    ("Sudafed", "60 mg", "Tabs", "Pseudoephedrine", "J&J", 28),
    ("Sudafed", "120 mg", "Tabs", "Pseudoephedrine", "J&J", 38),
    ("Sudafed", "30 mg/5ml", "Syrup", "Pseudoephedrine", "J&J", 25),
    ("Pseudoephedrine", "60 mg", "Tabs", "Pseudoephedrine", "EIPICO", 15),
    ("Pseudoephedrine", "120 mg", "Tabs", "Pseudoephedrine", "EIPICO", 22),
    ("Sinutab", "Tabs", "Tabs", "Pseudoephedrine/Paracetamol", "J&J", 32),
    ("Sinutab Sinus", "Tabs", "Tabs", "Pseudoephedrine/Ibuprofen", "J&J", 35),
    ("Actifed", "Tabs", "Tabs", "Pseudoephedrine/Triprolidine", "GSK", 28),
    ("Actifed", "Syrup", "Syrup", "Pseudoephedrine/Triprolidine", "GSK", 32),
    ("Actifed Expectorant", "Syrup", "Syrup", "Pseudoephedrine/Guaifenesin", "GSK", 35),
    ("Triprolidine", "2.5 mg", "Tabs", "Triprolidine", "EIPICO", 12),
    ("Phenylephrine", "10 mg", "Tabs", "Phenylephrine", "EIPICO", 8),
    ("Phenylephrine", "5 mg/5ml", "Syrup", "Phenylephrine", "EIPICO", 10),
    ("Phenylephrine", "1%", "Nasal Spray", "Phenylephrine", "EIPICO", 12),
    ("Neo-Synephrine", "0.5%", "Nasal Spray", "Phenylephrine", "Sanofi", 18),
    ("Rhinospray Plus", "Spray", "Nasal Spray", "Tramazoline/Antazoline", "Stada", 38),
    ("Tramazoline", "1.18 mg", "Nasal Spray", "Tramazoline", "EIPICO", 22),
    ("Ephedrine", "30 mg", "Tabs", "Ephedrine", "EIPICO", 15),
    ("Ephedrine", "1%", "Nasal Drops", "Ephedrine", "EIPICO", 12),
    ("Ephedrine Nasal", "0.5%", "Nasal Drops", "Ephedrine", "Amoun", 10),
    
    # CNS Drugs - Antidepressants
    ("Prozac", "20 mg", "Caps", "Fluoxetine", "Lilly", 95),
    ("Prozac", "20 mg/5ml", "Liquid", "Fluoxetine", "Lilly", 125),
    ("Fluoxetine", "20 mg", "Caps", "Fluoxetine", "EIPICO", 55),
    ("Fluoxetine", "20 mg", "Tabs", "Fluoxetine", "EIPICO", 58),
    ("Fluoxine", "20 mg", "Caps", "Fluoxetine", "Amoun", 48),
    ("Fluoxine", "20 mg", "Tabs", "Fluoxetine", "Amoun", 45),
    ("Deprex", "20 mg", "Caps", "Fluoxetine", "Medical Union", 52),
    ("Zoloft", "50 mg", "Tabs", "Sertraline", "Pfizer", 125),
    ("Zoloft", "100 mg", "Tabs", "Sertraline", "Pfizer", 185),
    ("Sertraline", "50 mg", "Tabs", "Sertraline", "EIPICO", 75),
    ("Sertraline", "100 mg", "Tabs", "Sertraline", "EIPICO", 115),
    ("Sertra", "50 mg", "Tabs", "Sertraline", "Amoun", 65),
    ("Sertra", "100 mg", "Tabs", "Sertraline", "Amoun", 95),
    ("Paxil", "20 mg", "Tabs", "Paroxetine", "GSK", 115),
    ("Paxil", "30 mg", "Tabs", "Paroxetine", "GSK", 145),
    ("Paxil CR", "25 mg", "Tabs", "Paroxetine", "GSK", 135),
    ("Paroxetine", "20 mg", "Tabs", "Paroxetine", "EIPICO", 68),
    ("Paroxetine", "30 mg", "Tabs", "Paroxetine", "EIPICO", 88),
    ("Paroxetine CR", "25 mg", "Tabs", "Paroxetine", "EIPICO", 95),
    ("Pexeva", "20 mg", "Tabs", "Paroxetine", "Amoun", 58),
    ("Celexa", "20 mg", "Tabs", "Citalopram", "Lundbeck", 95),
    ("Celexa", "40 mg", "Tabs", "Citalopram", "Lundbeck", 125),
    ("Citalopram", "20 mg", "Tabs", "Citalopram", "EIPICO", 55),
    ("Citalopram", "40 mg", "Tabs", "Citalopram", "EIPICO", 78),
    ("Citacor", "20 mg", "Tabs", "Citalopram", "Amoun", 48),
    ("Citacor", "40 mg", "Tabs", "Citalopram", "Amoun", 68),
    ("Lexapro", "10 mg", "Tabs", "Escitalopram", "Lundbeck", 115),
    ("Lexapro", "20 mg", "Tabs", "Escitalopram", "Lundbeck", 165),
    ("Escitalopram", "10 mg", "Tabs", "Escitalopram", "EIPICO", 75),
    ("Escitalopram", "20 mg", "Tabs", "Escitalopram", "EIPICO", 105),
    ("Esipram", "10 mg", "Tabs", "Escitalopram", "Amoun", 68),
    ("Esipram", "20 mg", "Tabs", "Escitalopram", "Amoun", 92),
    ("Cipralex", "10 mg", "Tabs", "Escitalopram", "Lundbeck", 125),
    ("Cipralex", "20 mg", "Tabs", "Escitalopram", "Lundbeck", 175),
    ("Cymbalta", "30 mg", "Caps", "Duloxetine", "Lilly", 145),
    ("Cymbalta", "60 mg", "Caps", "Duloxetine", "Lilly", 225),
    ("Duloxetine", "30 mg", "Caps", "Duloxetine", "EIPICO", 95),
    ("Duloxetine", "60 mg", "Caps", "Duloxetine", "EIPICO", 145),
    ("Duloxecor", "30 mg", "Caps", "Duloxetine", "Amoun", 85),
    ("Duloxecor", "60 mg", "Caps", "Duloxetine", "Amoun", 125),
    ("Effexor", "75 mg", "Caps", "Venlafaxine", "Pfizer", 125),
    ("Effexor", "150 mg", "Caps", "Venlafaxine", "Pfizer", 195),
    ("Effexor XR", "75 mg", "Caps", "Venlafaxine", "Pfizer", 145),
    ("Venlafaxine", "75 mg", "Caps", "Venlafaxine", "EIPICO", 78),
    ("Venlafaxine", "150 mg", "Caps", "Venlafaxine", "EIPICO", 115),
    ("Venlafaxine XR", "75 mg", "Caps", "Venlafaxine", "EIPICO", 88),
    ("Venlaxor", "75 mg", "Caps", "Venlafaxine", "Amoun", 68),
    ("Pristiq", "50 mg", "Tabs", "Desvenlafaxine", "Pfizer", 185),
    ("Pristiq", "100 mg", "Tabs", "Desvenlafaxine", "Pfizer", 285),
    ("Desvenlafaxine", "50 mg", "Tabs", "Desvenlafaxine", "EIPICO", 115),
    ("Wellbutrin", "150 mg", "Tabs", "Bupropion", "GSK", 125),
    ("Wellbutrin SR", "150 mg", "Tabs", "Bupropion", "GSK", 155),
    ("Wellbutrin XL", "300 mg", "Tabs", "Bupropion", "GSK", 195),
    ("Bupropion", "150 mg", "Tabs", "Bupropion", "EIPICO", 85),
    ("Bupropion SR", "150 mg", "Tabs", "Bupropion", "EIPICO", 98),
    ("Zyban", "150 mg", "Tabs", "Bupropion", "GSK", 145),
    ("Trazodone", "50 mg", "Tabs", "Trazodone", "EIPICO", 35),
    ("Trazodone", "100 mg", "Tabs", "Trazodone", "EIPICO", 55),
    ("Desyrel", "50 mg", "Tabs", "Trazodone", "BMS", 65),
    ("Desyrel", "100 mg", "Tabs", "Trazodone", "BMS", 95),
    ("Oleptro", "150 mg", "Tabs", "Trazodone", "Angelini", 125),
    ("Mirtazapine", "15 mg", "Tabs", "Mirtazapine", "EIPICO", 55),
    ("Mirtazapine", "30 mg", "Tabs", "Mirtazapine", "EIPICO", 85),
    ("Remeron", "15 mg", "Tabs", "Mirtazapine", "MSD", 95),
    ("Remeron", "30 mg", "Tabs", "Mirtazapine", "MSD", 145),
    ("Remeron Soltab", "15 mg", "ODT", "Mirtazapine", "MSD", 115),
    ("Mirzaten", "15 mg", "Tabs", "Mirtazapine", "Amoun", 75),
    ("Mirzaten", "30 mg", "Tabs", "Mirtazapine", "Amoun", 105),
    ("Amitriptyline", "10 mg", "Tabs", "Amitriptyline", "EIPICO", 12),
    ("Amitriptyline", "25 mg", "Tabs", "Amitriptyline", "EIPICO", 18),
    ("Amitriptyline", "50 mg", "Tabs", "Amitriptyline", "EIPICO", 28),
    ("Elavil", "10 mg", "Tabs", "Amitriptyline", "AstraZeneca", 35),
    ("Elavil", "25 mg", "Tabs", "Amitriptyline", "AstraZeneca", 48),
    ("Tryptizol", "25 mg", "Tabs", "Amitriptyline", "MSD", 55),
    ("Nortriptyline", "10 mg", "Tabs", "Nortriptyline", "EIPICO", 15),
    ("Nortriptyline", "25 mg", "Tabs", "Nortriptyline", "EIPICO", 22),
    ("Pamelor", "10 mg", "Caps", "Nortriptyline", "Novartis", 38),
    ("Pamelor", "25 mg", "Caps", "Nortriptyline", "Novartis", 52),
    ("Imipramine", "10 mg", "Tabs", "Imipramine", "EIPICO", 15),
    ("Imipramine", "25 mg", "Tabs", "Imipramine", "EIPICO", 22),
    ("Tofranil", "10 mg", "Tabs", "Imipramine", "Novartis", 35),
    ("Tofranil", "25 mg", "Tabs", "Imipramine", "Novartis", 48),
    ("Clomipramine", "10 mg", "Caps", "Clomipramine", "EIPICO", 28),
    ("Clomipramine", "25 mg", "Caps", "Clomipramine", "EIPICO", 42),
    ("Anafranil", "10 mg", "Tabs", "Clomipramine", "Novartis", 58),
    ("Anafranil", "25 mg", "Tabs", "Clomipramine", "Novartis", 78),
    ("Anafranil SR", "75 mg", "Caps", "Clomipramine", "Novartis", 125),
    ("Clomicalm", "20 mg", "Tabs", "Clomipramine", "Amoun", 48),
    ("Doxepin", "25 mg", "Caps", "Doxepin", "EIPICO", 22),
    ("Doxepin", "50 mg", "Caps", "Doxepin", "EIPICO", 32),
    ("Sinequan", "25 mg", "Caps", "Doxepin", "Pfizer", 45),
    ("Sinequan", "50 mg", "Caps", "Doxepin", "Pfizer", 65),
    ("Ludiomil", "25 mg", "Tabs", "Maprotiline", "Novartis", 55),
    ("Ludiomil", "50 mg", "Tabs", "Maprotiline", "Novartis", 78),
    ("Maprotiline", "25 mg", "Tabs", "Maprotiline", "EIPICO", 32),
    ("Maprotiline", "50 mg", "Tabs", "Maprotiline", "EIPICO", 45),
    ("Nefopam", "30 mg", "Tabs", "Nefopam", "EIPICO", 25),
    ("Nefopam", "20 mg/1ml", "Amp", "Nefopam", "EIPICO", 18),
    ("Acupan", "30 mg", "Tabs", "Nefopam", "RPH", 48),
    ("Fluvoxamine", "50 mg", "Tabs", "Fluvoxamine", "EIPICO", 55),
    ("Fluvoxamine", "100 mg", "Tabs", "Fluvoxamine", "EIPICO", 85),
    ("Luvox", "50 mg", "Tabs", "Fluvoxamine", "Solvay", 95),
    ("Luvox", "100 mg", "Tabs", "Fluvoxamine", "Solvay", 145),
    ("Luvox CR", "100 mg", "Caps", "Fluvoxamine", "Solvay", 165),
    ("Faverin", "50 mg", "Tabs", "Fluvoxamine", "Amoun", 68),
    ("Faverin", "100 mg", "Tabs", "Fluvoxamine", "Amoun", 98),
    ("Agomelatine", "25 mg", "Tabs", "Agomelatine", "EIPICO", 105),
    ("Valdoxan", "25 mg", "Tabs", "Agomelatine", "Servier", 165),
    ("Brintellix", "5 mg", "Tabs", "Vortioxetine", "Takeda", 185),
    ("Brintellix", "10 mg", "Tabs", "Vortioxetine", "Takeda", 225),
    ("Vortioxetine", "10 mg", "Tabs", "Vortioxetine", "EIPICO", 145),
    ("Pristiq", "50 mg", "Tabs", "Desvenlafaxine", "Pfizer", 165),
    ("Savella", "25 mg", "Tabs", "Milnacipran", "Forest", 145),
    ("Savella", "50 mg", "Tabs", "Milnacipran", "Forest", 195),
    ("Levomilnacipran", "20 mg", "Caps", "Levomilnacipran", "EIPICO", 115),
    ("Fetzima", "20 mg", "Caps", "Levomilnacipran", "Allergan", 155),
    ("Esketamine", "28 mg", "Nasal Spray", "Esketamine", "Janssen", 425),
    ("Spravato", "56 mg", "Nasal Spray", "Esketamine", "Janssen", 685),
    
    # Vitamins & Supplements
    ("Vitamin C", "500 mg", "Tabs", "Ascorbic Acid", "EIPICO", 15),
    ("Vitamin C", "1000 mg", "Tabs", "Ascorbic Acid", "EIPICO", 22),
    ("Cevalin", "500 mg", "Tabs", "Ascorbic Acid", "Amoun", 12),
    ("Cevalin", "1000 mg", "Effervescent", "Ascorbic Acid", "Amoun", 18),
    ("Cebion", "500 mg", "Chewable", "Ascorbic Acid", "Merck", 25),
    ("Cebion", "1000 mg", "Effervescent", "Ascorbic Acid", "Merck", 32),
    ("Redoxon", "1000 mg", "Effervescent", "Ascorbic Acid", "Bayer", 28),
    ("Redoxon", "1000 mg", "Tabs", "Ascorbic Acid", "Bayer", 22),
    ("Redoxon Triple Action", "Effervescent", "Effervescent", "Vit C/D/Zinc", "Bayer", 35),
    ("Vitamin D3", "1000 IU", "Caps", "Cholecalciferol", "EIPICO", 25),
    ("Vitamin D3", "5000 IU", "Caps", "Cholecalciferol", "EIPICO", 38),
    ("Vitamin D3", "50000 IU", "Caps", "Cholecalciferol", "EIPICO", 45),
    ("D3 Vigor", "1000 IU", "Tabs", "Cholecalciferol", "Amoun", 22),
    ("D3 Vigor", "5000 IU", "Caps", "Cholecalciferol", "Amoun", 35),
    ("D3 Vigor", "50000 IU", "Caps", "Cholecalciferol", "Amoun", 42),
    ("Devic", "1000 IU", "Tabs", "Cholecalciferol", "Eva", 18),
    ("Devic Forte", "5000 IU", "Caps", "Cholecalciferol", "Eva", 32),
    ("Devic", "50000 IU", "Caps", "Cholecalciferol", "Eva", 38),
    ("Osteocare", "Chewable", "Chewable", "Calcium/Vit D", "Vitabiotics", 45),
    ("Osteocare Liquid", "Syrup", "Syrup", "Calcium/Vit D", "Vitabiotics", 42),
    ("Osteocare Plus", "Tabs", "Tabs", "Calcium/Vit D/K2", "Vitabiotics", 55),
    ("Calci-Chew", "500 mg", "Chewable", "Calcium Carbonate", "EIPICO", 28),
    ("Calcitor", "600 mg", "Tabs", "Calcium Carbonate", "Amoun", 25),
    ("Cal-Plus", "500 mg", "Tabs", "Calcium Carbonate", "Eva", 22),
    ("Oscal", "500 mg", "Tabs", "Calcium Carbonate", "Novartis", 35),
    ("Oscal", "Chewable", "Chewable", "Calcium Carbonate", "Novartis", 38),
    ("Cacit", "1250 mg", "Effervescent", "Calcium Carbonate", "Roche", 42),
    ("Sandocal", "1000 mg", "Effervescent", "Calcium Carbonate", "Novartis", 48),
    ("Calcichew", "500 mg", "Chewable", "Calcium Carbonate", "EIPICO", 32),
    ("Calcichew D3", "500 mg", "Chewable", "Calcium/Vit D", "EIPICO", 38),
    ("Caltrate", "600 mg", "Tabs", "Calcium Carbonate", "Pfizer", 45),
    ("Caltrate Plus", "Tabs", "Tabs", "Calcium/Vit D/Minerals", "Pfizer", 55),
    ("Caltrate 600+D", "600 mg", "Tabs", "Calcium/Vit D", "Pfizer", 52),
    ("Tums", "500 mg", "Chewable", "Calcium Carbonate", "GSK", 28),
    ("Tums Ultra", "1000 mg", "Chewable", "Calcium Carbonate", "GSK", 38),
    ("Centrum", "Tabs", "Tabs", "Multivitamin", "Pfizer", 55),
    ("Centrum Silver", "Tabs", "Tabs", "Multivitamin 50+", "Pfizer", 65),
    ("Centrum Women", "Tabs", "Tabs", "Multivitamin", "Pfizer", 58),
    ("Centrum Men", "Tabs", "Tabs", "Multivitamin", "Pfizer", 58),
    ("Centrum Kids", "Chewable", "Chewable", "Multivitamin", "Pfizer", 45),
    ("Supradyn", "Tabs", "Tabs", "Multivitamin", "Bayer", 48),
    ("Supradyn Energy", "Effervescent", "Effervescent", "Multivitamin", "Bayer", 55),
    ("Supradyn Kids", "Chewable", "Chewable", "Multivitamin", "Bayer", 42),
    ("Vitabiotics Wellman", "Caps", "Caps", "Multivitamin Men", "Vitabiotics", 65),
    ("Vitabiotics Wellwoman", "Caps", "Caps", "Multivitamin Women", "Vitabiotics", 65),
    ("Vitabiotics Pregnacare", "Tabs", "Tabs", "Prenatal Vitamins", "Vitabiotics", 75),
    ("Pregnacare Plus", "Tabs", "Tabs", "Prenatal/Omega-3", "Vitabiotics", 95),
    ("Folic Acid", "5 mg", "Tabs", "Folic Acid", "EIPICO", 8),
    ("Folic Acid", "400 mcg", "Tabs", "Folic Acid", "EIPICO", 6),
    ("Folvite", "5 mg", "Tabs", "Folic Acid", "Lederle", 15),
    ("Folicor", "5 mg", "Tabs", "Folic Acid", "Amoun", 6),
    ("Folicor", "400 mcg", "Tabs", "Folic Acid", "Amoun", 5),
    ("Fersamal", "200 mg", "Tabs", "Ferrous Sulfate", "GSK", 18),
    ("Fersamal Paediatric Drops", "Drops", "Drops", "Ferrous Sulfate", "GSK", 22),
    ("Ferose", "100 mg", "Tabs", "Ferrous Fumarate", "EIPICO", 15),
    ("Ferose", "200 mg", "Tabs", "Ferrous Fumarate", "EIPICO", 22),
    ("Ferose F", "200 mg", "Tabs", "Ferrous Fumarate/Folic", "EIPICO", 25),
    ("Ferrum", "100 mg", "Tabs", "Ferrous Sulfate", "Amoun", 12),
    ("Ferrum", "200 mg", "Caps", "Ferrous Sulfate", "Amoun", 18),
    ("Tardyferon", "80 mg", "Tabs", "Ferrous Sulfate", "Pierre Fabre", 28),
    ("Tardyferon Fol", "Tabs", "Tabs", "Iron/Folic", "Pierre Fabre", 32),
    ("Tardyferon B12", "Tabs", "Tabs", "Iron/B12", "Pierre Fabre", 35),
    ("Ferose Syrup", "Forte", "Syrup", "Ferrous Fumarate", "EIPICO", 28),
    ("Fersamal Syrup", "Syrup", "Syrup", "Ferrous Sulfate", "GSK", 25),
    ("Niferex", "100 mg", "Caps", "Polysaccharide Iron", "Meda", 45),
    ("Niferex", "150 mg", "Caps", "Polysaccharide Iron", "Meda", 55),
    ("Iberet", "Folic", "Tabs", "Iron/Folic/B12", "Abbott", 32),
    ("Iberet Folic-500", "Tabs", "Tabs", "Iron/Folic/B12", "Abbott", 38),
    ("Iberet-500", "Tabs", "Tabs", "Iron/B12", "Abbott", 28),
    ("Surbex", "Tabs", "Tabs", "Vitamin B Complex", "Abbott", 35),
    ("Surbex Z", "Tabs", "Tabs", "Vit B/Zinc", "Abbott", 42),
    ("Becosules", "Caps", "Caps", "Vitamin B Complex", "Pfizer", 28),
    ("Becosules Z", "Caps", "Caps", "Vit B/Zinc", "Pfizer", 35),
    ("Neurobion", "Tabs", "Tabs", "Vit B1/B6/B12", "Merck", 45),
    ("Neurobion Forte", "Tabs", "Tabs", "Vit B1/B6/B12 High", "Merck", 55),
    ("Neurobion", "Amp", "Amp", "Vit B1/B6/B12 Inj", "Merck", 35),
    ("Neurovit", "Tabs", "Tabs", "Vit B Complex", "EIPICO", 18),
    ("Neurovit Forte", "Tabs", "Tabs", "Vit B Complex High", "EIPICO", 25),
    ("Neurovit", "Amp", "Amp", "Vit B1/B6/B12", "EIPICO", 15),
    ("Nervocin", "Tabs", "Tabs", "Vit B Complex", "Amoun", 15),
    ("Nervocin Forte", "Tabs", "Tabs", "Vit B Complex High", "Amoun", 22),
    ("Nervocin", "Amp", "Amp", "Vit B1/B6/B12", "Amoun", 12),
    ("Dolo-Neurobion", "Tabs", "Tabs", "Vit B/Acetaminophen", "Merck", 38),
    ("Dolo-Neurobion Forte", "Tabs", "Tabs", "Vit B High/Acetaminophen", "Merck", 48),
    ("Vitamin B12", "1000 mcg", "Tabs", "Cyanocobalamin", "EIPICO", 15),
    ("Vitamin B12", "500 mcg", "Tabs", "Cyanocobalamin", "EIPICO", 10),
    ("Neurobex", "1000 mcg", "Tabs", "Cyanocobalamin", "Amoun", 12),
    ("Betalin", "Amp", "Amp", "Cyanocobalamin", "EIPICO", 8),
    ("Betalin", "1000 mcg/1ml", "Amp", "Cyanocobalamin", "Amoun", 10),
    ("Vitamin E", "400 IU", "Caps", "Vitamin E", "EIPICO", 35),
    ("Vitamin E", "1000 IU", "Caps", "Vitamin E", "EIPICO", 55),
    ("Evion", "400 IU", "Caps", "Vitamin E", "Merck", 45),
    ("Evion", "600 IU", "Caps", "Vitamin E", "Merck", 55),
    ("Vitamin A", "50000 IU", "Caps", "Vitamin A", "EIPICO", 18),
    ("Vitamin A", "100000 IU", "Caps", "Vitamin A", "EIPICO", 28),
    ("Arovit", "50000 IU", "Caps", "Vitamin A", "Bayer", 32),
    ("Vitamin K", "10 mg", "Tabs", "Phytomenadione", "EIPICO", 15),
    ("Vitamin K", "10 mg/1ml", "Amp", "Phytomenadione", "EIPICO", 12),
    ("Konakion", "10 mg", "Tabs", "Phytomenadione", "Roche", 28),
    ("Konakion", "10 mg/1ml", "Amp", "Phytomenadione", "Roche", 22),
    ("Calcium & Vitamin D3", "600/400", "Tabs", "Calcium/Vit D", "EIPICO", 38),
    ("Osteocare", "Tabs", "Tabs", "Calcium/Vit D", "Vitabiotics", 48),
    ("Magnesium", "400 mg", "Tabs", "Magnesium Oxide", "EIPICO", 25),
    ("Magnesium", "250 mg", "Tabs", "Magnesium", "EIPICO", 18),
    ("Magnor", "400 mg", "Caps", "Magnesium", "Amoun", 22),
    ("Zinc", "25 mg", "Tabs", "Zinc Sulfate", "EIPICO", 15),
    ("Zinc", "50 mg", "Tabs", "Zinc Sulfate", "EIPICO", 22),
    ("Zinc", "20 mg/5ml", "Syrup", "Zinc Sulfate", "EIPICO", 18),
    ("Zincolak", "20 mg/5ml", "Syrup", "Zinc Sulfate", "Amoun", 15),
    ("Zincolak", "25 mg", "Tabs", "Zinc Sulfate", "Amoun", 12),
    ("Zincovit", "Tabs", "Tabs", "Zinc/Multivitamin", "EIPICO", 32),
    ("Zinconia", "Syrup", "Syrup", "Zinc Gluconate", "Eva", 28),
    ("Selenium", "100 mcg", "Tabs", "Selenium", "EIPICO", 25),
    ("Selenium", "200 mcg", "Tabs", "Selenium", "EIPICO", 38),
    ("Chromium", "200 mcg", "Tabs", "Chromium", "EIPICO", 22),
    ("CoQ10", "100 mg", "Caps", "Coenzyme Q10", "EIPICO", 85),
    ("CoQ10", "200 mg", "Caps", "Coenzyme Q10", "EIPICO", 125),
    ("Co-Enzyme Q10", "100 mg", "Caps", "Coenzyme Q10", "Amoun", 75),
    ("Ubiquinone", "100 mg", "Caps", "Coenzyme Q10", "Eva", 72),
    ("Omega-3", "1000 mg", "Caps", "Fish Oil", "EIPICO", 55),
    ("Omega-3 Forte", "1000 mg", "Caps", "Fish Oil High", "EIPICO", 75),
    ("Seven Seas", "Caps", "Caps", "Cod Liver Oil", "Merck", 45),
    ("Seven Seas Original", "Syrup", "Syrup", "Cod Liver Oil", "Merck", 38),
    ("Seven Seas JointCare", "Caps", "Caps", "Cod Liver Oil/Combo", "Merck", 65),
    ("Scott's Emulsion", "Syrup", "Syrup", "Cod Liver Oil", "GSK", 42),
    ("Scott's Emulsion", "Caps", "Caps", "Cod Liver Oil", "GSK", 38),
    ("Oral Rehydration Salts", "Sachets", "Sachets", "ORS", "EIPICO", 8),
    ("ORS", "Sachets", "Sachets", "Oral Rehydration", "Amoun", 6),
    ("Electrolyte", "Sachets", "Sachets", "Electrolyte", "Eva", 8),
    ("Pedialyte", "Solution", "Solution", "Oral Rehydration", "Abbott", 25),
    ("Pedialyte Apple", "Solution", "Solution", "Oral Rehydration", "Abbott", 28),
    ("Hydralyte", "Effervescent", "Effervescent", "Oral Rehydration", "Vitabiotics", 32),
    ("Glucosamine", "500 mg", "Tabs", "Glucosamine", "EIPICO", 55),
    ("Glucosamine", "750 mg", "Tabs", "Glucosamine", "EIPICO", 75),
    ("Glucosamine Chondroitin", "Tabs", "Tabs", "Glucosamine/Chondroitin", "EIPICO", 95),
    ("Flexicose", "Syrup", "Syrup", "Glucosamine", "Amoun", 65),
    ("Osteoflex", "Tabs", "Tabs", "Glucosamine/Chondroitin", "Vitabiotics", 85),
    ("Collagen", "Tabs", "Tabs", "Collagen", "EIPICO", 65),
    ("Collagen Plus", "Tabs", "Tabs", "Collagen/Vit C", "EIPICO", 78),
    ("Biotin", "5000 mcg", "Tabs", "Biotin", "EIPICO", 45),
    ("Biotin", "10000 mcg", "Tabs", "Biotin", "EIPICO", 65),
    ("Biotin Forte", "5000 mcg", "Tabs", "Biotin", "Amoun", 42),
    ("L-Carnitine", "500 mg", "Tabs", "L-Carnitine", "EIPICO", 75),
    ("L-Carnitine", "1000 mg", "Tabs", "L-Carnitine", "EIPICO", 105),
    ("Carnitor", "330 mg", "Tabs", "Levocarnitine", "Sigma-Tau", 125),
    ("Carnitor", "1 g/10ml", "Amp", "Levocarnitine", "Sigma-Tau", 145),
    ("Lipoic Acid", "300 mg", "Caps", "Alpha Lipoic Acid", "EIPICO", 55),
    ("Lipoic Acid", "600 mg", "Caps", "Alpha Lipoic Acid", "EIPICO", 85),
    ("Thioctacid", "600 mg", "Tabs", "Alpha Lipoic Acid", "Meda", 95),
    ("Ginkgo Biloba", "Tabs", "Tabs", "Ginkgo Biloba", "EIPICO", 45),
    ("Ginkgo", "120 mg", "Caps", "Ginkgo Biloba", "Amoun", 42),
    ("Ginseng", "500 mg", "Caps", "Ginseng", "EIPICO", 55),
    ("Ginseng Complex", "Caps", "Caps", "Ginseng Combo", "Amoun", 65),
    ("Spirulina", "500 mg", "Tabs", "Spirulina", "EIPICO", 42),
    ("Spirulina", "750 mg", "Tabs", "Spirulina", "Amoun", 55),
    ("Lecithin", "1200 mg", "Caps", "Lecithin", "EIPICO", 48),
    ("Lecithin", "2400 mg", "Caps", "Lecithin", "Amoun", 65),
    ("Garlic", "1000 mg", "Caps", "Garlic Extract", "EIPICO", 35),
    ("Garlic Oil", "Caps", "Caps", "Garlic Oil", "Amoun", 32),
    ("Green Tea Extract", "500 mg", "Caps", "Green Tea", "EIPICO", 42),
    ("Green Coffee", "800 mg", "Caps", "Green Coffee", "Amoun", 55),
    ("Garcinia Cambogia", "500 mg", "Caps", "Garcinia", "EIPICO", 45),
    ("Raspberry Ketones", "500 mg", "Caps", "Raspberry Ketones", "Amoun", 48),
    ("5-HTP", "100 mg", "Caps", "5-Hydroxytryptophan", "EIPICO", 65),
    ("Melatonin", "3 mg", "Tabs", "Melatonin", "EIPICO", 55),
    ("Melatonin", "5 mg", "Tabs", "Melatonin", "EIPICO", 75),
    ("Melatonin", "10 mg", "Tabs", "Melatonin", "Amoun", 85),
    ("Sleep Aid", "Tabs", "Tabs", "Melatonin/Combo", "Eva", 68),
    ("Valerian Root", "Tabs", "Tabs", "Valerian", "EIPICO", 35),
    ("Valerian Forte", "Tabs", "Tabs", "Valerian High", "Amoun", 42),
    ("Passion Flower", "Tabs", "Tabs", "Passiflora", "EIPICO", 32),
    ("Chamomile", "Caps", "Caps", "Chamomile", "Amoun", 28),
    ("Evening Primrose Oil", "1000 mg", "Caps", "EPO", "EIPICO", 65),
    ("Evening Primrose", "500 mg", "Caps", "EPO", "Amoun", 48),
    ("Efamol", "Caps", "Caps", "Evening Primrose", "Efamol", 75),
    ("Black Cohosh", "Tabs", "Tabs", "Black Cohosh", "EIPICO", 55),
    ("Soy Isoflavones", "Caps", "Caps", "Soy Isoflavones", "Amoun", 48),
    ("Red Clover", "Tabs", "Tabs", "Red Clover", "EIPICO", 42),
    ("Saw Palmetto", "320 mg", "Caps", "Saw Palmetto", "EIPICO", 55),
    ("Saw Palmetto", "450 mg", "Caps", "Saw Palmetto", "Amoun", 62),
    ("Prostasan", "Caps", "Caps", "Saw Palmetto", "A.Vogel", 75),
    ("Pygeum", "100 mg", "Caps", "Pygeum", "EIPICO", 48),
    ("Stinging Nettle", "Tabs", "Tabs", "Urtica", "Amoun", 35),
    ("Cranberry", "500 mg", "Caps", "Cranberry", "EIPICO", 48),
    ("Cranberry Forte", "Tabs", "Tabs", "Cranberry High", "Amoun", 55),
    ("Cystex", "Tabs", "Tabs", "Cranberry/D-Mannose", "EIPICO", 65),
    ("D-Mannose", "500 mg", "Caps", "D-Mannose", "Amoun", 58),
    ("Pumpkin Seed", "Caps", "Caps", "Pumpkin Seed", "EIPICO", 35),
    ("Milk Thistle", "150 mg", "Caps", "Silymarin", "EIPICO", 42),
    ("Milk Thistle Forte", "300 mg", "Caps", "Silymarin", "Amoun", 55),
    ("Turmeric", "500 mg", "Caps", "Curcumin", "EIPICO", 48),
    ("Turmeric Curcumin", "1000 mg", "Caps", "Curcumin", "Amoun", 75),
    ("Boswellia", "400 mg", "Caps", "Boswellia", "EIPICO", 55),
    ("Ginger", "500 mg", "Caps", "Ginger", "EIPICO", 32),
    ("Ginger Root", "550 mg", "Caps", "Ginger", "Amoun", 35),
    ("Peppermint Oil", "Caps", "Caps", "Peppermint Oil", "EIPICO", 38),
    ("Colpermin", "Caps", "Caps", "Peppermint Oil", "Tillotts", 55),
    ("Fennel Oil", "Caps", "Caps", "Fennel Oil", "EIPICO", 32),
    ("Caraway Oil", "Caps", "Caps", "Caraway Oil", "Amoun", 28),
    ("Artichoke", "Tabs", "Tabs", "Artichoke Extract", "EIPICO", 42),
    ("Artichoke Forte", "Tabs", "Tabs", "Artichoke High", "Amoun", 52),
    ("Dandelion", "Tabs", "Tabs", "Dandelion", "EIPICO", 28),
    ("Aloe Vera", "Caps", "Caps", "Aloe Vera", "Amoun", 35),
    ("Aloe Vera Gel", "Gel", "Gel", "Aloe Vera", "EIPICO", 32),
    ("Tea Tree Oil", "Bottle", "Bottle", "Tea Tree Oil", "Amoun", 38),
    ("Echinacea", "Tabs", "Tabs", "Echinacea", "EIPICO", 42),
    ("Echinacea Forte", "Tabs", "Tabs", "Echinacea High", "Amoun", 52),
    ("Astragalus", "Tabs", "Tabs", "Astragalus", "EIPICO", 38),
    ("Ashwagandha", "500 mg", "Caps", "Ashwagandha", "Amoun", 48),
    ("Rhodiola", "Tabs", "Tabs", "Rhodiola", "EIPICO", 55),
    ("Maca Root", "500 mg", "Caps", "Maca", "Amoun", 45),
    ("Tribulus", "Tabs", "Tabs", "Tribulus", "EIPICO", 42),
    ("Horny Goat Weed", "Caps", "Caps", "Epimedium", "Amoun", 48),
    ("L-Arginine", "500 mg", "Caps", "L-Arginine", "EIPICO", 55),
    ("L-Arginine", "1000 mg", "Caps", "L-Arginine", "Amoun", 75),
    ("L-Glutamine", "500 mg", "Caps", "L-Glutamine", "EIPICO", 62),
    ("BCAA", "Tabs", "Tabs", "Branched Chain AA", "Amoun", 85),
    ("Whey Protein", "Powder", "Powder", "Whey Protein", "EIPICO", 125),
    ("Casein Protein", "Powder", "Powder", "Casein", "Amoun", 145),
    ("Creatine", "Powder", "Powder", "Creatine", "EIPICO", 75),
    ("Creatine", "1000 mg", "Caps", "Creatine", "Amoun", 85),
    ("Beta-Alanine", "Tabs", "Tabs", "Beta-Alanine", "EIPICO", 68),
    ("HMB", "Caps", "Caps", "HMB", "Amoun", 78),
    ("Pre-Workout", "Powder", "Powder", "Pre-Workout", "EIPICO", 95),
    ("Post-Workout", "Powder", "Powder", "Post-Workout", "Amoun", 88),
    ("Electrolyte Powder", "Powder", "Powder", "Electrolytes", "EIPICO", 42),
    ("Isotonic Drink", "Powder", "Powder", "Isotonic", "Amoun", 38),
    ("Probiotic 10", "Caps", "Caps", "Probiotics", "EIPICO", 85),
    ("Probiotic Complex", "Caps", "Caps", "Probiotics", "Amoun", 75),
    ("Acidophilus", "Caps", "Caps", "L. Acidophilus", "EIPICO", 55),
    ("Bifidobacterium", "Caps", "Caps", "Bifidobacterium", "Amoun", 58),
    ("Saccharomyces", "Caps", "Caps", "S. Boulardii", "EIPICO", 65),
    ("Bioflor", "Caps", "Caps", "S. Boulardii", "Amoun", 62),
    ("Enterogermina", "5 ml", "Amp", "B. Clausii", "Sanofi", 32),
    ("Enterogermina", "2 billion", "Caps", "B. Clausii", "Sanofi", 42),
    ("Antibiophilus", "Caps", "Caps", "L. Acidophilus", "Bayer", 48),
    ("Lacteol Fort", "Sachets", "Sachets", "L. LB", "Lacteol", 45),
    ("Lacteol Fort", "Caps", "Caps", "L. LB", "Lacteol", 52),
    ("Smecta", "Sachets", "Sachets", "Diosmectite", "Beaufour", 35),
    ("Smecta", "Orange", "Sachets", "Diosmectite", "Beaufour", 38),
    ("Diosmectite", "Sachets", "Sachets", "Diosmectite", "EIPICO", 25),
    ("Diosmect", "Sachets", "Sachets", "Diosmectite", "Amoun", 22),
    ("Pectin", "Sachets", "Sachets", "Pectin", "EIPICO", 18),
    ("Charcoal", "250 mg", "Tabs", "Activated Charcoal", "EIPICO", 12),
    ("Charcoal", "Activated", "Caps", "Activated Charcoal", "Amoun", 15),
    ("Carbosorb", "250 mg", "Tabs", "Activated Charcoal", "Reckitt", 22),
    ("Albendazole", "200 mg", "Tabs", "Albendazole", "EIPICO", 15),
    ("Albendazole", "400 mg", "Tabs", "Albendazole", "EIPICO", 22),
    ("Zentel", "200 mg", "Tabs", "Albendazole", "GSK", 28),
    ("Zentel", "400 mg", "Tabs", "Albendazole", "GSK", 38),
    ("Zentel Susp.", "400 mg/10ml", "Susp", "Albendazole", "GSK", 32),
    ("Albendacor", "400 mg", "Tabs", "Albendazole", "Amoun", 18),
    ("Mebendazole", "100 mg", "Tabs", "Mebendazole", "EIPICO", 12),
    ("Mebendazole", "500 mg", "Tabs", "Mebendazole", "EIPICO", 18),
    ("Vermox", "100 mg", "Tabs", "Mebendazole", "Janssen", 22),
    ("Vermox", "500 mg", "Tabs", "Mebendazole", "Janssen", 32),
    ("Vermox Susp.", "100 mg/5ml", "Susp", "Mebendazole", "Janssen", 28),
    ("Mebendacor", "500 mg", "Tabs", "Mebendazole", "Amoun", 15),
    ("Praziquantel", "600 mg", "Tabs", "Praziquantel", "EIPICO", 55),
    ("Biltricide", "600 mg", "Tabs", "Praziquantel", "Bayer", 85),
    ("Niclosamide", "500 mg", "Tabs", "Niclosamide", "EIPICO", 22),
    ("Yomesan", "500 mg", "Tabs", "Niclosamide", "Bayer", 38),
    ("Piperazine", "500 mg", "Tabs", "Piperazine", "EIPICO", 15),
    ("Pyrantel", "125 mg", "Tabs", "Pyrantel Pamoate", "EIPICO", 18),
    ("Pyrantel", "250 mg", "Tabs", "Pyrantel Pamoate", "EIPICO", 25),
    ("Combantrin", "125 mg", "Tabs", "Pyrantel Pamoate", "Pfizer", 32),
    ("Combantrin", "250 mg", "Tabs", "Pyrantel Pamoate", "Pfizer", 42),
    ("Combantrin Susp.", "50 mg/5ml", "Susp", "Pyrantel Pamoate", "Pfizer", 35),
    ("Ivermectin", "3 mg", "Tabs", "Ivermectin", "EIPICO", 35),
    ("Ivermectin", "6 mg", "Tabs", "Ivermectin", "EIPICO", 55),
    ("Stromectol", "3 mg", "Tabs", "Ivermectin", "MSD", 55),
    ("Stromectol", "6 mg", "Tabs", "Ivermectin", "MSD", 85),
    ("Ivercor", "6 mg", "Tabs", "Ivermectin", "Amoun", 48),
    ("Diethylcarbamazine", "50 mg", "Tabs", "Diethylcarbamazine", "EIPICO", 18),
    ("DEC", "100 mg", "Tabs", "Diethylcarbamazine", "Amoun", 15),
]

for drug_data in additional_drugs:
    add_drug(*drug_data)

# Save
output = {"drugs": drugs}
with open('data/egyptian-drugs-gtin-expanded.json', 'w', encoding='utf-8') as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print(f"Total drugs now: {len(drugs)}")
