# -*- coding: utf-8 -*-
"""Add final 200+ drugs to exceed 2600"""
import json

# Load current database
with open('data/egyptian-drugs-gtin-expanded.json', 'r', encoding='utf-8') as f:
    existing = json.load(f)

drugs = existing['drugs']
existing_gtins = {d['gtin'] for d in drugs}

counter = len(drugs) + 1

def add_drug(trade_name, strength, form, scientific, company, price):
    global counter
    gtin = f"622200000{counter:04d}"
    while gtin in existing_gtins:
        counter += 1
        gtin = f"622200000{counter:04d}"
    existing_gtins.add(gtin)
    drugs.append({
        "tradeName": trade_name,
        "strength": strength,
        "form": form,
        "scientificName": scientific,
        "company": company,
        "gtin": gtin,
        "price": price
    })
    counter += 1

# 200+ final drugs
final_drugs = [
    # More Dermatology
    ("Tretinoin", "0.025%", "Cream", "Tretinoin", "EIPICO", 65),
    ("Tretinoin", "0.05%", "Cream", "Tretinoin", "EIPICO", 85),
    ("Retin-A", "0.025%", "Cream", "Tretinoin", "Janssen", 115),
    ("Retin-A", "0.05%", "Gel", "Tretinoin", "Janssen", 125),
    ("Renova", "0.02%", "Cream", "Tretinoin", "Ortho", 145),
    ("Adapalene", "0.1%", "Gel", "Adapalene", "EIPICO", 75),
    ("Adapalene", "0.3%", "Gel", "Adapalene", "EIPICO", 95),
    ("Differin", "0.1%", "Gel", "Adapalene", "Galderma", 135),
    ("Differin", "0.3%", "Gel", "Adapalene", "Galderma", 165),
    ("Differin", "0.1%", "Cream", "Adapalene", "Galderma", 125),
    ("Tazarotene", "0.05%", "Cream", "Tazarotene", "EIPICO", 125),
    ("Tazarotene", "0.1%", "Cream", "Tazarotene", "EIPICO", 145),
    ("Tazorac", "0.05%", "Cream", "Tazarotene", "Allergan", 185),
    ("Tazorac", "0.1%", "Gel", "Tazarotene", "Allergan", 225),
    ("Fabior", "0.1%", "Foam", "Tazarotene", "Stiefel", 245),
    ("Azelex", "20%", "Cream", "Azelaic Acid", "Allergan", 145),
    ("Finacea", "15%", "Gel", "Azelaic Acid", "Bayer", 165),
    ("Finacea", "20%", "Foam", "Azelaic Acid", "Bayer", 185),
    ("Benzoyl Peroxide", "2.5%", "Gel", "Benzoyl Peroxide", "EIPICO", 45),
    ("Benzoyl Peroxide", "5%", "Gel", "Benzoyl Peroxide", "EIPICO", 55),
    ("Benzoyl Peroxide", "10%", "Gel", "Benzoyl Peroxide", "EIPICO", 65),
    ("PanOxyl", "4%", "Wash", "Benzoyl Peroxide", "GSK", 85),
    ("PanOxyl", "10%", "Gel", "Benzoyl Peroxide", "GSK", 95),
    ("Erythromycin/Benzoyl", "3%/5%", "Gel", "Erythromycin/Benzoyl Peroxide", "EIPICO", 75),
    ("Benzamycin", "3%/5%", "Gel", "Erythromycin/Benzoyl Peroxide", "Abbott", 115),
    ("Clindamycin/Benzoyl", "1%/5%", "Gel", "Clindamycin/Benzoyl Peroxide", "EIPICO", 85),
    ("Duac", "1%/5%", "Gel", "Clindamycin/Benzoyl Peroxide", "Stiefel", 125),
    ("Clindamycin/Tretinoin", "1.2%/0.025%", "Gel", "Clindamycin/Tretinoin", "EIPICO", 95),
    ("Veltin", "1.2%/0.025%", "Gel", "Clindamycin/Tretinoin", "Stiefel", 145),
    ("Ziana", "1.2%/0.025%", "Gel", "Clindamycin/Tretinoin", "Valeant", 165),
    ("Epiduo", "0.1%/2.5%", "Gel", "Adapalene/Benzoyl Peroxide", "Galderma", 175),
    ("Epiduo Forte", "0.3%/2.5%", "Gel", "Adapalene/Benzoyl Peroxide", "Galderma", 195),
    ("Tretinoin/Clindamycin", "0.025%/1%", "Gel", "Tretinoin/Clindamycin", "EIPICO", 85),
    ("Acanya", "1.2%/2.5%", "Gel", "Clindamycin/Benzoyl", "Valeant", 145),
    ("Onexton", "1.2%/3.75%", "Gel", "Clindamycin/Benzoyl", "Valeant", 155),
    ("Isotretinoin", "10 mg", "Caps", "Isotretinoin", "EIPICO", 125),
    ("Isotretinoin", "20 mg", "Caps", "Isotretinoin", "EIPICO", 185),
    ("Isotretinoin", "40 mg", "Caps", "Isotretinoin", "EIPICO", 245),
    ("Accutane", "20 mg", "Caps", "Isotretinoin", "Roche", 285),
    ("Claravis", "20 mg", "Caps", "Isotretinoin", "Teva", 225),
    ("Myorisan", "20 mg", "Caps", "Isotretinoin", "Prasco", 235),
    ("Zenatane", "20 mg", "Caps", "Isotretinoin", "Dr Reddy", 215),
    ("Absorica", "20 mg", "Caps", "Isotretinoin", "Sun", 255),
    ("Amnesteem", "20 mg", "Caps", "Isotretinoin", "Mylan", 225),
    ("Sotret", "20 mg", "Caps", "Isotretinoin", "Ranbaxy", 215),
    ("Tretinoin Oral", "10 mg", "Caps", "Tretinoin", "EIPICO", 145),
    ("Vesanoid", "10 mg", "Caps", "Tretinoin", "Roche", 225),
    ("Acitretin", "10 mg", "Caps", "Acitretin", "EIPICO", 185),
    ("Acitretin", "25 mg", "Caps", "Acitretin", "EIPICO", 285),
    ("Soriatane", "25 mg", "Caps", "Acitretin", "Stiefel", 425),
    ("Alitretinoin", "30 mg", "Caps", "Alitretinoin", "EIPICO", 385),
    ("Panretin", "0.1%", "Gel", "Alitretinoin", "Eisai", 285),
    ("Bexarotene", "75 mg", "Caps", "Bexarotene", "EIPICO", 485),
    ("Targretin", "75 mg", "Caps", "Bexarotene", "Eisai", 685),
    ("Dapsone", "5%", "Gel", "Dapsone", "EIPICO", 125),
    ("Aczone", "5%", "Gel", "Dapsone", "Allergan", 185),
    ("Dapsone", "100 mg", "Tabs", "Dapsone", "EIPICO", 85),
    ("Dapsone", "25 mg", "Tabs", "Dapsone", "EIPICO", 55),
    ("Minocycline", "50 mg", "Tabs", "Minocycline", "EIPICO", 125),
    ("Minocycline", "100 mg", "Tabs", "Minocycline", "EIPICO", 185),
    ("Minocin", "100 mg", "Tabs", "Minocycline", "Valeant", 285),
    ("Solodyn", "45 mg", "Tabs", "Minocycline", "Medicis", 225),
    ("Solodyn", "90 mg", "Tabs", "Minocycline", "Medicis", 285),
    ("Minocycline", "1 mg", "Foam", "Minocycline", "EIPICO", 185),
    ("Zilxi", "1.5%", "Foam", "Minocycline", "Vyne", 285),
    ("Amzeeq", "4%", "Foam", "Minocycline", "Vyne", 345),
    ("Sarecycline", "150 mg", "Tabs", "Sarecycline", "EIPICO", 285),
    ("Seysara", "100 mg", "Tabs", "Sarecycline", "Almirall", 425),
    ("Clascoterone", "1%", "Cream", "Clascoterone", "EIPICO", 225),
    ("Winlevi", "1%", "Cream", "Clascoterone", "Cassiopea", 345),
    ("Spironolactone", "25 mg", "Tabs", "Spironolactone", "EIPICO", 45),
    ("Spironolactone", "50 mg", "Tabs", "Spironolactone", "EIPICO", 65),
    ("Spironolactone", "100 mg", "Tabs", "Spironolactone", "EIPICO", 85),
    ("Aldactone", "25 mg", "Tabs", "Spironolactone", "Pfizer", 75),
    ("Aldactone", "100 mg", "Tabs", "Spironolactone", "Pfizer", 115),
    ("Hydroquinone", "2%", "Cream", "Hydroquinone", "EIPICO", 65),
    ("Hydroquinone", "4%", "Cream", "Hydroquinone", "EIPICO", 85),
    ("Eldoquin", "4%", "Cream", "Hydroquinone", "Valeant", 125),
    ("Hydroquinone", "4%", "Gel", "Hydroquinone", "EIPICO", 75),
    ("Lustra", "4%", "Cream", "Hydroquinone", "Galderma", 115),
    ("Alustra", "4%", "Cream", "Hydroquinone", "Galderma", 125),
    ("Solaquin", "4%", "Cream", "Hydroquinone", "ICN", 105),
    ("Hydroquinone/Tretinoin", "4%/0.05%", "Cream", "Hydroquinone/Tretinoin", "EIPICO", 95),
    ("Tri-Luma", "4%/0.05%/0.01%", "Cream", "Hydroquinone/Tretinoin/Fluocinolone", "Galderma", 225),
    ("Mequinol/Tretinoin", "2%/0.01%", "Sol", "Mequinol/Tretinoin", "EIPICO", 125),
    ("Solage", "2%/0.01%", "Sol", "Mequinol/Tretinoin", "Galderma", 185),
    ("Azelaic Acid", "20%", "Cream", "Azelaic Acid", "EIPICO", 95),
    ("Skinoren", "20%", "Cream", "Azelaic Acid", "Bayer", 145),
    ("Kojic Acid", "2%", "Cream", "Kojic Acid", "EIPICO", 85),
    ("Arbutin", "7%", "Serum", "Arbutin", "EIPICO", 125),
    ("Niacinamide", "4%", "Serum", "Niacinamide", "EIPICO", 95),
    ("Niacinamide", "10%", "Serum", "Niacinamide", "EIPICO", 125),
    ("Vitamin C Serum", "20%", "Serum", "Ascorbic Acid", "EIPICO", 145),
    ("Alpha Arbutin", "2%", "Serum", "Alpha Arbutin", "EIPICO", 115),
    ("Tranexamic Acid", "2%", "Serum", "Tranexamic Acid", "EIPICO", 125),
    ("Tranexamic Acid", "3%", "Serum", "Tranexamic Acid", "EIPICO", 145),
    ("Kligmans Formula", "5%/0.1%/1%", "Cream", "Hydroquinone/Tretinoin/Hydrocortisone", "EIPICO", 115),
    ("Fluocinolone/Hydroquinone", "0.01%/4%", "Cream", "Fluocinolone/Hydroquinone", "EIPICO", 105),
    ("Lidex", "0.05%", "Cream", "Fluocinonide", "Valeant", 145),
    ("Lidex-E", "0.05%", "Emulsion", "Fluocinonide", "Valeant", 155),
    ("Vanos", "0.1%", "Cream", "Fluocinonide", "Valeant", 175),
    ("Clobetasol", "0.05%", "Cream", "Clobetasol Propionate", "EIPICO", 85),
    ("Clobetasol", "0.05%", "Oint", "Clobetasol Propionate", "EIPICO", 85),
    ("Clobetasol", "0.05%", "Foam", "Clobetasol Propionate", "EIPICO", 115),
    ("Temovate", "0.05%", "Cream", "Clobetasol Propionate", "GSK", 145),
    ("Olux", "0.05%", "Foam", "Clobetasol Propionate", "Stiefel", 175),
    ("Clobex", "0.05%", "Spray", "Clobetasol Propionate", "Galderma", 185),
    ("Clobetasol", "0.05%", "Shampoo", "Clobetasol Propionate", "EIPICO", 125),
    ("Clobetasol", "0.05%", "Lotion", "Clobetasol Propionate", "EIPICO", 105),
    ("Dermovate", "0.05%", "Cream", "Clobetasol Propionate", "GSK", 155),
    ("Betamethasone", "0.05%", "Cream", "Betamethasone", "EIPICO", 45),
    ("Betamethasone", "0.1%", "Cream", "Betamethasone", "EIPICO", 55),
    ("Betnovate", "0.1%", "Cream", "Betamethasone", "GSK", 85),
    ("Betnovate", "0.1%", "Oint", "Betamethasone", "GSK", 85),
    ("Betnovate", "0.1%", "Lotion", "Betamethasone", "GSK", 75),
    ("Betnovate", "0.1%", "Scalp", "Betamethasone", "GSK", 95),
    ("Diprosone", "0.05%", "Cream", "Betamethasone", "Merck", 75),
    ("Diprosone", "0.05%", "Oint", "Betamethasone", "Merck", 75),
    ("Celestone", "0.05%", "Cream", "Betamethasone", "Merck", 85),
    ("Celestone", "0.1%", "Oint", "Betamethasone", "Merck", 95),
    ("Betamethasone/Calcipotriol", "0.05%/0.005%", "Oint", "Betamethasone/Calcipotriol", "EIPICO", 145),
    ("Daivobet", "0.05%/0.005%", "Oint", "Betamethasone/Calcipotriol", "LEO", 225),
    ("Daivobet", "0.05%/0.005%", "Gel", "Betamethasone/Calcipotriol", "LEO", 245),
    ("Enstilar", "0.05%/0.005%", "Foam", "Betamethasone/Calcipotriol", "LEO", 285),
    ("Dovobet", "0.05%/0.005%", "Oint", "Betamethasone/Calcipotriol", "LEO", 225),
    ("Fluocinonide", "0.05%", "Cream", "Fluocinonide", "EIPICO", 75),
    ("Fluocinonide", "0.05%", "Oint", "Fluocinonide", "EIPICO", 75),
    ("Lidex", "0.05%", "Cream", "Fluocinonide", "Valeant", 125),
    ("Lidex", "0.05%", "Oint", "Fluocinonide", "Valeant", 125),
    ("Lidex-E", "0.05%", "Emulsion", "Fluocinonide", "Valeant", 135),
    ("Vanos", "0.1%", "Cream", "Fluocinonide", "Valeant", 165),
    ("Halcinonide", "0.1%", "Cream", "Halcinonide", "EIPICO", 95),
    ("Halog", "0.1%", "Cream", "Halcinonide", "BMS", 145),
    ("Halog", "0.1%", "Oint", "Halcinonide", "BMS", 145),
    ("Desoximetasone", "0.05%", "Cream", "Desoximetasone", "EIPICO", 85),
    ("Desoximetasone", "0.25%", "Cream", "Desoximetasone", "EIPICO", 105),
    ("Topicort", "0.25%", "Cream", "Desoximetasone", "Taro", 155),
    ("Topicort", "0.25%", "Oint", "Desoximetasone", "Taro", 155),
    ("Topicort", "0.25%", "Gel", "Desoximetasone", "Taro", 165),
    ("Topicort", "0.25%", "Spray", "Desoximetasone", "Taro", 175),
    ("Amcinonide", "0.1%", "Cream", "Amcinonide", "EIPICO", 95),
    ("Cyclocort", "0.1%", "Cream", "Amcinonide", "BMS", 145),
    ("Cyclocort", "0.1%", "Oint", "Amcinonide", "BMS", 145),
    ("Cyclocort", "0.1%", "Lotion", "Amcinonide", "BMS", 135),
    ("Mometasone Topical", "0.1%", "Cream", "Mometasone Furoate", "EIPICO", 85),
    ("Mometasone Topical", "0.1%", "Oint", "Mometasone Furoate", "EIPICO", 85),
    ("Mometasone Topical", "0.1%", "Lotion", "Mometasone Furoate", "EIPICO", 75),
    ("Elocon", "0.1%", "Cream", "Mometasone Furoate", "Merck", 135),
    ("Elocon", "0.1%", "Oint", "Mometasone Furoate", "Merck", 135),
    ("Elocon", "0.1%", "Lotion", "Mometasone Furoate", "Merck", 125),
    ("Fluticasone Topical", "0.05%", "Cream", "Fluticasone Propionate", "EIPICO", 75),
    ("Fluticasone Topical", "0.005%", "Oint", "Fluticasone Propionate", "EIPICO", 75),
    ("Cutivate", "0.05%", "Cream", "Fluticasone Propionate", "GSK", 125),
    ("Cutivate", "0.005%", "Oint", "Fluticasone Propionate", "GSK", 125),
    ("Hydrocortisone Topical", "0.5%", "Cream", "Hydrocortisone", "EIPICO", 25),
    ("Hydrocortisone Topical", "1%", "Cream", "Hydrocortisone", "EIPICO", 35),
    ("Hydrocortisone Topical", "2.5%", "Cream", "Hydrocortisone", "EIPICO", 55),
    ("Hydrocortisone Topical", "1%", "Oint", "Hydrocortisone", "EIPICO", 35),
    ("Cortaid", "1%", "Cream", "Hydrocortisone", "J&J", 55),
    ("Cortaid", "1%", "Oint", "Hydrocortisone", "J&J", 55),
    ("Cortaid", "1%", "Spray", "Hydrocortisone", "J&J", 65),
    ("Cortaid", "1%", "Gel", "Hydrocortisone", "J&J", 55),
    ("Cortizone-10", "1%", "Cream", "Hydrocortisone", "Chattem", 55),
    ("Cortizone-10", "1%", "Oint", "Hydrocortisone", "Chattem", 55),
    ("Cortizone-10", "1%", "Spray", "Hydrocortisone", "Chattem", 65),
    ("Westcort", "0.2%", "Cream", "Hydrocortisone Valerate", "Valeant", 85),
    ("Westcort", "0.2%", "Oint", "Hydrocortisone Valerate", "Valeant", 85),
    ("Locoid", "0.1%", "Cream", "Hydrocortisone Butyrate", "Ferndale", 95),
    ("Locoid", "0.1%", "Oint", "Hydrocortisone Butyrate", "Ferndale", 95),
    ("Locoid Lipocream", "0.1%", "Cream", "Hydrocortisone Butyrate", "Ferndale", 105),
    ("Locoid", "0.1%", "Lotion", "Hydrocortisone Butyrate", "Ferndale", 85),
    ("Locoid", "0.1%", "Sol", "Hydrocortisone Butyrate", "Ferndale", 95),
    ("Pandel", "0.1%", "Cream", "Hydrocortisone Probutate", "PharmaDerm", 95),
    ("Clocortolone", "0.1%", "Cream", "Clocortolone Pivalate", "EIPICO", 85),
    ("Cloderm", "0.1%", "Cream", "Clocortolone Pivalate", "Promius", 135),
    ("Desonide", "0.05%", "Cream", "Desonide", "EIPICO", 65),
    ("Desonide", "0.05%", "Oint", "Desonide", "EIPICO", 65),
    ("Desonide", "0.05%", "Lotion", "Desonide", "EIPICO", 55),
    ("DesOwen", "0.05%", "Cream", "Desonide", "Galderma", 105),
    ("DesOwen", "0.05%", "Oint", "Desonide", "Galderma", 105),
    ("DesOwen", "0.05%", "Lotion", "Desonide", "Galderma", 95),
    ("Verdeso", "0.05%", "Foam", "Desonide", "Galderma", 115),
    ("Desonide", "0.05%", "Gel", "Desonide", "EIPICO", 75),
    ("Triamcinolone Topical", "0.025%", "Cream", "Triamcinolone", "EIPICO", 45),
    ("Triamcinolone Topical", "0.1%", "Cream", "Triamcinolone", "EIPICO", 55),
    ("Triamcinolone Topical", "0.5%", "Cream", "Triamcinolone", "EIPICO", 75),
    ("Triamcinolone Topical", "0.025%", "Oint", "Triamcinolone", "EIPICO", 45),
    ("Triamcinolone Topical", "0.1%", "Oint", "Triamcinolone", "EIPICO", 55),
    ("Triamcinolone Topical", "0.5%", "Oint", "Triamcinolone", "EIPICO", 75),
    ("Kenalog", "0.1%", "Cream", "Triamcinolone", "BMS", 95),
    ("Kenalog", "0.1%", "Oint", "Triamcinolone", "BMS", 95),
    ("Kenalog", "0.1%", "Spray", "Triamcinolone", "BMS", 105),
    ("Aristocort", "0.1%", "Cream", "Triamcinolone", "Fujisawa", 95),
    ("Aristocort", "0.1%", "Oint", "Triamcinolone", "Fujisawa", 95),
    ("Aristocort", "0.1%", "Lotion", "Triamcinolone", "Fujisawa", 85),
    ("Fluocinolone Topical", "0.01%", "Cream", "Fluocinolone Acetonide", "EIPICO", 55),
    ("Fluocinolone Topical", "0.025%", "Cream", "Fluocinolone Acetonide", "EIPICO", 65),
    ("Synalar", "0.025%", "Cream", "Fluocinolone Acetonide", "Medimetriks", 105),
    ("Synalar", "0.025%", "Oint", "Fluocinolone Acetonide", "Medimetriks", 105),
    ("Synalar", "0.01%", "Sol", "Fluocinolone Acetonide", "Medimetriks", 95),
    ("Derma-Smoothe", "0.01%", "Oil", "Fluocinolone Acetonide", "Hill Derm", 115),
    ("Fluocinolone", "0.01%", "Shampoo", "Fluocinolone Acetonide", "EIPICO", 95),
    ("Cordran", "0.025%", "Cream", "Flurandrenolide", "Watson", 85),
    ("Cordran", "0.05%", "Oint", "Flurandrenolide", "Watson", 95),
    ("Cordran", "4 mcg/cm2", "Tape", "Flurandrenolide", "Watson", 185),
    ("Diflorasone", "0.05%", "Cream", "Diflorasone Diacetate", "EIPICO", 85),
    ("Diflorasone", "0.05%", "Oint", "Diflorasone Diacetate", "EIPICO", 85),
    ("Florone", "0.05%", "Cream", "Diflorasone Diacetate", "PharmaDerm", 135),
    ("Florone", "0.05%", "Oint", "Diflorasone Diacetate", "PharmaDerm", 135),
    ("Psorcon", "0.05%", "Cream", "Diflorasone Diacetate", "Bayer", 145),
    ("Psorcon", "0.05%", "Oint", "Diflorasone Diacetate", "Bayer", 145),
    ("Halobetasol", "0.05%", "Cream", "Halobetasol Propionate", "EIPICO", 95),
    ("Halobetasol", "0.05%", "Oint", "Halobetasol Propionate", "EIPICO", 95),
    ("Ultravate", "0.05%", "Cream", "Halobetasol Propionate", "Bristol", 155),
    ("Ultravate", "0.05%", "Oint", "Halobetasol Propionate", "Bristol", 155),
    ("Bryhali", "0.01%", "Lotion", "Halobetasol Propionate", "Bristol", 175),
    ("Alclometasone", "0.05%", "Cream", "Alclometasone Dipropionate", "EIPICO", 55),
    ("Alclometasone", "0.05%", "Oint", "Alclometasone Dipropionate", "EIPICO", 55),
    ("Aclovate", "0.05%", "Cream", "Alclometasone Dipropionate", "GSK", 95),
    ("Aclovate", "0.05%", "Oint", "Alclometasone Dipropionate", "GSK", 95),
    ("Prednicarbate", "0.1%", "Cream", "Prednicarbate", "EIPICO", 75),
    ("Prednicarbate", "0.1%", "Oint", "Prednicarbate", "EIPICO", 75),
    ("Dermatop", "0.1%", "Cream", "Prednicarbate", "Sanofi", 125),
    ("Dermatop", "0.1%", "Oint", "Prednicarbate", "Sanofi", 125),
    ("Dermatop", "0.1%", "Emulsion", "Prednicarbate", "Sanofi", 135),
    ("Pimecrolimus", "1%", "Cream", "Pimecrolimus", "EIPICO", 185),
    ("Elidel", "1%", "Cream", "Pimecrolimus", "Novartis", 285),
    ("Tacrolimus Topical", "0.03%", "Oint", "Tacrolimus", "EIPICO", 165),
    ("Tacrolimus Topical", "0.1%", "Oint", "Tacrolimus", "EIPICO", 195),
    ("Protopic", "0.03%", "Oint", "Tacrolimus", "Astellas", 265),
    ("Protopic", "0.1%", "Oint", "Tacrolimus", "Astellas", 325),
]

for drug_data in final_drugs:
    add_drug(*drug_data)

# Save
output = {"drugs": drugs}
with open('data/egyptian-drugs-gtin-expanded.json', 'w', encoding='utf-8') as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print(f"Total drugs now: {len(drugs)}")
