# -*- coding: utf-8 -*-
"""Expand Egyptian drug database to 500+ entries with GTIN"""
import json

# Load existing
with open('data/egyptian-drugs-gtin.json', 'r', encoding='utf-8') as f:
    existing = json.load(f)

drugs = existing['drugs']
existing_gtins = {d['gtin'] for d in drugs}

counter = len(drugs) + 1

def add_drug(trade_name, strength, form, scientific, company, price):
    global counter
    gtin = f"622200000{counter:04d}"
    while gtin in existing_gtins:
        counter += 1
        gtin = f"622200000{counter:04d}"
    existing_gtins.add(gtin)
    drugs.append({
        "tradeName": trade_name,
        "strength": strength,
        "form": form,
        "scientificName": scientific,
        "company": company,
        "gtin": gtin,
        "price": price
    })
    counter += 1

# Additional 400+ Egyptian drugs
additional_drugs = [
    # More Analgesics
    ("Panadol", "250 mg", "Tabs", "Paracetamol", "GSK", 23),
    ("Panadol", "1000 mg", "Tabs", "Paracetamol", "GSK", 71),
    ("Panadol Forte", "500 mg", "Tabs", "Paracetamol", "GSK", 59),
    ("Panadol Sinus", "500/30 mg", "Tabs", "Paracetamol/Pseudoephedrine", "GSK", 46),
    ("Panadol Night", "500/25 mg", "Tabs", "Paracetamol/Diphenhydramine", "GSK", 52),
    ("Panadol Children", "120 mg/5ml", "Syrup", "Paracetamol", "GSK", 28),
    ("Panadol Baby", "100 mg/5ml", "Syrup", "Paracetamol", "GSK", 32),
    ("Cetal", "250 mg", "Tabs", "Paracetamol", "EIPICO", 15),
    ("Cetal", "1000 mg", "Tabs", "Paracetamol", "EIPICO", 38),
    ("Cetal Cold", "Day", "Tabs", "Paracetamol/Pseudoephedrine", "EIPICO", 28),
    ("Cetal Night", "Night", "Tabs", "Paracetamol/Diphenhydramine", "EIPICO", 32),
    ("Adol", "250 mg", "Tabs", "Paracetamol", "Julphar", 15),
    ("Adol", "1000 mg", "Tabs", "Paracetamol", "Julphar", 38),
    ("Adol", "120 mg/5ml", "Syrup", "Paracetamol", "Julphar", 18),
    ("Adol", "100 mg", "Supp", "Paracetamol", "Julphar", 20),
    ("Adol", "250 mg", "Supp", "Paracetamol", "Julphar", 24),
    ("Abimol", "500 mg", "Tabs", "Paracetamol", "GSK", 18),
    ("Paramol", "500 mg", "Tabs", "Paracetamol", "Amoun", 20),
    ("Doliprane", "500 mg", "Tabs", "Paracetamol", "Sanofi", 35),
    ("Doliprane", "1000 mg", "Tabs", "Paracetamol", "Sanofi", 55),
    ("Tylol", "500 mg", "Tabs", "Paracetamol", "EIPICO", 19),
    ("Fevadol", "500 mg", "Tabs", "Paracetamol", "Julphar", 19),
    ("Perfalgan", "10 mg/ml", "IV", "Paracetamol", "BMS", 125),
    
    # More NSAIDs
    ("Brufen", "200 mg", "Tabs", "Ibuprofen", "Abbott", 22),
    ("Brufen", "800 mg", "Tabs", "Ibuprofen", "Abbott", 65),
    ("Brufen", "100 mg/5ml", "Syrup", "Ibuprofen", "Abbott", 28),
    ("Ibuflex", "200 mg", "Tabs", "Ibuprofen", "Eva", 28),
    ("Ibuflex", "400 mg", "Tabs", "Ibuprofen", "Eva", 38),
    ("Ibugesic", "200 mg", "Tabs", "Ibuprofen", "Medical Union", 25),
    ("Ibugesic", "400 mg", "Tabs", "Ibuprofen", "Medical Union", 35),
    ("Profen", "400 mg", "Tabs", "Ibuprofen", "Delta", 30),
    ("Voltaren", "25 mg", "Tabs", "Diclofenac", "Novartis", 35),
    ("Voltaren", "100 mg", "SR Tabs", "Diclofenac", "Novartis", 75),
    ("Voltaren", "1%", "Gel", "Diclofenac", "Novartis", 65),
    ("Voltaren Emulgel", "1%", "Gel", "Diclofenac", "Novartis", 68),
    ("Diclofen", "25 mg", "Tabs", "Diclofenac", "EIPICO", 25),
    ("Diclofen", "50 mg", "Tabs", "Diclofenac", "EIPICO", 32),
    ("Diclofen", "75 mg", "Tabs", "Diclofenac", "EIPICO", 38),
    ("Diclofen Retard", "100 mg", "Tabs", "Diclofenac", "EIPICO", 48),
    ("Diclomax", "25 mg", "Tabs", "Diclofenac", "Medical Union", 28),
    ("Diclomax", "50 mg", "Tabs", "Diclofenac", "Medical Union", 36),
    ("Diclomax SR", "100 mg", "Tabs", "Diclofenac", "Medical Union", 48),
    ("Olfen", "50 mg", "Tabs", "Diclofenac", "Mepha", 42),
    ("Olfen", "75 mg", "Tabs", "Diclofenac", "Mepha", 48),
    ("Olfen", "100 mg", "SR", "Diclofenac", "Mepha", 58),
    ("Ketofan", "25 mg", "Tabs", "Ketoprofen", "Amoun", 22),
    ("Ketofan SR", "200 mg", "Caps", "Ketoprofen", "Amoun", 42),
    ("Ketofan", "2.5%", "Gel", "Ketoprofen", "Amoun", 38),
    ("Profenid", "100 mg", "Tabs", "Ketoprofen", "Sanofi", 45),
    ("Profenid", "200 mg", "SR", "Ketoprofen", "Sanofi", 65),
    ("Profenid", "1%", "Gel", "Ketoprofen", "Sanofi", 55),
    ("Catafast", "50 mg", "Sachet", "Diclofenac K", "Novartis", 54),
    ("Aspirin", "300 mg", "Tabs", "Aspirin", "GSK", 18),
    ("Aspirin", "500 mg", "Tabs", "Aspirin", "GSK", 25),
    ("Aspirin Cardio", "100 mg", "Tabs", "Aspirin", "Bayer", 35),
    ("Aspirin Protect", "100 mg", "Tabs", "Aspirin", "Bayer", 38),
    ("Aspocid", "100 mg", "Tabs", "Aspirin", "Sandoz", 32),
    ("Aspegic", "100 mg", "Sachet", "Aspirin", "Sanofi", 38),
    ("Aspegic", "500 mg", "Sachet", "Aspirin", "Sanofi", 48),
    ("Aspegic", "1000 mg", "Sachet", "Aspirin", "Sanofi", 65),
    ("Naprosyn", "250 mg", "Tabs", "Naproxen", "Roche", 42),
    ("Naprosyn", "500 mg", "Tabs", "Naproxen", "Roche", 55),
    ("Naprosyn", "750 mg", "SR", "Naproxen", "Roche", 75),
    ("Naproxen", "250 mg", "Tabs", "Naproxen", "EIPICO", 32),
    ("Naproxen", "500 mg", "Tabs", "Naproxen", "EIPICO", 38),
    ("Proxen", "250 mg", "Tabs", "Naproxen", "Medical Union", 35),
    ("Proxen", "500 mg", "Tabs", "Naproxen", "Medical Union", 45),
    ("Celebrex", "100 mg", "Caps", "Celecoxib", "Pfizer", 145),
    ("Celebrex", "200 mg", "Caps", "Celecoxib", "Pfizer", 180),
    ("Celebrex", "400 mg", "Caps", "Celecoxib", "Pfizer", 225),
    ("Celecoxib", "200 mg", "Caps", "Celecoxib", "EIPICO", 120),
    ("Arcoxia", "60 mg", "Tabs", "Etoricoxib", "Merck", 125),
    ("Arcoxia", "90 mg", "Tabs", "Etoricoxib", "Merck", 145),
    ("Arcoxia", "120 mg", "Tabs", "Etoricoxib", "Merck", 165),
    ("Etoricoxib", "90 mg", "Tabs", "Etoricoxib", "EIPICO", 95),
    ("Mobic", "7.5 mg", "Tabs", "Meloxicam", "Boehringer", 48),
    ("Mobic", "15 mg", "Tabs", "Meloxicam", "Boehringer", 65),
    ("Meloxicam", "7.5 mg", "Tabs", "Meloxicam", "EIPICO", 32),
    ("Meloxicam", "15 mg", "Tabs", "Meloxicam", "EIPICO", 42),
    ("Movatec", "7.5 mg", "Tabs", "Meloxicam", "Medical Union", 36),
    ("Movatec", "15 mg", "Tabs", "Meloxicam", "Medical Union", 48),
    
    # Opioids
    ("Tramadol", "50 mg", "Caps", "Tramadol", "EIPICO", 35),
    ("Tramadol", "100 mg", "Caps", "Tramadol", "EIPICO", 55),
    ("Tramadol SR", "100 mg", "Tabs", "Tramadol", "EIPICO", 65),
    ("Tramadol", "100 mg/2ml", "Amp", "Tramadol", "EIPICO", 45),
    ("Tramal", "50 mg", "Caps", "Tramadol", "Grunenthal", 55),
    ("Tramal", "100 mg", "Caps", "Tramadol", "Grunenthal", 75),
    ("Tramal SR", "100 mg", "Tabs", "Tramadol", "Grunenthal", 85),
    ("Tramal", "100 mg/2ml", "Amp", "Tramadol", "Grunenthal", 55),
    ("Tramacet", "37.5/325 mg", "Tabs", "Tramadol/Paracetamol", "Grunenthal", 72),
    ("Codeine", "30 mg", "Tabs", "Codeine Phosphate", "EIPICO", 32),
    ("Panadeine", "500/10 mg", "Tabs", "Paracetamol/Codeine", "GSK", 42),
    
    # More Antibiotics - Penicillins
    ("Augmentin", "375 mg", "Tabs", "Amoxicillin/Clavulanate", "GSK", 65),
    ("Augmentin ES", "600 mg/5ml", "Susp", "Amoxicillin/Clavulanate", "GSK", 95),
    ("Hibiotic", "625 mg", "Tabs", "Amoxicillin/Clavulanate", "Amoun", 75),
    ("Hibiotic", "375 mg", "Tabs", "Amoxicillin/Clavulanate", "Amoun", 55),
    ("Hibiotic Forte", "457 mg/5ml", "Susp", "Amoxicillin/Clavulanate", "Amoun", 68),
    ("Megamox", "625 mg", "Tabs", "Amoxicillin/Clavulanate", "Hikma", 82),
    ("Megamox", "375 mg", "Tabs", "Amoxicillin/Clavulanate", "Hikma", 62),
    ("Megamox Syrup", "312.5 mg/5ml", "Syrup", "Amoxicillin/Clavulanate", "Hikma", 72),
    ("Amoclav", "1 g", "Tabs", "Amoxicillin/Clavulanate", "EIPICO", 88),
    ("Amoclav", "625 mg", "Tabs", "Amoxicillin/Clavulanate", "EIPICO", 68),
    ("Amoclav Syrup", "312.5 mg/5ml", "Syrup", "Amoxicillin/Clavulanate", "EIPICO", 58),
    ("Amoxicillin", "250 mg", "Caps", "Amoxicillin", "EIPICO", 18),
    ("Amoxicillin", "1000 mg", "Tabs", "Amoxicillin", "EIPICO", 42),
    ("Amoxicillin Susp.", "250 mg/5ml", "Susp", "Amoxicillin", "EIPICO", 22),
    ("E-Mox", "250 mg", "Caps", "Amoxicillin", "EIPICO", 18),
    ("E-Mox", "1000 mg", "Tabs", "Amoxicillin", "EIPICO", 45),
    ("E-Mox Susp.", "125 mg/5ml", "Susp", "Amoxicillin", "EIPICO", 18),
    ("E-Mox Forte", "250 mg/5ml", "Susp", "Amoxicillin", "EIPICO", 22),
    ("Hiconcil", "250 mg", "Caps", "Amoxicillin", "Hikma", 22),
    ("Hiconcil", "500 mg", "Caps", "Amoxicillin", "Hikma", 32),
    ("Hiconcil", "1000 mg", "Tabs", "Amoxicillin", "Hikma", 45),
    ("Hiconcil Syrup", "125 mg/5ml", "Syrup", "Amoxicillin", "Hikma", 22),
    ("Moxipil", "250 mg", "Caps", "Amoxicillin", "Medical Union", 18),
    ("Moxipil", "500 mg", "Caps", "Amoxicillin", "Medical Union", 28),
    ("Moxipil", "1000 mg", "Tabs", "Amoxicillin", "Medical Union", 42),
    ("Moxipil Syrup", "125 mg/5ml", "Syrup", "Amoxicillin", "Medical Union", 18),
    ("Amoxil", "250 mg", "Caps", "Amoxicillin", "GSK", 25),
    ("Amoxil", "500 mg", "Caps", "Amoxicillin", "GSK", 35),
    ("Amoxil", "1000 mg", "Tabs", "Amoxicillin", "GSK", 52),
    ("Amoxil Syrup", "125 mg/5ml", "Syrup", "Amoxicillin", "GSK", 25),
    
    # Nitroimidazoles
    ("Flagyl", "200 mg", "Tabs", "Metronidazole", "Sanofi", 22),
    ("Flagyl", "400 mg", "Tabs", "Metronidazole", "Sanofi", 28),
    ("Flagyl Susp.", "125 mg/5ml", "Susp", "Metronidazole", "Sanofi", 28),
    ("Flagyl Supp.", "500 mg", "Supp", "Metronidazole", "Sanofi", 32),
    ("Metronidazole", "200 mg", "Tabs", "Metronidazole", "EIPICO", 15),
    ("Metronidazole", "400 mg", "Tabs", "Metronidazole", "EIPICO", 18),
    ("Metronidazole Susp.", "125 mg/5ml", "Susp", "Metronidazole", "EIPICO", 18),
    ("Nidazole", "200 mg", "Tabs", "Metronidazole", "Medical Union", 14),
    ("Nidazole Susp.", "125 mg/5ml", "Susp", "Metronidazole", "Medical Union", 16),
    ("Tinidazole", "500 mg", "Tabs", "Tinidazole", "EIPICO", 45),
    ("Fasigyn", "500 mg", "Tabs", "Tinidazole", "Pfizer", 55),
    
    # Macrolides
    ("Zithromax", "250 mg", "Tabs", "Azithromycin", "Pfizer", 68),
    ("Zithromax", "600 mg", "Tabs", "Azithromycin", "Pfizer", 115),
    ("Zithromax Susp.", "200 mg/5ml", "Susp", "Azithromycin", "Pfizer", 78),
    ("Zithromax Z-Pak", "250 mg", "Pack", "Azithromycin", "Pfizer", 85),
    ("Zithrokan", "250 mg", "Tabs", "Azithromycin", "Amoun", 55),
    ("Zithrokan Susp.", "200 mg/5ml", "Susp", "Azithromycin", "Amoun", 58),
    ("Zithron", "250 mg", "Tabs", "Azithromycin", "Medical Union", 48),
    ("Zithron", "500 mg", "Tabs", "Azithromycin", "Medical Union", 65),
    ("Zithron Susp.", "200 mg/5ml", "Susp", "Azithromycin", "Medical Union", 52),
    ("Xithrone", "250 mg", "Tabs", "Azithromycin", "Eva", 55),
    ("Xithrone", "500 mg", "Tabs", "Azithromycin", "Eva", 72),
    ("Xithrone Susp.", "200 mg/5ml", "Susp", "Azithromycin", "Eva", 58),
    ("Klacid", "250 mg", "Tabs", "Clarithromycin", "Abbott", 85),
    ("Klacid XL", "500 mg", "Tabs", "Clarithromycin", "Abbott", 135),
    ("Klacid Susp.", "125 mg/5ml", "Susp", "Clarithromycin", "Abbott", 75),
    ("Klacid Forte", "250 mg/5ml", "Susp", "Clarithromycin", "Abbott", 95),
    ("Clarithromycin", "250 mg", "Tabs", "Clarithromycin", "EIPICO", 55),
    ("Clarithromycin", "500 mg", "Tabs", "Clarithromycin", "EIPICO", 88),
    ("Clarithromycin XL", "500 mg", "Tabs", "Clarithromycin", "EIPICO", 95),
    ("Claridar", "250 mg", "Tabs", "Clarithromycin", "Medical Union", 52),
    ("Claridar", "500 mg", "Tabs", "Clarithromycin", "Medical Union", 82),
    ("Erythrocin", "250 mg", "Tabs", "Erythromycin", "Abbott", 35),
    ("Erythrocin Susp.", "200 mg/5ml", "Susp", "Erythromycin", "Abbott", 32),
    ("E-Mycin", "250 mg", "Tabs", "Erythromycin", "EIPICO", 28),
    ("E-Mycin Susp.", "200 mg/5ml", "Susp", "Erythromycin", "EIPICO", 25),
    
    # Fluoroquinolones
    ("Ciprobay", "250 mg", "Tabs", "Ciprofloxacin", "Bayer", 55),
    ("Ciprobay", "750 mg", "Tabs", "Ciprofloxacin", "Bayer", 115),
    ("Ciprobay XR", "500 mg", "Tabs", "Ciprofloxacin", "Bayer", 95),
    ("Ciprobay", "200 mg/100ml", "IV Inf", "Ciprofloxacin", "Bayer", 125),
    ("Ciprofloxacin", "250 mg", "Tabs", "Ciprofloxacin", "EIPICO", 35),
    ("Ciprofloxacin", "750 mg", "Tabs", "Ciprofloxacin", "EIPICO", 75),
    ("Ciprofar", "250 mg", "Tabs", "Ciprofloxacin", "Amoun", 38),
    ("Ciprofar", "750 mg", "Tabs", "Ciprofloxacin", "Amoun", 82),
    ("Cipromax", "250 mg", "Tabs", "Ciprofloxacin", "Medical Union", 32),
    ("Cipromax", "500 mg", "Tabs", "Ciprofloxacin", "Medical Union", 58),
    ("Cipromax", "750 mg", "Tabs", "Ciprofloxacin", "Medical Union", 78),
    ("Ciprocin", "250 mg", "Tabs", "Ciprofloxacin", "Eva", 35),
    ("Ciprocin", "500 mg", "Tabs", "Ciprofloxacin", "Eva", 60),
    ("Ciprocin", "750 mg", "Tabs", "Ciprofloxacin", "Eva", 82),
    ("Tavanic", "250 mg", "Tabs", "Levofloxacin", "Sanofi", 85),
    ("Tavanic", "750 mg", "Tabs", "Levofloxacin", "Sanofi", 135),
    ("Tavanic IV", "500 mg/100ml", "IV Sol", "Levofloxacin", "Sanofi", 145),
    ("Levofloxacin", "250 mg", "Tabs", "Levofloxacin", "EIPICO", 55),
    ("Levofloxacin", "750 mg", "Tabs", "Levofloxacin", "EIPICO", 95),
    ("Levox", "250 mg", "Tabs", "Levofloxacin", "Amoun", 62),
    ("Levox", "750 mg", "Tabs", "Levofloxacin", "Amoun", 102),
    ("Cravit", "500 mg", "Tabs", "Levofloxacin", "Medical Union", 78),
    ("Cravit", "750 mg", "Tabs", "Levofloxacin", "Medical Union", 98),
    ("Avelox", "400 mg", "Tabs", "Moxifloxacin", "Bayer", 155),
    ("Avelox IV", "400 mg/250ml", "IV Inf", "Moxifloxacin", "Bayer", 185),
    ("Moxifloxacin", "400 mg", "Tabs", "Moxifloxacin", "EIPICO", 95),
    ("Moxiflox", "400 mg", "Tabs", "Moxifloxacin", "Amoun", 105),
    
    # Cephalosporins
    ("Cefix", "200 mg", "Tabs", "Cefixime", "EIPICO", 45),
    ("Cefix Susp.", "100 mg/5ml", "Susp", "Cefixime", "EIPICO", 38),
    ("Cefix Forte", "200 mg/5ml", "Susp", "Cefixime", "EIPICO", 52),
    ("Suprax", "200 mg", "Tabs", "Cefixime", "Lupin", 55),
    ("Suprax Susp.", "100 mg/5ml", "Susp", "Cefixime", "Lupin", 45),
    ("Suprax Forte", "200 mg/5ml", "Susp", "Cefixime", "Lupin", 62),
    ("Fortum", "250 mg", "IV/IM", "Ceftazidime", "GSK", 85),
    ("Fortum", "500 mg", "IV/IM", "Ceftazidime", "GSK", 125),
    ("Fortum", "2 g", "IV", "Ceftazidime", "GSK", 285),
    ("Ceftazidime", "1 g", "IV/IM", "Ceftazidime", "EIPICO", 145),
    ("Ceftazidime", "500 mg", "IV/IM", "Ceftazidime", "EIPICO", 95),
    ("Rocephin", "250 mg", "IM/IV", "Ceftriaxone", "Roche", 75),
    ("Rocephin", "500 mg", "IM/IV", "Ceftriaxone", "Roche", 115),
    ("Rocephin", "2 g", "IV", "Ceftriaxone", "Roche", 265),
    ("Ceftriaxone", "1 g", "IM/IV", "Ceftriaxone", "EIPICO", 125),
    ("Ceftriaxone", "500 mg", "IM/IV", "Ceftriaxone", "EIPICO", 85),
    ("Ceftriaxone", "250 mg", "IM/IV", "Ceftriaxone", "EIPICO", 55),
    ("Cefatrexyl", "1 g", "IM/IV", "Ceftriaxone", "Amoun", 115),
    ("Cefatrexyl", "500 mg", "IM/IV", "Ceftriaxone", "Amoun", 78),
    ("Claforan", "500 mg", "IM/IV", "Cefotaxime", "Sanofi", 115),
    ("Claforan", "1 g", "IM/IV", "Cefotaxime", "Sanofi", 175),
    ("Claforan", "2 g", "IV", "Cefotaxime", "Sanofi", 285),
    ("Cefotax", "250 mg", "IM/IV", "Cefotaxime", "EIPICO", 65),
    ("Cefotax", "500 mg", "IM/IV", "Cefotaxime", "EIPICO", 95),
    ("Cefotax", "1 g", "IM/IV", "Cefotaxime", "EIPICO", 145),
    ("Zinacef", "250 mg", "IM/IV", "Cefuroxime", "GSK", 55),
    ("Zinacef", "1.5 g", "IM/IV", "Cefuroxime", "GSK", 145),
    ("Zinacef", "750 mg", "IM Inj", "Cefuroxime", "GSK", 85),
    ("Cefuroxime", "250 mg", "IM/IV", "Cefuroxime", "EIPICO", 42),
    ("Cefuroxime", "750 mg", "IM/IV", "Cefuroxime", "EIPICO", 72),
    ("Cefuroxime", "1.5 g", "IM/IV", "Cefuroxime", "EIPICO", 115),
    ("Cefurab", "750 mg", "IM/IV", "Cefuroxime", "Amoun", 68),
    ("Cefurab", "1.5 g", "IM/IV", "Cefuroxime", "Amoun", 108),
    
    # Antifungals
    ("Diflucan", "50 mg", "Caps", "Fluconazole", "Pfizer", 55),
    ("Diflucan", "200 mg", "Tabs", "Fluconazole", "Pfizer", 115),
    ("Diflucan Susp.", "50 mg/5ml", "Susp", "Fluconazole", "Pfizer", 65),
    ("Diflucan IV", "200 mg/100ml", "IV Inf", "Fluconazole", "Pfizer", 135),
    ("Fluconazole", "200 mg", "Caps", "Fluconazole", "EIPICO", 58),
    ("Flucon", "150 mg", "Caps", "Fluconazole", "Amoun", 38),
    ("Flucon", "200 mg", "Caps", "Fluconazole", "Amoun", 55),
    ("Nizoral", "2%", "Shampoo", "Ketoconazole", "Janssen", 75),
    ("Nizoral", "2%", "Cream", "Ketoconazole", "Janssen", 65),
    ("Ketoconazole", "200 mg", "Tabs", "Ketoconazole", "EIPICO", 55),
    ("Ketozole", "200 mg", "Tabs", "Ketoconazole", "Amoun", 48),
    ("Ketozole", "2%", "Shampoo", "Ketoconazole", "Amoun", 55),
    ("Ketozole", "2%", "Cream", "Ketoconazole", "Amoun", 48),
    ("Sporanox", "10 mg/ml", "Sol", "Itraconazole", "Janssen", 165),
    ("Itraconazole", "100 mg", "Caps", "Itraconazole", "EIPICO", 85),
    ("Itrazole", "100 mg", "Caps", "Itraconazole", "Amoun", 78),
    ("Candistat", "100 mg", "Caps", "Itraconazole", "Eva", 72),
    ("Candistat", "200 mg", "Caps", "Itraconazole", "Eva", 115),
    ("Lamisil", "1%", "Cream", "Terbinafine", "Novartis", 95),
    ("Lamisil", "1%", "Spray", "Terbinafine", "Novartis", 105),
    ("Lamisil", "1%", "Gel", "Terbinafine", "Novartis", 92),
    ("Terbinafine", "250 mg", "Tabs", "Terbinafine", "EIPICO", 115),
    ("Tebina", "250 mg", "Tabs", "Terbinafine", "Amoun", 105),
    ("Tebina", "1%", "Cream", "Terbinafine", "Amoun", 58),
    
    # Antivirals
    ("Zovirax", "200 mg", "Tabs", "Acyclovir", "GSK", 55),
    ("Zovirax", "800 mg", "Tabs", "Acyclovir", "GSK", 125),
    ("Zovirax", "5%", "Cream", "Acyclovir", "GSK", 75),
    ("Zovirax", "5%", "Oint", "Acyclovir", "GSK", 65),
    ("Acivir", "200 mg", "Tabs", "Acyclovir", "Amoun", 28),
    ("Acivir", "400 mg", "Tabs", "Acyclovir", "Amoun", 45),
    ("Acivir", "5%", "Cream", "Acyclovir", "Amoun", 48),
    ("Acivirax", "200 mg", "Tabs", "Acyclovir", "Eva", 32),
    ("Acivirax", "400 mg", "Tabs", "Acyclovir", "Eva", 48),
    ("Acivirax", "800 mg", "Tabs", "Acyclovir", "Eva", 75),
    ("Valtrex", "1000 mg", "Tabs", "Valacyclovir", "GSK", 385),
    ("Valacyclovir", "500 mg", "Tabs", "Valacyclovir", "EIPICO", 165),
    ("Valtrexol", "500 mg", "Tabs", "Valacyclovir", "Amoun", 145),
    ("Tamiflu Susp.", "12 mg/ml", "Susp", "Oseltamivir", "Roche", 325),
    ("Oseltamivir", "75 mg", "Caps", "Oseltamivir", "EIPICO", 185),
    ("Oselvir", "75 mg", "Caps", "Oseltamivir", "Amoun", 165),
    ("Antiflu", "75 mg", "Caps", "Oseltamivir", "Eva", 155),
    
    # Antihypertensives - More Amlodipine
    ("Norvasc", "2.5 mg", "Tabs", "Amlodipine", "Pfizer", 42),
    ("Amlodipine", "2.5 mg", "Tabs", "Amlodipine", "EIPICO", 25),
    ("Amlor", "2.5 mg", "Tabs", "Amlodipine", "Sanofi", 38),
    ("Amlodip", "2.5 mg", "Tabs", "Amlodipine", "Amoun", 22),
    ("Amlodip", "5 mg", "Tabs", "Amlodipine", "Amoun", 32),
    ("Amlodip", "10 mg", "Tabs", "Amlodipine", "Amoun", 48),
    
    # More Beta Blockers
    ("Concor", "2.5 mg", "Tabs", "Bisoprolol", "Merck", 35),
    ("Concor Plus", "5/12.5 mg", "Tabs", "Bisoprolol/HCTZ", "Merck", 65),
    ("Concor Plus", "10/12.5 mg", "Tabs", "Bisoprolol/HCTZ", "Merck", 95),
    ("Bisoprolol", "5 mg", "Tabs", "Bisoprolol", "EIPICO", 38),
    ("Bisoprolol", "10 mg", "Tabs", "Bisoprolol", "EIPICO", 58),
    ("Bisorol", "2.5 mg", "Tabs", "Bisoprolol", "Amoun", 25),
    ("Bisorol", "5 mg", "Tabs", "Bisoprolol", "Amoun", 32),
    ("Bisorol", "10 mg", "Tabs", "Bisoprolol", "Amoun", 48),
    
    # ACE Inhibitors
    ("Coversyl", "4 mg", "Tabs", "Perindopril", "Servier", 75),
    ("Coversyl Plus", "10/2.5 mg", "Tabs", "Perindopril/Indapamide", "Servier", 135),
    ("Perindopril", "4 mg", "Tabs", "Perindopril", "EIPICO", 55),
    ("Perindopril", "8 mg", "Tabs", "Perindopril", "EIPICO", 88),
    ("Perindocor", "4 mg", "Tabs", "Perindopril", "Amoun", 48),
    ("Perindocor", "8 mg", "Tabs", "Perindopril", "Amoun", 78),
    
    # ARBs
    ("Cozaar", "100 mg", "Tabs", "Losartan", "Merck", 125),
    ("Cozaar Plus", "50/12.5 mg", "Tabs", "Losartan/HCTZ", "Merck", 95),
    ("Losartan", "50 mg", "Tabs", "Losartan", "EIPICO", 58),
    ("Losar", "50 mg", "Tabs", "Losartan", "Amoun", 48),
    ("Losar Plus", "50/12.5 mg", "Tabs", "Losartan/HCTZ", "Amoun", 58),
    ("Angizaar", "50 mg", "Tabs", "Losartan", "Eva", 52),
    ("Diovan", "80 mg", "Tabs", "Valsartan", "Novartis", 95),
    ("Diovan", "320 mg", "Tabs", "Valsartan", "Novartis", 185),
    ("Diovan Plus", "80/12.5 mg", "Tabs", "Valsartan/HCTZ", "Novartis", 115),
    ("Diovan Plus", "160/25 mg", "Tabs", "Valsartan/HCTZ", "Novartis", 165),
    ("Valsartan", "80 mg", "Tabs", "Valsartan", "EIPICO", 68),
    ("Valsar", "80 mg", "Tabs", "Valsartan", "Amoun", 58),
    ("Valsar", "160 mg", "Tabs", "Valsartan", "Amoun", 92),
    ("Valsar Plus", "160/12.5 mg", "Tabs", "Valsartan/HCTZ", "Amoun", 75),
    ("Micardis", "40 mg", "Tabs", "Telmisartan", "BI", 105),
    ("Micardis Plus", "40/12.5 mg", "Tabs", "Telmisartan/HCTZ", "BI", 125),
    ("Micardis Plus", "80/12.5 mg", "Tabs", "Telmisartan/HCTZ", "BI", 175),
    ("Telmisartan", "40 mg", "Tabs", "Telmisartan", "EIPICO", 72),
    ("Telmista", "40 mg", "Tabs", "Telmisartan", "Amoun", 62),
    ("Telmista", "80 mg", "Tabs", "Telmisartan", "Amoun", 98),
    
    # More Beta Blockers
    ("Tenormin", "100 mg", "Tabs", "Atenolol", "AstraZeneca", 65),
    ("Atenolol", "50 mg", "Tabs", "Atenolol", "EIPICO", 28),
    ("Atenocor", "50 mg", "Tabs", "Atenolol", "Amoun", 25),
    ("Atenocor", "100 mg", "Tabs", "Atenolol", "Amoun", 38),
    ("Zestril", "5 mg", "Tabs", "Lisinopril", "AstraZeneca", 55),
    ("Zestril", "20 mg", "Tabs", "Lisinopril", "AstraZeneca", 95),
    ("Lisinopril", "10 mg", "Tabs", "Lisinopril", "EIPICO", 38),
    ("Lisinopril", "20 mg", "Tabs", "Lisinopril", "EIPICO", 58),
    ("Lisoril", "10 mg", "Tabs", "Lisinopril", "Amoun", 32),
    ("Lisoril", "20 mg", "Tabs", "Lisinopril", "Amoun", 48),
    ("Tritace", "2.5 mg", "Tabs", "Ramipril", "Sanofi", 55),
    ("Tritace Plus", "5/25 mg", "Tabs", "Ramipril/HCTZ", "Sanofi", 85),
    ("Ramipril", "5 mg", "Tabs", "Ramipril", "EIPICO", 48),
    ("Ramipril", "10 mg", "Tabs", "Ramipril", "EIPICO", 72),
    ("Ramicor", "2.5 mg", "Tabs", "Ramipril", "Amoun", 28),
    ("Ramicor", "5 mg", "Tabs", "Ramipril", "Amoun", 42),
    ("Ramicor", "10 mg", "Tabs", "Ramipril", "Amoun", 62),
    ("Capoten", "50 mg", "Tabs", "Captopril", "BMS", 52),
    ("Captopril", "25 mg", "Tabs", "Captopril", "EIPICO", 18),
    ("Captopril", "50 mg", "Tabs", "Captopril", "EIPICO", 32),
    ("Captocor", "25 mg", "Tabs", "Captopril", "Amoun", 15),
    ("Captocor", "50 mg", "Tabs", "Captopril", "Amoun", 28),
    ("Dilatrend", "6.25 mg", "Tabs", "Carvedilol", "Roche", 55),
    ("Dilatrend", "12.5 mg", "Tabs", "Carvedilol", "Roche", 75),
    ("Dilatrend", "25 mg", "Tabs", "Carvedilol", "Roche", 105),
    ("Carvedilol", "12.5 mg", "Tabs", "Carvedilol", "EIPICO", 48),
    ("Carvedilol", "25 mg", "Tabs", "Carvedilol", "EIPICO", 68),
    ("Carvid", "6.25 mg", "Tabs", "Carvedilol", "Amoun", 32),
    ("Carvid", "12.5 mg", "Tabs", "Carvedilol", "Amoun", 42),
    ("Carvid", "25 mg", "Tabs", "Carvedilol", "Amoun", 58),
    ("Lopressor", "50 mg", "Tabs", "Metoprolol", "Novartis", 45),
    ("Lopressor SR", "200 mg", "Tabs", "Metoprolol", "Novartis", 95),
    ("Metoprolol", "50 mg", "Tabs", "Metoprolol", "EIPICO", 28),
    ("Metoprolol", "100 mg", "Tabs", "Metoprolol", "EIPICO", 42),
    ("Metocor", "50 mg", "Tabs", "Metoprolol", "Amoun", 25),
    ("Metocor", "100 mg", "Tabs", "Metoprolol", "Amoun", 38),
    
    # Diuretics
    ("Aldactone", "25 mg", "Tabs", "Spironolactone", "Pfizer", 32),
    ("Aldactone", "100 mg", "Tabs", "Spironolactone", "Pfizer", 55),
    ("Spironolactone", "25 mg", "Tabs", "Spironolactone", "EIPICO", 18),
    ("Spironolactone", "50 mg", "Tabs", "Spironolactone", "EIPICO", 32),
    ("Spironolactone", "100 mg", "Tabs", "Spironolactone", "EIPICO", 42),
    ("Spirocor", "25 mg", "Tabs", "Spironolactone", "Amoun", 15),
    ("Spirocor", "50 mg", "Tabs", "Spironolactone", "Amoun", 22),
    ("Spirocor", "100 mg", "Tabs", "Spironolactone", "Amoun", 28),
    ("Lasix", "40 mg", "Tabs", "Furosemide", "Sanofi", 25),
    ("Lasix", "500 mg", "Tabs", "Furosemide", "Sanofi", 55),
    ("Lasix", "20 mg/2ml", "Amp", "Furosemide", "Sanofi", 22),
    ("Furosemide", "40 mg", "Tabs", "Furosemide", "EIPICO", 12),
    ("Furocor", "40 mg", "Tabs", "Furosemide", "Amoun", 10),
    ("Natrilix", "1.5 mg", "Tabs", "Indapamide", "Servier", 55),
    ("Natrilix", "2.5 mg", "Tabs", "Indapamide", "Servier", 75),
    ("Natrilix SR", "1.5 mg", "Tabs", "Indapamide", "Servier", 65),
    ("Indapamide", "1.5 mg", "Tabs", "Indapamide", "EIPICO", 32),
    ("Indapamide", "2.5 mg", "Tabs", "Indapamide", "EIPICO", 48),
    ("Indacor", "1.5 mg", "Tabs", "Indapamide", "Amoun", 28),
    
    # Antidiabetics - Metformin
    ("Glucophage XR", "500 mg", "Tabs", "Metformin", "Merck", 38),
    ("Glucophage XR", "750 mg", "Tabs", "Metformin", "Merck", 52),
    ("Metformin", "500 mg", "Tabs", "Metformin", "EIPICO", 18),
    ("Metformin", "850 mg", "Tabs", "Metformin", "EIPICO", 28),
    ("Metformin", "1000 mg", "Tabs", "Metformin", "EIPICO", 38),
    ("Metformax", "500 mg", "Tabs", "Metformin", "Amoun", 15),
    ("Metformax", "850 mg", "Tabs", "Metformin", "Amoun", 22),
    ("Metformax XR", "1000 mg", "Tabs", "Metformin", "Amoun", 42),
    ("Amaryl", "1 mg", "Tabs", "Glimepiride", "Sanofi", 35),
    ("Amaryl", "3 mg", "Tabs", "Glimepiride", "Sanofi", 75),
    ("Amaryl M", "1/500 mg", "Tabs", "Glimepiride/Metformin", "Sanofi", 52),
    ("Amaryl M", "2/500 mg", "Tabs", "Glimepiride/Metformin", "Sanofi", 72),
    ("Glimepiride", "1 mg", "Tabs", "Glimepiride", "EIPICO", 22),
    ("Glimepiride", "2 mg", "Tabs", "Glimepiride", "EIPICO", 32),
    ("Glimepiride", "3 mg", "Tabs", "Glimepiride", "EIPICO", 48),
    ("Glimerax", "1 mg", "Tabs", "Glimepiride", "Amoun", 18),
    ("Glimerax", "2 mg", "Tabs", "Glimepiride", "Amoun", 28),
    ("Glimerax", "3 mg", "Tabs", "Glimepiride", "Amoun", 42),
    ("Glimerax", "4 mg", "Tabs", "Glimepiride", "Amoun", 55),
    ("Diamicron", "30 mg", "Tabs", "Gliclazide", "Servier", 45),
    ("Diamicron MR", "30 mg", "Tabs", "Gliclazide", "Servier", 55),
    ("Diamicron MR", "60 mg", "Tabs", "Gliclazide", "Servier", 85),
    ("Gliclazide", "80 mg", "Tabs", "Gliclazide", "EIPICO", 25),
    ("Gliclazide MR", "30 mg", "Tabs", "Gliclazide", "EIPICO", 32),
    ("Gliclacor", "80 mg", "Tabs", "Gliclazide", "Amoun", 22),
    ("Glucotrol", "10 mg", "Tabs", "Glipizide", "Pfizer", 52),
    ("Glucotrol XL", "5 mg", "Tabs", "Glipizide", "Pfizer", 42),
    ("Glucotrol XL", "10 mg", "Tabs", "Glipizide", "Pfizer", 65),
    ("Glipizide", "5 mg", "Tabs", "Glipizide", "EIPICO", 18),
    ("Glipizide", "10 mg", "Tabs", "Glipizide", "EIPICO", 32),
    ("Glibizid", "5 mg", "Tabs", "Glipizide", "Amoun", 15),
    ("Daonil", "5 mg", "Tabs", "Glibenclamide", "Sanofi", 15),
    ("Glibenclamide", "5 mg", "Tabs", "Glibenclamide", "EIPICO", 8),
    ("Glibenax", "5 mg", "Tabs", "Glibenclamide", "Amoun", 6.5),
    ("Actos", "15 mg", "Tabs", "Pioglitazone", "Takeda", 105),
    ("Actos", "45 mg", "Tabs", "Pioglitazone", "Takeda", 195),
    ("Pioglitazone", "15 mg", "Tabs", "Pioglitazone", "EIPICO", 72),
    ("Pioglitazone", "30 mg", "Tabs", "Pioglitazone", "EIPICO", 115),
    ("Piozid", "15 mg", "Tabs", "Pioglitazone", "Amoun", 62),
    ("Piozid", "30 mg", "Tabs", "Pioglitazone", "Amoun", 98),
    ("Januvia", "25 mg", "Tabs", "Sitagliptin", "MSD", 125),
    ("Januvia", "50 mg", "Tabs", "Sitagliptin", "MSD", 185),
    ("Janumet", "50/500 mg", "Tabs", "Sitagliptin/Metformin", "MSD", 225),
    ("Janumet", "50/850 mg", "Tabs", "Sitagliptin/Metformin", "MSD", 285),
    ("Janumet", "50/1000 mg", "Tabs", "Sitagliptin/Metformin", "MSD", 325),
    ("Janumet XR", "100/1000 mg", "Tabs", "Sitagliptin/Metformin", "MSD", 355),
    ("Sitagliptin", "25 mg", "Tabs", "Sitagliptin", "EIPICO", 85),
    ("Sitagliptin", "50 mg", "Tabs", "Sitagliptin", "EIPICO", 125),
    ("Galvus", "100 mg", "Tabs", "Vildagliptin", "Novartis", 255),
    ("Galvus Met", "50/500 mg", "Tabs", "Vildagliptin/Metformin", "Novartis", 195),
    ("Galvus Met", "50/850 mg", "Tabs", "Vildagliptin/Metformin", "Novartis", 225),
    ("Galvus Met", "50/1000 mg", "Tabs", "Vildagliptin/Metformin", "Novartis", 255),
    ("Vildagliptin", "50 mg", "Tabs", "Vildagliptin", "EIPICO", 95),
    ("Vildamet", "50/1000 mg", "Tabs", "Vildagliptin/Metformin", "EIPICO", 145),
    ("Onglyza", "2.5 mg", "Tabs", "Saxagliptin", "AstraZeneca", 145),
    ("Kombiglyze", "5/500 mg", "Tabs", "Saxagliptin/Metformin", "AstraZeneca", 225),
    ("Kombiglyze", "5/1000 mg", "Tabs", "Saxagliptin/Metformin", "AstraZeneca", 265),
    ("Trajenta", "5 mg", "Tabs", "Linagliptin", "BI", 195),
    ("Jentadueto", "2.5/500 mg", "Tabs", "Linagliptin/Metformin", "BI", 225),
    ("Jentadueto", "2.5/850 mg", "Tabs", "Linagliptin/Metformin", "BI", 255),
    ("Jentadueto", "2.5/1000 mg", "Tabs", "Linagliptin/Metformin", "BI", 285),
    ("Forxiga", "5 mg", "Tabs", "Dapagliflozin", "AstraZeneca", 265),
    ("Xigduo", "5/850 mg", "Tabs", "Dapagliflozin/Metformin", "AstraZeneca", 325),
    ("Xigduo", "5/1000 mg", "Tabs", "Dapagliflozin/Metformin", "AstraZeneca", 355),
    ("Jardiance", "10 mg", "Tabs", "Empagliflozin", "BI", 295),
    ("Jardiance", "25 mg", "Tabs", "Empagliflozin", "BI", 425),
    ("Synjardy", "5/850 mg", "Tabs", "Empagliflozin/Metformin", "BI", 355),
    ("Synjardy", "12.5/1000 mg", "Tabs", "Empagliflozin/Metformin", "BI", 485),
    ("Invokana", "100 mg", "Tabs", "Canagliflozin", "Janssen", 255),
    ("Invokana", "300 mg", "Tabs", "Canagliflozin", "Janssen", 385),
    ("Vokanamet", "50/850 mg", "Tabs", "Canagliflozin/Metformin", "Janssen", 325),
    ("Vokanamet", "50/1000 mg", "Tabs", "Canagliflozin/Metformin", "Janssen", 355),
    ("Steglatro", "5 mg", "Tabs", "Ertugliflozin", "MSD", 225),
    ("Steglatro", "15 mg", "Tabs", "Ertugliflozin", "MSD", 325),
    ("Segluromet", "2.5/500 mg", "Tabs", "Ertugliflozin/Metformin", "MSD", 285),
    ("Segluromet", "7.5/1000 mg", "Tabs", "Ertugliflozin/Metformin", "MSD", 385),
    ("Victoza", "6 mg/ml", "Prefilled Pen", "Liraglutide", "Novo Nordisk", 625),
    ("Saxenda", "6 mg/ml", "Pen", "Liraglutide", "Novo Nordisk", 725),
    ("Byetta", "250 mcg/ml", "Prefilled Pen", "Exenatide", "AstraZeneca", 485),
    ("Bydureon", "2 mg", "Pen", "Exenatide", "AstraZeneca", 585),
    ("Trulicity", "0.75 mg/0.5ml", "Pen", "Dulaglutide", "Eli Lilly", 685),
    ("Trulicity", "1.5 mg/0.5ml", "Pen", "Dulaglutide", "Eli Lilly", 785),
    ("Ozempic", "0.25 mg", "Pen", "Semaglutide", "Novo Nordisk", 785),
    ("Ozempic", "0.5 mg", "Pen", "Semaglutide", "Novo Nordisk", 885),
    ("Rybelsus", "3 mg", "Tabs", "Semaglutide", "Novo Nordisk", 825),
    ("Rybelsus", "7 mg", "Tabs", "Semaglutide", "Novo Nordisk", 925),
    ("Rybelsus", "14 mg", "Tabs", "Semaglutide", "Novo Nordisk", 1085),
    ("Wegovy", "0.25 mg", "Pen", "Semaglutide", "Novo Nordisk", 925),
    ("Wegovy", "0.5 mg", "Pen", "Semaglutide", "Novo Nordisk", 1085),
    ("Mounjaro", "2.5 mg", "Pen", "Tirzepatide", "Eli Lilly", 885),
    ("Mounjaro", "5 mg", "Pen", "Tirzepatide", "Eli Lilly", 985),
    ("Mounjaro", "10 mg", "Pen", "Tirzepatide", "Eli Lilly", 1185),
    ("Zepbound", "2.5 mg", "Pen", "Tirzepatide", "Eli Lilly", 925),
]

for drug_data in additional_drugs:
    add_drug(*drug_data)

# Save
output = {"drugs": drugs}
with open('data/egyptian-drugs-gtin-expanded.json', 'w', encoding='utf-8') as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print(f"Total drugs now: {len(drugs)}")
